### ISSUE TITLE
Page is moved up on input in long textboxes [Firefox]

### ISSUE THREAD

**Issue by niijv** [lektor/lektor#1]
When editing long text the page moved up as far as possible on input.
Firefox only.

**Comment by tino** [comment]
I think I get the same problem with Safari. When I change the class of the bottom text block of the root of the lektor-website project, the page jumps up a bit.

**Comment by niijv** [comment]
Using safari on OSX i assume?

**Comment by tino** [comment]
Yes

**Comment by georgkaser** [comment]
I think this is not fixed. A very annoying behaviour happens with flow elements in Firefox:

![Firefox](https://user-images.githubusercontent.com/6472869/54288723-38b94900-45a8-11e9-9497-3438ccebe98a.gif)

This is what it looks like in Chrome (Chromium in my case):

![chrome](https://user-images.githubusercontent.com/6472869/54288779-51296380-45a8-11e9-869b-78ef73d76ce2.gif)

**Comment by runfalk** [comment]
This is definitely still an issue in Firefox. I do however think it's better to open a new issue for it. I think the root causes are different. I think the current issue is how we dynamically recalculate the input height on input.

Could you open a new issue and attach your images, or should I do it?

**Comment by georgkaser** [comment]
I'll do it ;)

**Comment by photong** [comment]
We're still seeing this problem in Firefox 98 and Chromium 98. For Chromium, new markdown content can be edited without page movement. However, input in a field with existing markdown content causes the problem shown by @georgkaser. This makes Lektor admin unusable for editing content.

**Comment by georgkaser** [comment]
Yes, this bug still exists in Firefox 98. Now also in Chromium 99 - I tested it now one more time.

It should be fixed soon, because it's abslolute unuseable (please not another 7 years :))

**Comment by photong** [comment]
Maybe Chrome 99 fixed it :) Of note, Gnome Web (based on WebKitGTK) doesn't exhibit the bug.

**Comment by bngsudheer** [comment]
This is still an issue in Firefox: Mozilla Firefox 103.0.2
Chrome: Google Chrome 104.0.5112.101

**Comment by photong** [comment]
I have just installed Lektor 3.3.6 (using pipx). This problem is finally solved for me (hallelujah). Tested in Firefox 103.0.2 (Linux Mint).

**Comment by bngsudheer** [comment]
I removed all Lektor files and installed 3.3.6 via pipx. The problem is solved. :)
