### ISSUE TITLE
Implement locale-aware sort() and dictsort() filters

### ISSUE THREAD

**Issue by paternal** [lektor/lektor#1005]
My French website has a [tag cloud](https://ababsurdo.fr/blog/tag/) (implemented using [this template](https://framagit.org/lpaternault/ababsurdo/-/blob/ebbb0a0084d704b5a81a3b84b3c9de831a28cabe/templates/blocks/tagcloud-block.html)). My problem is that because the sort is not aware of locale, the tag ``énigme`` is sorted at the very end because it starts with a diacritic, while it should be sorted with other tags starting with "e".

I opened an [issue on the jinja project](https://github.com/pallets/jinja/issues/1583), but I wonder whether the solution should come from jinja or lektor.

It would be nice if lektor provided ``locale_sort()`` and ``locale_dictsort()`` filters, which would behave like ``sort()`` and ``dictsort()``, but the sort would be localized. They could have a ``locale`` parameter:
- if ``locale==None`` (default): use the [locale of the current context](https://www.getlektor.com/docs/api/build/context/locale/);
- otherwise, use the provided locale (e.g. ``{{ some_list | locale_sort(locale="fr_FR") }}``).

I could implement this, but… I cannot see how to do so. The obvious way would be use the [``locale.strxfrm()``](https://docs.python.org/3/library/locale.html#locale.strxfrm) function, but it is not thread-safe. Unfortunately, [Babel does not provide such tools](https://github.com/python-babel/babel/issues/154). Any idea?

I know I could implement it as "dirty" plugin, using ``locale.strxfrm()`` (since my website only has one locale), but since Lektor supports different locales, it would be nice to have this feature.

Thanks,
Louis

**Comment by dairiki** [comment]
As you say, switching between different locales is fraught.

A somewhat hokey alternative is use [unidecode.unidecode](https://pypi.org/project/Unidecode/) as a key function.  It is not truly locale-aware, but should, at least, be able to cope with most languages in a somewhat sane way.  It's probably good enough for ordering tag clouds.

**Comment by paternal** [comment]
> A somewhat hokey alternative is use [unidecode.unidecode](https://pypi.org/project/Unidecode/) as a key function. It is not truly locale-aware, but should, at least, be able to cope with most languages in a somewhat sane way. It's probably good enough for ordering tag clouds.

- If this is a hint to write my custom quick-and-dirty plugin, thanks.
- If this is a clue to implement something in Lektor (adding sortunidecode() and dictsortunidecode() filters), I can write a pull request (but I think that this is something that should be in jinja2 rather than lektor, and jinja2 people [don't seem to be really interested](https://github.com/pallets/jinja/issues/1583#issuecomment-1055086598).

**Comment by dairiki** [comment]
@paternal My feeling is that since this is not a truly _correct_ solution to the local-aware sort issue it would be better placed in a Lektor plugin — ideally one published on PyPI and in the [plugin listing](https://www.getlektor.com/plugins/) on the Lektor website, so that it is easily usable by others.

Alternatively, it could be packaged as an external jinja [extension](https://jinja.palletsprojects.com/en/3.0.x/extensions/#extension-api).  This would still require a trival custom Lektor plugin in order to configure its use, but would make the filters easily available to jinja users.

**Comment by paternal** [comment]
Following @dairiki's advice, I wrote a [unidecode-sort](https://framagit.org/lpaternault/ababsurdo/-/tree/main/packages/unidecode-sort) plugin, which provides `unidecode_sort()` and `unidecode_dictsort()` filters, which act like `sort()` and `dictsort()`, but using [unidecode.unidecode](pypi.org/p/unidecode) as a key function.

I was too lazy to publish a proper package for it, but if someone politely asks for it, I might get the courage to build a package.
