### ISSUE TITLE
Can't use a flow field in your example.

### ISSUE THREAD

**Issue by matrixise** [lektor/lektor#1008]
With your example, I just added this field in `models/project.ini`, and via the admin interface, I tried to add a new `flow` field into `Project A`.

Result -> Crash of the frontend interface.

```ini
[fields.flow]
label = Flow
type = flow
flow_blocks = text_and_html, text
```

My commit for testing: https://github.com/matrixise/lektor/commit/9382c39ac95efc68c2ec4c9a92d80863b454a86f

**Comment by matrixise** [comment]
<img width="691" alt="Screenshot 2022-03-01 at 06 53 49" src="https://user-images.githubusercontent.com/38737/156114226-9a307230-f3e6-46b7-af9d-6075706cbf1f.png">

**Comment by matrixise** [comment]
This issue is related to https://github.com/lektor/lektor/commit/a88b90e60d964c8d81dbd92042374bdfdb7dc50e . you need to release a new version of `lektor`

**Comment by dairiki** [comment]
I've just pushed Lektor [3.3.2](https://pypi.org/project/Lektor/3.3.2/).  Thank you for the kick.

Closing this issue.  Re-open if the issue persists.
