### ISSUE TITLE
Lektor server  command fails

### ISSUE THREAD

**Issue by gnuza** [lektor/lektor#1018]
I noticed that lektor server command failed while I was trying to use it.

Got the command to work and server up by changing line from buildfailures.py

"from werkzeug.debug.tbtools import Traceback" to "from werkzeug.debug.tbtools import DebugTraceback"

**Comment by dairiki** [comment]
Lektor is using undocumented internal API from `werkzeug.debug.tbtools`. That API was significantly refactored in werkzeug 2.1.0 which was released yesterday.

I will work on a fix for Lektor soon.

In the interim, pinning `werkzeug<2.1.0` is probably the safest fix.

**Comment by dairiki** [comment]
Fixed in release 3.3.3.
