### ISSUE TITLE
change in asset does not trigger change in templates that use asseturl

### ISSUE THREAD

**Issue by gotyaoi** [lektor/lektor#1020]
For templates using an asseturl filter, if you change the content of the referenced asset, lektor build does not trigger rebuilds of pages based on that template, leaving the old asset hash in place on those pages.

python 3.9.9
lektor 3.3.2

installed manually in a venv
python3 -m venv lektor_venv
./lektor_venv/bin/pip install -U pip
./lektor_venv/bin/pip install lektor

**Comment by dairiki** [comment]
Thank you for the report!

This is fixed in the master branch (see 4d37fc9bbf56eaafd1dc1800d54e567d6a5160f8).
