### ISSUE TITLE
Weird behavior of installing local packages

### ISSUE THREAD

**Issue by frostming** [lektor/lektor#1028]
Currently we install local packages into the packages root, here is the related code:

https://github.com/lektor/lektor/blob/19486da795ba5dff7a8abf39302e3ec2c6429dd0/lektor/packages.py#L104-L152

There are some problems and questions about it:

1. `--install-option=--install-dir=%s` this option does not work with PEP 660 build backends. We should use `--target` instead.
2. Why do we install with `--no-deps` at the first go and parse the requirements ourselves, why not just `pip install --editable ...`(with deps)?
3. The local package system assumes the existence of `setup.py`, which is not recommended against PEP 517/PEP518 `pyproject.toml`

**Comment by dairiki** [comment]
This is a whole kettle of fish that has to do with the original design choice to have Lektor manage its own local installations of plugins, combined with idiosyncracies and bugs (some of which may be fixed now, I'm not sure) in pip.

See #865, #877, #904.

Personally, I lean towards doing away with all this internal package management completely (or as much as possible), instead just recommend running Lektor in a separate venv for each project, with whatever plugsin are desired for that project in installed in that venv (e.g. lektor/lektor-website#327).  But, of course, there are backward-compatibility issues to be addressed with doing this.

Anyhow, it's been discussed a lot.  No perfect solution has been found, as of yet.  Perhaps the advent (and state of support) of the newer PEPs has changed things for the better — I haven't looked at this recently enough to say.

**Comment by frostming** [comment]
I am a member of PyPA and familiar with Python packaging stuff, I can investigate those issues when I get time and help solve them.

**Comment by frostming** [comment]
After a travel of the commit history, I found this piece of code has been existing since the **initial commit**, I think it is a workaround to be compatible with some *old* versions of pip. Given remote packages are installed with `--target` argument I think it is safe to change the local package installation to keep consistent now.
