### ISSUE TITLE
 E index.html (TemplateNotFound: none.html)

### ISSUE THREAD

**Issue by ghost** [lektor/lektor#103]
When I use lektor quickstart and and the end I choose `Add Basic Blog [Y/n]: n`.
Then I edit models:

```
[model]
name = Activity
label = {{ this.title }}

[fields.title]
label = Title
type = string

[fields.body]
label = Body
type = markdown
```

Delete all contents except this

```
title: Welcome to Activities!

---
body:

This is a basic demo website that shows how to use Lektor for a basic
website with some pages and a blog.
```

then I receive the following error:

```
$ lektor server
 * Project path: /home/xan/SYNC/cc-ng/lektor/cc-ng/cc-ng.lektorproject
 * Output path: /home/xan/.cache/lektor/builds/855b4aec55720a0bd0c4e30203f034d1
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
Started source info update
Finished source info update in 0.01 sec
Started build
U index.html
  E index.html (TemplateNotFound: none.html)
Error: Build failed with 1 failure.
Finished build in 0.03 sec
Started prune
Finished prune in 0.00 sec
```

You can see the files [here](https://github.com/somenxavier/lektor-test)

**Comment by Vye** [comment]
I'm having the same issue. Is there a workaround?

**Comment by mitsuhiko** [comment]
This happens if you do not have a model named `page.ini` and you did not explicitly select another model. Does this happen out of the quickstart without blog?

**Comment by Vye** [comment]
OK, this was a noob mistake. I created models/home.ini and templates/home.html thinking that if I deleted page.ini/page.html then content/contens.lr would use home automatically. https://www.getlektor.com/docs/content/#page-model-and-template clearly states how to use a custom model/template though.

Thanks for the direction. Very cool project, been using it for a few hours now.
