### ISSUE TITLE
administrator interface: page scrolling up at each keypress

### ISSUE THREAD

**Issue by andrearicci** [lektor/lektor#1038]
When I try to edit my blog in the administrator interface, and the window is highr than the viewport, and I'm editing at the bottom, each keypress makes the window immediatilly scroll to the top.
Lektor, version 3.3.4 on firefox 101.0.1 - win 10

**Comment by truenicoco** [comment]
Can confirm this happens to me too. I tried both firefox and chrome on Mac OS X. Lektor is running on a linux box though, but I am not sure it matters for admin interface stuff.

This is pretty serious since it makes the admin interface almost useless.

**Comment by dairiki** [comment]
See #1038, which describes the same or a similar problem.

PR #1045 proposes a fix.

**Comment by dairiki** [comment]
I think that hopefully🤞 this is fixed in release [3.3.6](https://github.com/lektor/lektor/releases/tag/v3.3.6).  (If not, please reopen.)
