### ISSUE TITLE
Allow assets with leading dots to be copied

### ISSUE THREAD

**Issue by mitsuhiko** [lektor/lektor#105]
There are some common files that currently cannot be created because lektor skips over files with leading dots.  In particular it ignores `.well-known`, `.nojekyll` etc.  Maybe the solution is a custom `.lektorignore` file?

**Comment by benjiao** [comment]
Hi @mitsuhiko 

I guess another possible solution would be to add something like an `[included-files]` field in the `<project>.lektorproject` file? Will look cleaner IMHO. Less clutter. :smile:

**Comment by ajdavis** [comment]
Underscore-prefixed files are also skipped, which is a problem for Netlify's `_redirects` file.
