### ISSUE TITLE
improved blog post preview on social media

### ISSUE THREAD

**Issue by drbenvincent** [lektor/lektor#1054]
Hi. At the moment when we post links to blog posts from our Lektor site, the 'preview image' or 'social media card' picks out the favicon. This seems like undesirable behaviour - ideally it would pick out the `cover.png`, or something a bit more structured for example including the title etc.

Doing a bit of research shows that 'Twitter cards' are generated when posting a link to Twitter (https://developer.twitter.com/en/docs/twitter-for-websites/cards/overview/abouts-cards), and that these rely on metadata in the generated html. It looks like this is the case for other sites, such as LinkedIn (https://theocarney.medium.com/changing-your-websites-preview-images-for-linkedin-and-other-social-media-fe6af741fd0c).

So my questions are:
- Is there there ability to do this in Lector currently?
- If not, this would be an extremely desirably feature to add.

**Comment by dairiki** [comment]
I am not an expert on this stuff either... but, the [Open Graph Protocol](https://ogp.me/) (published by Facebook) may be the most common of these sorts of things.  (It's what's used in the article you linked to about LinkedIn, and [Twitter will fall back to using Open Graph tags](https://developer.twitter.com/en/docs/twitter-for-websites/cards/guides/getting-started#twitter-cards-and-open-graph) if it doesn't find their own Twitter tags.)

On a related note, one can include [structured data](https://developers.google.com/custom-search/docs/structured_data) in the site's HTML that can influence the way Google (& Bing) will display search results pointing to the site.

All of these work by sticking special data into your HTML via meta tags or some other method.  So, fundamentally, in a Lektor site, that is the job of your Jinja templates.

To start simple, if one just wants their logo displayed with links to the site, the data that need to be stuck into the HTML is constant — it's the same on every page.  Edit the Jinja template to add the necessary tags, and you're done.

That said, Lektor can help you with these things.

One can add fields to their Lektor models (for a blog post, say) to add a field to specify the brief textual _description_ that goes into, e.g.  the [`og:description`](https://ogp.me/#optional) meta tag on the page (or maybe there's already an existing field in the blog post model that contains a brief description of the page.) One can add a field that can be used  to select which image gets linked to in the `og:image` tag.  The Jinja template can then use these fields when inserting the Open Graph tags (or "structured data", or whatever) into your rendered page.

Make sense?

**Comment by dairiki** [comment]
Closing. I think this is neither really a Lektor bug nor a well-defined feature request.  (Feel free to re-open.)
