### ISSUE TITLE
`clean` command broken in master - works in 3.3.6

### ISSUE THREAD

**Issue by nixjdm** [lektor/lektor#1056]
Normally, clean would purge the build dir, now, it seems to not do anything. Even unreferenced artifacts I place in the build dir remain. This seems caused by recent changes from [PR #203 in builder.py](https://github.com/lektor/lektor/pull/1048/files#diff-c1360c0fb130c5b6c80979a6ccc2a99bd9b95ad80af1e43af49eaebf43ccb922). @dairiki could you take a look?

[`prune(all=True)`](https://github.com/lektor/lektor/blame/master/lektor/builder.py#L1185), now returns an empty generator, instead of everything.

The test added in that PR is correct - in a `lektor build`, previously generated artifacts of sources that are now marked hidden to get pruned, but `prune(all=True)` fails.

**Comment by nixjdm** [comment]
Thanks!

**Comment by dairiki** [comment]
Yup, my fault!

This issue is that [this](https://github.com/lektor/lektor/blob/6d7bd4db43584ffa14158ccf5f4f5211a2567f14/lektor/builder.py#L412) should be a `yield from self.iter_existing_artifacts()` rather than a `return`.

Thank you for the report.
