### ISSUE TITLE
List dependency versions in GitHub Actions tests

### ISSUE THREAD

**Issue by nixjdm** [lektor/lektor#1059]
It would be nice if the automated tests clearly showed `pip freeze` so we could know precisely what has worked or not. Even if we eventually move to poetry or something with a lock file, `pip freeze` is a very condensed, simple view of what we're working with, and easily copy and paste-able for debugging.

**Comment by dairiki** [comment]
Tox does list installed package versions at the start of each run.  It's in a rather compressed, hard-to-read format, but it's there.

Screenshot of the log of one of our GitHub workflow runs:

![image](https://user-images.githubusercontent.com/495018/187795733-e502cbe7-8414-476a-9b70-e10fb39e1275.png)

**Comment by nixjdm** [comment]
Ah, I see. I missed that.

I just found the "View raw logs" button in the gear in the top-right. I'll try to remember that next time I want to ctrl-f something. The search didn't work for me.

Thanks!
