### ISSUE TITLE
wrong concatenation separator with the Jinja join filter on field of type strings

### ISSUE THREAD

**Issue by bbbart** [lektor/lektor#1060]
When applying the Jinja `join` filter in a template on a field of type `strings`, the concatenation separator seems to be always ", ". So, for example,

```
{{ this.tags|join(' | ') }}
{{ this.tags|join }}
{{ '<br>'.join(this.tags) }}
```

all result in the exact same output `tag1, tag2, tag3`.

I understand this could have nothing to do with Lektor. If so, I'll redirect the issue towards the Jinja team.

Versions:
 - Lektor 3.3.6
 - Jinja2 3.1.2

**Comment by dairiki** [comment]
I suspect what is going on is that the value of `this.tags` in your case is not an iterable (e.g. a list or a tuple), but, rather, the string `"tag1, tag2, tag3"` (or some other non-iterable that stringifies to that value).
(What is the field type of your `tags` field?  Try `{{ this.tags|pprint }}` and see what you get.)

Your third example (`'<br>'.join(this.tags)`) doesn't even involve a Jinja filter.  That's invoking python’s `str.join` directly.

In any case, I am unable to reproduce this.   (In my experiments, the default joiner for the Jinja `join` filter is the empty string, not `", "`.)

**Comment by bbbart** [comment]
Aha! Yes, that would make a lot of sense...

However, `pprint` shows the value for `this.tags` as `['tag1', 'tag2', 'tag3']`.

The type in the model for the tag field is `strings`. I use the same type for other fields and can successfully iterate over them as expected.

Oh... wait... while typing this comment, I played around some more... and now it simply works. I reckon, but I can't recall with certainty, that the `tags` field must have had some other type before and the existing content was stored as a single, comma separated string, as your analysis suggested.

Okay, move on, nothing to see here.

I'm very grateful for the quick and thoughtful reply you gave. Thank you!
