### ISSUE TITLE
Can a model have multiple children models?

### ISSUE THREAD

**Issue by miratcan** [lektor/lektor#1078]
Hi, I am the founder of internetguzeldir.com It's a web directory. In every category, there are subcategories and links. This means I need a model that has subcategories as children also links. Is that possible with lektor?

**Comment by nixjdm** [comment]
I'm not sure I completely understand your use case and how it's _best_ implemented, but yes, you can have a model that has multiple child models. There's no limit on the number of models that inherit the same model parent. See https://www.getlektor.com/docs/models/#model-options `inherits` for how to make a model inherit another.

You may also be interested in https://www.getlektor.com/docs/guides/categories/ and https://www.getlektor.com/plugins/lektor-tags/

**Comment by miratcan** [comment]
For example check this page: 

https://internetguzeldir.com/bilgisayarlar/yazilim-gelistirme/index.html

This page is about software development and has two kinds of children. One is subcategories, the other is links. 

<img width="935" alt="Ekran Resmi 2022-10-06 11 30 36" src="https://user-images.githubusercontent.com/140968/194263111-f2289acd-93bc-48aa-b49c-4f5bfc8533b1.png">

So I need two models that can be children of a category page. Am I clear now?

**Comment by nixjdm** [comment]
You can do this all manually by creating models for parents and children, and not necessarily need or want inheritance. The categories guide is along these lines. I get the sense though that you would like to create both these categories and links more easily, because it looks like you have more than a few. This seems better suited to [lektor-tags](https://github.com/lektor/lektor-tags). Plugin categories require making new contents.lr in your code, but tags are merely a line in an existing contents.lr.

It may help to compare how plugin categories and tags are both implemented on getlektor.com. See this [plugin's contents.lr](https://github.com/lektor/lektor-website/blame/master/content/plugins/lektor-s3/contents.lr#L5-L13). Those tags' pages are generated, but the categories need a [real contents.lr](https://github.com/lektor/lektor-website/tree/master/content/plugin-categories/deploy) making them a bit more cumbersome. Thus, getlektor.com only has a few categories, but [many tags](https://www.getlektor.com/plugins/tags/).

**Comment by dairiki** [comment]
Aha!  I understand now. (I think.)

At present, it is not possible to constrain the types of children a particular model can have (via the `[children] model` setting in the model's `.ini` file) to a specific set of size larger than one.  

You can leave the types of the model's children unconstrained (i.e. leave `[children] model` unset).  In that case, when you create a new subpage using the admin UI, you'll be offered a choice of all defined models which aren't explicitly marked "hidden" for the new page.  In your case, that's what I would suggest.

**Comment by nixjdm** [comment]
Ah, I interpreted the problem differently.

> At present, it is not possible to constrain the types of children a particular model can have (via the [children] model setting in the model's .ini file) to a specific set of size larger than one.

@dairiki you're correct. See #166

**Comment by nixjdm** [comment]
Another option is to have only one child model, and bake in all the features you need in that one model, and create a template for those children that's sufficiently complex to handle the need. It's hard to say from here how complicated that model and template would need to be, so I'm not sure if this is a palatable solution.

**Comment by dairiki** [comment]
If my understanding of the structure of internetguzeldir.com is correct (I don't read Turkish, so it's quite possible it's not :smile:) there are only two page types on the whole site: categories and links.  The main distinction between the two is that categories have children (of both model types), while links do not; and links have a URL field.

If that is the case, Lektor models roughly as follows would make sense:

`models/category.ini`:
```ini
[model]
name = Category
label = {{ this.title }}

# children of any non-hidden model are allowed by default

[fields.title]
label = Title
type = string

[fields.description]
label = Description
type = markdown
```

`models/link.ini`:
```ini
[model]
name = Link
label = {{ this.title }}

[children]
# Links don't have sub-pages
enabled = no

[fields.title]
label = Title
type = string

[fields.description]
label = Description
type = markdown

[fields.url]
label = URL
type = url
```

----

If you have a lot of shared structure between the two types, they could both inherit from a hidden base model.

`models/base.ini`:
```ini
[model]
hidden = yes
label = {{ this.title }}

[fields.title]
label = Title
type = string

[fields.description]
label = Description
type = markdown
```

`models/category.ini`:
```ini
[model]
name = Category
inherits = base
hidden = no

# ... other fields specific to category
```

`models/link.ini`:
```ini
[model]
name = Link
inherits = base
hidden = no

[children]
# Links don't have sub-pages
enabled = no

[fields.url]
label = URL
type = url
```

----

If categories do not have any fields that links do not also have, then the link model could inherit from the category model:

`models/page.ini` (`page` is the default model type):
```ini
[model]
name = Category
label = {{ this.title }}

# children of any non-hidden model are allowed by default

[fields.title]
label = Title
type = string

[fields.description]
label = Description
type = markdown
```

`models/link.ini`:
```ini
[model]
name = Link
inherits = page

[children]
# Links don't have sub-pages
enabled = no

[fields.url]
label = URL
type = url
```

**Comment by miratcan** [comment]
@dairiki Thank you for efford, you are very kind. I will try this when I go to front of the computer

**Comment by dairiki** [comment]
Closing, as this is not a bug report or feature request, and the question seems to have been answered.
