### ISSUE TITLE
New Plugin for more convenient template debugging

### ISSUE THREAD

**Issue by nixjdm** [lektor/lektor#1083]
I often find figuring out the jinja I need in templates tedious, and I know others do too. There are tricks to fairly quickly suss out what data is available in a context and how to call it, but I think it can be more convenient than it is currently.

The couple tricks I've used and recommended to others are:

- `{% debug %}`, made available with `LEKTOR_DEV=1`
- `{{ this._data }}`
- `{{ this.__dir__() }}`
- `{% for blk in this.<flow field>.blocks %}{{ blk._data }}{% endfor %}`

and similar things.

Of course, you could figure out this information in other ways, but for me, it's sometimes quicker like this. It still feels cumbersome though, especially with flow blocks involved.

My proposition is to provide a better template variable when `LEKTOR_DEV=1` that really gives you most of what you might need all at once, and with some nice basic html formatting for easy viewing and navigation, which none of the above have. It could all be provided in an expandable section

<details><summary>like this (click me)</summary>~ debug content ~</details>

And a link could be given too, that goes to a separately rendered json page showing all of the same data. That could be very convenient and easy to read, since browsers like Firefox offer several nice viewing options for json. I'm not sure what to name the var that's injected. `debug` would seem obvious, but we'd already have that as a tag, which would be confusing.

I'm pretty sure I'm going to just go and make this. At minimum I think it'll help out some people I work with. I might even be able to prioritize it since it might help coworkers. Does anyone have any other suggestions for how this plugin might act? Any other related quality of life improvements I can add?

**Comment by relikd** [comment]
In addition, I'd like to add some basic python debugging functions for plugin development:

```py
self.env.jinja_env.globals['str'] = str
self.env.jinja_env.globals['dir'] = dir
self.env.jinja_env.globals['type'] = type
```

**Comment by nixjdm** [comment]
This is done https://github.com/terminal-labs/lektor-debug

After exposing all of this debug info under a `<details>` element, and in a markdown codeblock, it looks pretty good just on it's own. I don't think the extra json files are necessary right now. Everything else in this post is built though. Check it out!
