### ISSUE TITLE
How to access the alternative of a Field Type

### ISSUE THREAD

**Issue by relikd** [lektor/lektor#1088]
I have a custom field type to parse an ingredient line of a recipe.
For example: "2 cups chocolate" or "1 banana" or "1 can Marzano tomatoes, chopped".
As you can see, the format is quite variable so I cannot simply split the string by some delimiter.
Instead I have a list of pre-defined measurement units ('cups', 'can') that I check to split the components.

But now comes the tricky part, my site is multi-lingual and I have a different list of measurements for each alternative.
However, when lektor initializes my custom field (`value_from_raw`) I have no way to get the alternative of the calling record.

Is there a way to get the alternative of a Field Type?

**Comment by dairiki** [comment]
I'm not sure I totally understand the issue, but:

Each Lektor db record corresponds to a specific alt and contains only a single value for each field.
Remember that records are identified by the pair (`path`, `alt`) — there is (at least, conceptually if not actually) a separate record for each alt.  When you access a field value from a record you get the value for alt = `record.alt`.

If you want the value for a different alt than the record you have, you need to access the field on the record for that alt.
E.g. if you want specifically the German value for a field, something like:
```py
record_de = record.pad.get(record.path, alt="de")
value_de = record_de["fieldname"]
```

**Comment by relikd** [comment]
Yeah, it seems I did a terrible job explaining 😄
I dont want to access the field of a record but construct a custom `lektor.types.Type`.

```py
class IngredientsListType(Type):
    widget = 'multiline-text'

    def value_from_raw(self, raw: 'RawValue') -> IngredientsList:
        print(raw.field)  # I want to get the alt of the record
        exit(0)
[...]
self.env.add_type(IngredientsListType)
```

**Comment by dairiki** [comment]
Ah.  If you want access to the record (so that you can access `record.alt`), you'll need to resort to returning a "descriptor" from your `value_from_raw` (and defer further processing of the value until that descriptor's `__get__` is called.)

See Lektor's [MarkdownType](https://github.com/lektor/lektor/blob/master/lektor/types/formats.py) for an example of how that's done.

The issue (IIRC) is that `value_from_raw` gets called early in the process of reading the `.lr` file data, before the `Record` is actually constructed.  So at the time `value_from_raw` is called, there is no `record`...

**Comment by relikd** [comment]
Perfect, that worked nice 👍. Just one more question: when is the optional field `type=None` used? (or is it even used? I am considering what cases I have to handle in my code)

https://github.com/lektor/lektor/blob/fcf31cb620989715fd0773a8d50abf8ee554f546/lektor/types/formats.py#L12-L15

**Comment by dairiki** [comment]
I don't think it's used anywhere.

The API is evidently copied from Python's [attribute descriptor API](https://docs.python.org/3/reference/datamodel.html#implementing-descriptors).  Maybe, originally, the idea was to use the `property` decorator to define field descriptors?  I don't know.
