### ISSUE TITLE
`record_dependency` during `environment.Expression.evaluate()`

### ISSUE THREAD

**Issue by relikd** [lektor/lektor#1090]
Hi there, I am probably just missing something but is there a way to know which files were accessed during an `Expression` evaluation?

For example, if I have the following Expression `site.get('/pageB').name` on page A, I'd like to keep track of page B as a dependency of page A. I quickly searched the source code but can't seem to find a way that either lists all accessed fiels during the evaluation, or create a context that lists all accesses.

**Comment by relikd** [comment]
Ahh, partly solved. I found https://www.getlektor.com/docs/api/build/context/gather-dependencies/

Only one thing left, how do I get the same result if there is no context available?

**Comment by dairiki** [comment]
I think all of Lektor's dependency recording happens through calls to [`Context.record_dependency`](https://github.com/lektor/lektor/blob/fcf31cb620989715fd0773a8d50abf8ee554f546/lektor/context.py#L230) or [`Context.record_virtual_dependency`](https://github.com/lektor/lektor/blob/fcf31cb620989715fd0773a8d50abf8ee554f546/lektor/context.py#L242).  As such, a context has to be active for those dependency tracking hooks to be called.

Normally a context is created for each artifact build.  When the build of the artifact is completed, all of the source files and virtual source objects that the artifact depends on, along with the timestamps and hashes of those files and virtual source objects, are recorded in the build database.  That data is then used to determine when an artifact needs to be rebuilt, and when to remove stale artifacts.

I think you could compute a list of dependencies outside of the artifact build process by pushing your own context.  (I don't quite understand why you'd want to do that.)  (Untested code follows:)
```py
from lektor.context import Context
from lektor.environment import Expression

deps = set()
with Context(pad=pad) as ctx:
    with ctx.gather_dependencies(deps.add):
        # Whatever evaluation you want to track referenced dependencies for.  E.g.:
        Expression(env, "site.get('/pageB').name").evaluate(pad)
```

**Comment by relikd** [comment]
That works perfectly :) thank you!
I have to work over my code anyway but now, at least, I have a fallback if nothing else helps.
