### ISSUE TITLE
Inconsistent relative build paths for CLI params --output-path and --buildstate-path

### ISSUE THREAD

**Issue by relikd** [lektor/lektor#1103]
If you provide a relative path to the lektor build command, the paths are relative to different folders.

Consider this folder structure:

> CWD
> CWD/projdir
> CWD/projdir/main.lektorproject

running this command:

```sh
lektor build --project projdir --output-path opath --buildstate-path bspath
```

Creates these two folder:

> CWD/projdir/opath/
> CWD/bspath/

I find it a bit confusing that output-path is relative to the project file whereas buildstate is relative to the current working directory.

**Comment by dairiki** [comment]
Having thought more about this, I'm willing to call this a bug.

In general, it seems unexpected and surprising for any path specified on the command line to be interpreted relative to anything but the current working directory.

Do note that it is also possible to set the `output_path` in the *project file*. In that case, I would expect that the path would be interpreted relative to the location of the project file (as is [documented](https://www.getlektor.com/docs/project/file/#project)).

So we should support both:
- relative paths specified on the command line (or via environment variables) should be interpreted relative to the current working directory
- relative paths specified in the project file should be interpreted relative to the location to the project file

To add one more ball to juggle: also note that the location of the *project tree* — the directory that contains the `content`, `templates`, `models` and other directories comprising the source of the project — isn't necessarily the same as the location of the *project file*.  (The location of the tree can be set by the `path` setting in the project file.)

**Comment by dairiki** [comment]
**Another buglet**: It appears that relative `output_path` paths specified in the project file are currently interpreted relative to the *project tree* (see [here](https://github.com/lektor/lektor/blob/6d1bb16e2790e130edb8b5f5761f8ad118c14236/lektor/project.py#L114)). As previously noted the [documentation](https://www.getlektor.com/docs/project/file/#project) says it should be interpreted relative to the location of the *project file* — and I think that makes more sense.
(The *project tree* is usually but not necessarily the same as the location of the *project file*.)
