### ISSUE TITLE
get_prev_sibling and get_next_sibling cause all pages to depend on each other

### ISSUE THREAD

**Issue by ajdavis** [lektor/lektor#114]
Say I have sibling blog posts: post1, post2, and post3. The blog post template uses `get_prev_sibling` and `get_next_sibling` to render navigation links. This causes post1's artifact to depend on post2, and post2's artifact to depend on post3, which is correct.

The bug is: post1's artifact **also** depends on post3. This is because any call to `get_prev_sibling` and `get_next_sibling` records a dependency on all items in `self.parent.children` or `self.parent.pagination.items`.

In a setup like this, all posts depend on all others. This is unfortunate because this setup is the intended use-case for `get_prev_sibling` and `get_next_sibling`, but any change to any post causes nearly the whole site to rebuild. If I fix a typo on one post on my site, it rebuilds 500+ pages instead of one.

Demonstrated in `test_category_dependencies` in [test_dependencies.py on my branch](https://github.com/ajdavis/lektor/blob/dependency-test/tests/test_dependencies.py).

I don't know how to fix this, I could use your advice.

**Comment by ajdavis** [comment]
There's a way to make each post only record a dependency on its next and previous sibling, instead of depending on all the other posts:

``` python
@cached_property
def _siblings(self):
    ctx = get_ctx()
    with Context(ctx.artifact, ctx.env):
        parent = self.parent
        pagination_enabled = parent.datamodel.pagination_config.enabled
        if pagination_enabled:
            pagination = parent.pagination
            siblings = list(pagination.config.get_pagination_query(parent))
        else:
            siblings = list(parent.children)

        prev_item, next_item = None, None
        try:
            me = siblings.index(self)
        except ValueError:
            # Self not in parents.children or not in parents.pagination.
            pass
        else:
            if me > 0:
                prev_item = siblings[me - 1]
                ctx.pad.db.track_record_dependency(prev_item)

            if me + 1 < len(siblings):
                next_item = siblings[me + 1]
                ctx.pad.db.track_record_dependency(next_item)

        return prev_item, next_item
```

The problem with this is, if I add a _new_ post to the list and build the site, the new post's siblings should be rebuilt but they are not.

**Comment by ajdavis** [comment]
I have a proposal: the previous and next siblings should become virtual sources. This will be nice because the template syntax will become nicer:

```
<a href="{{ '@next'|url }}">next</a>
```

(I think that will work?)

post3 now depends on the "post3@prev" and "post3@next" virtual sources. When I add "post4", that becomes the new "post3@next" and somehow updates the modification time of the "post3@next" virtual source, causing post3's artifact to be rebuilt.

Does this sound feasible? I don't know if virtual sources have modification times, or where they're tracked.

**Comment by mitsuhiko** [comment]
You can't just record the dependency to prev and next because next and prev can change. However the reason everything rebuilds for a tiny change currently is because we depend on the entire checksum of the source. It would be much preferred if each field change is checksummed individually. That way you would only rebuild if something significant changed. Eg: the title of the post changed if the other template does `{{ prev.title }}` or something of that sort.

I did not look into it yet, but that's what I generally have in mind to make the dependency tracking better.

**Comment by ajdavis** [comment]
Thanks. Yes, I've been thinking about that too.

Meanwhile I'm _also_ working on a proposal for virtual sources to be listed as dependencies, which implement "unchanged" like FileInfos do. I'll show you when it's ready. It's ok if you reject it in favor of a different solution. =)
