### ISSUE TITLE
Security Issue Report: Stored XSS in [Lektor] (https://github.com/lektor/lektor/)

### ISSUE THREAD

**Issue by djvirus9** [lektor/lektor#1197]
### Issue Summary

A **Stored Cross-Site Scripting (XSS)** vulnerability has been identified in the `/pathinfo` endpoint of the project. This vulnerability allows an attacker to inject malicious JavaScript code that will be **stored and executed** when accessed by other users. This issue was discovered by **[Danish Siddiqui](https://www.linkedin.com/in/danish-siddiqui-bb0793197/)** and **[Amar Shindhe](https://www.linkedin.com/in/amarshindhe/)**, working together in **[Your Organization Name]**.

We are raising this issue in compliance with **responsible disclosure guidelines** to notify the maintainer and **request a CVE assignment**.

---

### Detailed Report

Please find the attached detailed report here:  
[Google Document Link](https://docs.google.com/document/d/12TwXfII5za0fDtHVpcjh_dzmP9cOxJcVFhoFqs4meqc/edit?usp=sharing)

---

### Credits

This issue was discovered and reported by:  
- **[Danish Siddiqui](https://www.linkedin.com/in/danish-siddiqui-bb0793197/)**  
- **[Amar Shindhe](https://www.linkedin.com/in/amarshindhe/)**  

---

Let us know if further information or testing assistance is required. We are happy to collaborate to resolve this issue promptly. Thank you for your attention to this matter!

**Comment by dairiki** [comment]
Lektor is a static website generator.  It includes a web-based admin GUI that is intended to be run on, e.g.  `http://localhost:5000/` for local use.  The admin GUI is not intended to be made available to untrusted parties.

A primary purpose of the admin GUI is to allow for editing HTML or markdown source to be included in the generated static site output. As such it is designed to allow the site author to enter arbitrary HTML.

This report seems to be describing nothing more than that — the ability of a site author to include arbitrary HTML in the text of their site.  It seems over-reactive to call this a vulnerability.

**Comment by yagebu** [comment]
Thanks @dairiki, I agree and don't see this as even remotely being a vulnerability, I'll close it.
