### ISSUE TITLE
Pillow 11.0 breaks a test

### ISSUE THREAD

**Issue by dairiki** [lektor/lektor#1200]
The test [`tests/imagetools/test_thumbnail.py::test_create_artifact_strips_metadata`][src] fails under Pillow==11.0.0 (but not 10.4.0) due to the appearance of an `xmp` key in the thumbnail's `image.info` dict.

At this point, more investigation is required to determine whether this represents a real possibility of leakage of image metadata from the original to the thumbnail or whether this is a false alarm.

[src]: https://github.com/lektor/lektor/blob/3d34de1f279205f9be36d1c8928a5adeba849f2f/tests/imagetools/test_thumbnail.py#L239

**Comment by webknjaz** [comment]
I was just about to post the same discovery :)

**Comment by webknjaz** [comment]
@dairiki I think it'd be useful to get a quick-and-dirty workaround into `master` until it's addressed: https://github.com/lektor/lektor/pull/1201.

**Comment by dairiki** [comment]
A new feature in Pillow 11 is support for writing packed XMP data to image files.
See https://pillow.readthedocs.io/en/stable/releasenotes/11.0.0.html#writing-xmp-bytes-to-jpeg-and-mpo

Apparently, when [scaling images](https://github.com/lektor/lektor/blob/3d34de1f279205f9be36d1c8928a5adeba849f2f/lektor/imagetools/thumbnail.py#L372), any XMP data in the original image is propagated to the scale image.  We should be stripping the XMP data from thumbnails, I think.
