### ISSUE TITLE
Tiny MCE is not working

### ISSUE THREAD

**Issue by etoimene** [lektor/lektor#1211]
I installed added tinymce.ini and 
[packages]
lektor-tinymce = 0.6

as described at https://pypi.org/project/lektor-tinymce/

but I don't see editor working.

Where should I look for logs?

Link above says "Currently it is compatible with Lektor 3.3.6"
and I am using higher, latest lektor version.

**Comment by dairiki** [comment]
Lektor-tinymce is a third-party plugin, and so is not supported by the Lektor project.

The official repo for the lektor-tinymce project appears to be https://github.com/sphericalpm/lektor-tinymce.
You might try filing an issue there.

**Comment by etoimene** [comment]
Thank you. Somehow, I was not able to find it.

**Comment by dairiki** [comment]
> Thank you. Somehow, I was not able to find it.

It was not particularly easy to find, as it's not linked in the project metadata.  I found it after some searching on GitHub. 

The project's releases match the PyPI releases, and the organization that owns the project matches the email of the author listed in the project's metadata, so I'm pretty sure that's the right place.
