### ISSUE TITLE
Lack of Proxy Support for Install Script

### ISSUE THREAD

**Issue by daks** [lektor/lektor#122]
Hello,

I want to try Lektor. I read the documentation which discourage the use of virtualenv/pip and encourage to use the curl/pipe option.
It starts well the installation, asking me the first question but then it crashes with this error 'ValueError: No JSON object could be decoded'

This is a complete output of the program

```
eric@/tmp$ curl -sf https://www.getlektor.com/install.sh|sh

Welcome to Lektor

This script will install Lektor on your computer.

Installing at:
  bin: /home/eric/bin
  app: /home/eric/.local/lib/lektor

Continue? [Yn] 
Traceback (most recent call last):
  File "<stdin>", line 126, in <module>
  File "<stdin>", line 114, in main
  File "/usr/lib/python2.7/json/__init__.py", line 290, in load
    **kw)
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

I can provide more information if needed.

**Comment by mitsuhiko** [comment]
Are you using a proxy server on your computer?

**Comment by daks** [comment]
Access to internet is done using a HTTP proxy (which is not on my computer). http_proxy and https_proxy environment variables are set in my shell. (I'm running Debian stable)

**Comment by mitsuhiko** [comment]
Yeah, this is currently not supported by the script installer.

**Comment by xlotlu** [comment]
This should be fixed by https://github.com/lektor/lektor-website/pull/298, which uses standard `urllib`, which in turn honours `http_proxy`.
