### ISSUE TITLE
SyntaxError: invalid token

### ISSUE THREAD

**Issue by ChillarAnand** [lektor/lektor#140]
I have installed lektor using pip and when i run `quickstart`, it is throwing error.

```
$ lektor quickstart
Traceback (most recent call last):
  File "/home/anand/.virtualenvs/3/bin/lektor", line 7, in <module>
    from lektor.cli import main
  File "/home/anand/.virtualenvs/3/lib/python3.4/site-packages/lektor/cli.py", line 9, in <module>
    from .utils import secure_url
  File "/home/anand/.virtualenvs/3/lib/python3.4/site-packages/lektor/utils.py", line 394
    os.chmod(tmp_filename, 0644)
                              ^
SyntaxError: invalid token
```

**Comment by buckket** [comment]
Python 3 is not supported.

**Comment by ChillarAnand** [comment]
Is anyone working on  it?

**Comment by mitsuhiko** [comment]
As mentioned, Python 3 is not supported and that's pointed out in the docs. If someone is willing to commit to support Python 3 then I'm all for accepting patches for this.

**Comment by mitsuhiko** [comment]
JFTR. Currently nobody actually stepped up to support it.

**Comment by ChillarAnand** [comment]
I will provide a patch in a few days.

**Comment by ChillarAnand** [comment]
While porting, a test is failing at https://github.com/lektor/lektor/blob/master/tests/test_types.py#L39

``` py
            for val in b'', None:
                rv = field.deserialize_value(val, pad=pad)
                assert isinstance(rv, MarkdownDescriptor)
                rv = rv.__get__(source)
>               assert not rv
E               assert not <lektor.markdown.Markdown object at 0x7fd616e6d0f0>

```

``` py
ipdb> assert not rv
*** AssertionError: <could not determine information>
```

Any idea why its happening?

**Comment by arishuynhvan** [comment]
Hi, for the original bug, it can be fixed by changing to the convention of Octal in Python 3 (0644 -> 0o644)
Actually, I'm interested in porting the code to from Python 2 to Python 3. @mitsuhiko Will it be a useful contribution to the project?

Edit: Really sorry, I didn't see @ChillarAnand 's latest pull request. I will continue to comment over there
