### ISSUE TITLE
support brew install

### ISSUE THREAD

**Issue by item4** [lektor/lektor#141]
For Mac OS X user, brew can make installing simple and easy.

**Comment by Fil** [comment]
well since 4 Feb it exists — I've just used it, works like a charm
`brew cask install lektor`
https://github.com/caskroom/homebrew-cask/blob/master/Casks/lektor.rb

**Comment by singingwolfboy** [comment]
Can this issue be closed, then?

**Comment by Fil** [comment]
I'd say yes
