### ISSUE TITLE
Support Python 3

### ISSUE THREAD

**Issue by item4** [lektor/lektor#142]
[@mitsuhiko want someone's PR](https://gitter.im/lektor/lektor?at=56aee398586242210ae0b531)
## Issue
- ~~Can we use [six](https://pythonhosted.org/six/) for keep same operation?~~
- Can we use [tox](https://tox.readthedocs.org/en/latest/) for testing?
- Can we use [coveralls](https://coveralls.io/) for checking coverage?
- Can lektor's dependencies support py3?

**Comment by item4** [comment]
- [Jinja2>=2.4](http://jinja.pocoo.org/docs/dev/intro/#experimental-python-3-support) (O)
- [click>=6.0](http://click.pocoo.org/5/python3/) (O)
- [watchdog](https://pypi.python.org/pypi/watchdog) (O)
- [mistune](https://pypi.python.org/pypi/mistune/0.7.1) (O)
- [Flask](http://flask.pocoo.org/docs/0.10/python3/) (O)
- [EXIFRead](https://pypi.python.org/pypi/ExifRead/2.1.2) (O)
- [inifile](https://pypi.python.org/pypi/inifile/0.3) (???)
- [Babel](https://pypi.python.org/pypi/Babel) (O)
- setuptools (O)
- pip (O)
- [requests[security]](http://docs.python-requests.org/en/latest/) (O)

@mitsuhiko May I know inifile support py3? It's your library. but have any docs.

**Comment by mitsuhiko** [comment]
inifile supports Python 3.

Instead of using `six` please write a custom `_compat` module like in other libraries. Six pulls in a shitty hack on import hooks and that causes major pain on distribution.

**Comment by techdragon** [comment]
@mitsuhiko I assume the futures/futurize path is also a no go for supporting Python 3?.

**Comment by mitsuhiko** [comment]
@techdragon i'm fine with anything for as long as the code stays as clean as possible and nothing in python 2 degrades and does not pull in dependencies for achieving this feat.
