### ISSUE TITLE
sqlite database is slow

### ISSUE THREAD

**Issue by textshell** [lektor/lektor#144]
sqlite's consistency and durability implementation slows lektor down quite a bit on systems without SSDs (i did not try with SSD)

Tests are done with buildstate and output diretory's contents deleted.
With a test site running lektor via `time (lektor clean --yes ; lektor build)` takes 32 seconds

Time spend on sqlite's fsync can be approximated by changing Builder.connect_to_database to disable fsync (`PRAGMA synchronous=OFF;`). Run time then decreases to 1.2 seconds.

Of course disabling all fsync usage does leave the buildstate in a risk of corruption if the system crashes, which might not be acceptable. I think that switching to write ahead logging allows similar performance gains. Setting `PRAGMA journal_mode=WAL; PRAGMA synchronous=NORMAL;` still is robust against database corruption, but can loose already commited transactions when the system crashes. As far as i understand loosing transaction would be safe as lektor would just rebuild some files again on next build.

Just added these pragmas to Builder.connect_to_database doesn't work as intended as sqlite integrates the wal back into the database file on close of the last active connection to a database thus slowing lektor down even more (42 seconds in my measurements). Connections caching could avoid that problem of course. But for quick testing i just "leaked" a connection in Builder.**init** and got a runtime of 3 seconds. (`self.leak = self.connect_to_database(); self.leak.cursor().cur.execute("BEGIN TRANSACTION;")`)

I think that's to dirty to actually suggest. So my suggestion at the moment is to try connection caching. Would a pull request with connection caching have a chance? Or do you would like to explore other approches?

**Comment by mitsuhiko** [comment]
Which system does that happen on? I tried on an HDD system and it did not slow it down tremendously so I assume this is dependent on the OS?

**Comment by textshell** [comment]
I'm sure fsync performance varies. This is on linux (4.4.1) using an ext3 filesystem in a logical volume on raid1 with 2 disks.
I just tested again to make sure it's reproducible plain git master and without custom plugins. I noticed this while working on my pagination so it's with a fair amount of dummy test pages (approximately 70).
Maybe it's relevant that this setup generates a moderately sized sqlite database of 544 kilobytes.
I just made a copy of the project and removed most except the test posts and templates and it's still reproducible. If you like i can share that project with you also...
I'm currently also on the lektor irc, so if you like you we can also discuss there.

**Comment by mitsuhiko** [comment]
I guess I'm fine with `synchronous=OFF` if we can detect a certain bad environment. But not sure how we would do that.

**Comment by textshell** [comment]
I'm not sure there is a good way to detect fsync performance. So i was going for something that doesn't depend on detection. So the three possible solutions i can come up with is 
- always using synchronous=off
- wal+sync=normal with connection caching (no need to get fancy as long as one connection is open all the time)
- wal+sync=normal with a connection that is just around to delay sqlite's removal of the wal log.

**Comment by mitsuhiko** [comment]
> wal+sync=normal with connection caching

This one is tricky because of concurrency.

**Comment by textshell** [comment]
I don't really understand how lektor is using threads. I'm not even completely sure about the lifecycle of Builder. But adding connection caching just for this sounds like an unneeded complication if the Builder is accessed from multiple threads.
I'm not sure how to do this so the dev server also benefits, but i just tried keeping one connection open in Builder.build_all. That works ok too.

```
diff --git a/lektor/builder.py b/lektor/builder.py
index 8f6ca2a..a3552f0 100644
--- a/lektor/builder.py
+++ b/lektor/builder.py
@@ -976,8 +976,13 @@ class Builder(object):
         return os.path.join(self.meta_path, 'buildstate')

     def connect_to_database(self):
-        return sqlite3.connect(self.buildstate_database_filename,
+        con = sqlite3.connect(self.buildstate_database_filename,
                                timeout=10, check_same_thread=False)
+        cur = con.cursor()
+        cur.execute("PRAGMA journal_mode=WAL;");
+        cur.execute("PRAGMA synchronous=NORMAL;");
+        con.commit()
+        return con

     def touch_site_config(self):
         """Touches the site config which typically will trigger a rebuild."""
@@ -1088,6 +1093,7 @@ class Builder(object):
         """Builds the entire tree.  Returns the number of failures."""
         failures = 0
         path_cache = PathCache(self.env)
+        con = self.connect_to_database()
         with reporter.build('build', self):
             self.env.plugin_controller.emit('before-build-all', builder=self)
             to_build = self.get_initial_build_queue()
@@ -1099,6 +1105,7 @@ class Builder(object):
             self.env.plugin_controller.emit('after-build-all', builder=self)
             if failures:
                 reporter.report_build_all_failure(failures)
+        con.close()
         return failures

     def update_all_source_infos(self):

```

**Comment by mitsuhiko** [comment]
In particular parallel builds happen currently when you use the dev server with the builder in the background. But in the future hopefully we can build from multiple threads in general.
