### ISSUE TITLE
Filtering on attachements to manage display between 2 images

### ISSUE THREAD

**Issue by nsteinmetz** [lektor/lektor#146]
Hi,

For a given page, I would like to have two images:
- One for the thumbnail view in the parent folder
- One for the page view

I tried to play with `.first()` but it does not always give me the same result ; so is there a way to do something like `.filter(F.title.contains('small'))` ? I tried to add a metadata file for images but seems it does not work this way.

Filtering on filename would be enough for me.

Thanks,
Nicolas

**Comment by mitsuhiko** [comment]
Please send support requests to stackoverflow.

**Comment by davidbenque** [comment]
Hi @nsteinmetz did you ever resolve this? I'm having a similar issue with `.first()` giving weird results.
