### ISSUE TITLE
loading interface ... on current master

### ISSUE THREAD

**Issue by oz123** [lektor/lektor#148]
I could not access the admin UI on the current master. 
My browser hangs at:

```
loading interface ...
```

This works fine with 1.2.1.

Another issue with the current master I have, is that CTRL+C does not work (also works fine with 1.2.1)

**Comment by niijv** [comment]
Did you build the JS again after switchting to master? 
What does it say in console of the browser developer tools?

**Comment by oz123** [comment]
@niijv , well I didn't update the JS.

The issue with control+c is console (trying to stop the server)

**Comment by niijv** [comment]
Ok, so the Admin UI works now?

About the console, do you get any specific error messages when trying to exit or is there no effect at all?

**Comment by mitsuhiko** [comment]
This happens if you do not run `make build-js`.
