### ISSUE TITLE
Can not load Admin interface

### ISSUE THREAD

**Issue by amvtek** [lektor/lektor#150]
I am running lektor server on Ubuntu 14.04 with ext4 filesystem
lektor --version reads 1.2.1

When trying to edit a page, I got a "Loading Interface..." message, then nothing happens.
I get same behavior after reloading the page & switching from Firefox to Chrome.
We also tried to clear the cache

It once worked...
Same project sources can be edited when working on MAC OS
Unsure of the exact sequence of events that are related to this problem, but
- lektor was reinstalled
- we cleared the cache prior to attend stagging deployment using rsync method

**Comment by mitsuhiko** [comment]
Can you open the javascript console in the browser and copy paste the error message?

**Comment by amvtek** [comment]
edit:3   GET http://localhost:5000/admin/static/gen/styles.css 
edit:20 GET http://localhost:5000/admin/static/gen/vendor.js 
edit:22 GET http://localhost:5000/admin/static/gen/app.js

When using chrome web console

**Comment by mitsuhiko** [comment]
That does not look like errors. Are they shown in red? If yes it sounds like the generated javascript files are not available. How did you install it?

**Comment by mitsuhiko** [comment]
I can see this happen if you installed the git version and you did not build the sources with `make build-js` but these files should be available if installed from pypi.

**Comment by amvtek** [comment]
The links are shown in red.
I will reinstall from PyPI & let you know

**Comment by mitsuhiko** [comment]
Please open a new issue if it persists.  I cannot reproduce this myself.

**Comment by amvtek** [comment]
You are right, reinstalling from PyPI solved the issue & yes previous version was retrieved from github.
Sorry for not having found this myself.
