### ISSUE TITLE
url function generates duplicated slug

### ISSUE THREAD

**Issue by steckerhalter** [lektor/lektor#159]
If I'm using this to generate an url:

``` html
<a href="{{ '.'|url(alt='de') }}">{{ alternative.locale }}</a>
```

German is an alternative (not primary) and the contents+de.lr in question has a translated `_slug: versuch`. The resulting url then looks like: `http://localhost:5000/de/versuch/versuch/` instead of `http://localhost:5000/de/versuch/`

This doesn't happen when the slug is not specified (translated) in contents+de.lr

**Comment by mitsuhiko** [comment]
Does this happen in Lektor 2 as well?

**Comment by steckerhalter** [comment]
I have justed checked with v2 and it's working allright there...

**Comment by steckerhalter** [comment]
while the issue with the duplicated slug seems to be fixed in v2, now the prefix on the index page is always just the primary language. I'll investigate this tomorrow again.

**Comment by mitsuhiko** [comment]
Can you open a separate issue for this if you can confirm that's the problem?
