### ISSUE TITLE
Dev server cannot serve pagination for pages > 1

### ISSUE THREAD

**Issue by item4** [lektor/lektor#16]
- used command

```
$ lektor server -f webpack
```
- `content/contents.lr`

``` md
_model: blog

```
- `blog.ini`

``` ini
[model]
name = Blog
label = Blog
hidden = yes

[children]
model = blog-post
order_by = -pub_date, title
slug_format = {{ this.pub_date|dateformat('YYYY-MM-dd') }}/{{ this.title }}/

[pagination]
enabled = yes
per_page = 1
```
- page 1: `/`
- page 2: `/page/2/` (403) → `/page/2/index.html` (work)
- page 3: `/page/3/` (403) → `/page/3/index.html` (work)
- ...

page 2, 3, ... link generated by `this.pagination.next|url`

I think it is bug of test server

**Comment by mitsuhiko** [comment]
The URL looks correct. Are you saying that the pages > 1 do not load in the dev server?

**Comment by item4** [comment]
yes

**Comment by mitsuhiko** [comment]
Unfortunately I cannot reproduce this one which is annoying. Need to figure out what's wrong there.

**Comment by item4** [comment]
@mitsuhiko See my real blog (warn: korean) `git@github.com:item4/item4.github.io.git`

## requirements
- node 5.0 or higher
- lektor master branch

use `lektor server -f webpack` to launch dev server

**Comment by item4** [comment]
## additional info

``` console
(lektor)[item4@item4-mbp testing]$ python --version
Python 2.7.10
(lektor)[item4@item4-mbp testing]$ lektor --version
Lektor, version 2.0.dev0
```

mac os x 10.11.2 firefox 43.0.1
