### ISSUE TITLE
lektor 2: slug generated with url function always links to primary

### ISSUE THREAD

**Issue by steckerhalter** [lektor/lektor#162]
so if there are two alternatives `en` (primary) and `de`, on the index page (e.g.`/de/index.html`) an url generated with `{{ '.'|url(alt='de') }}` is rendered as `/en/` instead of `/de/`

Is it clear what I mean?

**Comment by mitsuhiko** [comment]
Odd. That should not happen with Lektor 2.  Do you have a test case for this somewhere I can have a look at?  I have a project where this behavior does not happen which is why I would like to have some details.

**Comment by steckerhalter** [comment]
Lektor 2 is master, right? I have just tried the default quickstart project and it looks ok there. I'm not yet sure what causes it in my project.

**Comment by mitsuhiko** [comment]
jup. is master

**Comment by steckerhalter** [comment]
ok, I found out why it happens. I have:

```
_model: blog
```

in the top-level `contents.lr`. When I remove that the problem is not occuring. Maybe it's my fault? :)

**Comment by steckerhalter** [comment]
Although that at least worked ok with v1.2

**Comment by mitsuhiko** [comment]
I wonder if it's broken for the first page of the pagination.

**Comment by steckerhalter** [comment]
Doesn't seem to be the case (also wrong on 2nd page). It works ok on subpages of the blog though.

**Comment by steckerhalter** [comment]
It's also wrong on the default quickstart project on the blog.
