### ISSUE TITLE
Access to related objects

### ISSUE THREAD

**Issue by asyncee** [lektor/lektor#165]
Hello, can you help me to output related objects?

I have a blog-post model with field

```
[fields.tags]
label = Тэги
type = checkboxes
source = site.query('/tags')
```

In the template i do {{ post.tags }} and i get output [u'tag1', u'tag2'] which is just a plain list, but i want list of Page objects, filtered by a blog-post.

**Comment by mitsuhiko** [comment]
Please use stackoverflow for questions and not the issue tracker :)
