### ISSUE TITLE
generate incorrect file name

### ISSUE THREAD

**Issue by item4** [lektor/lektor#17]
- `/content/test.xml/contents.lr`

```
_template: test.html

---
_model: none
```
- `/models/none.ini`
  → empty
- `template/test.html`

``` html
hello world
```
- log

```
U index.html
U page/2/index.html
U page/3/index.html
U page/4/index.html
U 2015-12-21/Hello_Website/index.html
U 2015-12-21/Hello_Website1/index.html
U 2015-12-21/Hello_Website3/index.html
U temp-test.xml
```

I want to get `test.xml` but got `temp-test.xml`. How to remove it?

**Comment by mitsuhiko** [comment]
If you get a slug named `temp-X` then you have a `slug_format` configured that failed to evaluate.  For instance because it tried to use a function on a field that is not set.  You could force the `_slug` or fix your expression to not fail.
