### ISSUE TITLE
Relative link still broken with markdown

### ISSUE THREAD

**Issue by cynddl** [lektor/lektor#170]
Using lektor 1.2.1, the issue #75 is still not fixed. A relative URI for an attachment in a blog post still leads to wrong paths in the content of `/blog`. However, the commit c95717b was supposed to fix the issue and is included in the release.

**Comment by cynddl** [comment]
I was a little puzzled, so I checked and c95717b (from Jan 5th) was actually not included in lektor 1.2.1 (from Feb 3rd), at least using the version from pypi. Shouldn't #75 be released with a bugfix release?

**Comment by mitsuhiko** [comment]
@cynddl correct. However this was not a bug but a missing feature in 1.0. It's in 2.0 only because it required significant changes. 2.0 will release soon though.
