### ISSUE TITLE
Values get saved even when validation fails

### ISSUE THREAD

**Issue by niijv** [lektor/lektor#179]
Tested for Integer and Float, in both cases it is possible to save invalid values from admin ui to contents.lr even if the validation failed because onChange gets called before the validation.
Need to check for other types.

Also the float validation should be reworked because of the limitations of the builtin `parseFloat`.

**Comment by go-bears** [comment]
@mitsuhiko @niijv 

@go-bears and @arbonanp can try to rework parseFloat?  We see that the parseFloat is being called in primitiveWidgets.jsx  in the FloatInputWidget component. Is the concern around  parseFloat() has a 17-digit limitation?  Were you considering a javascript regex solution in place of parseFloat()?

**Comment by niijv** [comment]
@go-bears 
There is already a branch fixing the parseFloat() with a regex solution. (https://github.com/lektor/lektor/tree/bugfix/validation) If you see limitations with the solution there, please submit a pull request on that branch!

The original defect is that even when the validation returns an error, the user is still able to save.
Maybe @mitsuhiko can review if he likes the overall approach there, I will open a pull request for it then.
