### ISSUE TITLE
Lektor Publish do not use environment variables when used from admin 

### ISSUE THREAD

**Issue by gops** [lektor/lektor#186]
as per this, 

https://www.getlektor.com/docs/deployment/ftp/ 

in credential sections, environment variables do not being used while using publish button from admin section from web apps. while lektor deploy from command line works as intended.

**Comment by mitsuhiko** [comment]
Is this running with the Lektor.app GUI app?

**Comment by gops** [comment]
I do not have access to Mac or OS X, Sorry.

**Comment by mitsuhiko** [comment]
I cannot reproduce this at all. Can you describe what environment you are using?
