### ISSUE TITLE
Document LEKTOR_DEV and support it in GUI App

### ISSUE THREAD

**Issue by item4** [lektor/lektor#189]
This make plugin developing hard.

Reason is simple, lektor command reuse first loaded env, so non-document file was detected change by watchdog but happen nothing.

I want to reload plugins and configs automatically when I changed plugin or config.

**Comment by mitsuhiko** [comment]
`LEKTOR_DEV=1` enables reloading for plugins. However this does not work with the GUI app yet.

**Comment by xlotlu** [comment]
This is now documented and there's no GUI app anymore.
