### ISSUE TITLE
pygments.css pruned right away

### ISSUE THREAD

**Issue by steckerhalter** [lektor/lektor#190]
this is with quickstart and files added as described here: https://github.com/lektor/lektor-markdown-highlighter

``` bash
$ lektor clean --yes
Started clean
D index.html
D blog/index.html
D blog/first-post/index.html
D static/style.css
D projects/index.html
D about/index.html
Finished clean in 0.10 sec
 $ ~/.pyenv/libexec/lektor build
Started build
U index.html
U static/pygments.css
U projects/index.html
U about/index.html
U blog/index.html
U static/style.css
U blog/first-post/index.html
Finished build in 0.27 sec
Started prune
D static/pygments.css
Finished prune in 0.02 sec
```

pygments.css is always pruned, same thing happens with `lektor server`

**Comment by mitsuhiko** [comment]
I noticed that. It's a bug in the plugin. It gets pruned if there is no config for the plugin. It shoudl be reported against the plugin directly.

**Comment by steckerhalter** [comment]
Thanks, I think I have found the problem. I named the config `highlighter.ini` instead of `markdown-highlighter.ini`
