### ISSUE TITLE
404 page not rendering in dev for alts

### ISSUE THREAD

**Issue by tathagatbanerjee** [lektor/lektor#194]
Hello,

Trying to add in a 404.html for alts. Tried two options.

**Option 1 - Using _model: page**

In `content/404.html/contents.lr`:

```
title: Page Not Found

---
body: Page Not Found

---
footer: © 2016
```

In `content/404.html/contents+hi.lr`:

```
title: पृष्ठ नहीं मिला

---
body: पृष्ठ नहीं मिला

---
footer: © २०१६
```

Output - `/saycheese/` does not exist:
- Image below is correct and showing the 404.html properly.
  ![image](https://cloud.githubusercontent.com/assets/11780602/14415943/dc48b042-ffe7-11e5-9329-5614ec63d124.png)
- Image below is _incorrect_ and _not_ showing the 404.html in the relevant language, it is flicking it back to primary language.
  ![image](https://cloud.githubusercontent.com/assets/11780602/14415957/0ffab05c-ffe8-11e5-98c1-03448e0564e8.png)
- Image below shows that the 404 exists in the alt when manually navigated to:
  ![image](https://cloud.githubusercontent.com/assets/11780602/14415972/631f272c-ffe8-11e5-81cd-9b0c070f7f44.png)

**Option 2 - Using custom model and template only.**
- `contents.lr` - Also shows directory structure
  ![image](https://cloud.githubusercontent.com/assets/11780602/14416085/ab5a0f4c-ffe9-11e5-959a-3e7fa491eda5.png)
- `error.ini` in databags:

```
[en]
error_title = Page Not Found
error_tag = Page Not Found
error_footer = © 2016

[hi]
error_title = पृष्ठ नहीं मिला
error_tag = पृष्ठ नहीं मिला
error_footer = © २०१६
```
- `error.ini` in models:

```
[model]
name = Error
label = {{ this.title }}

[fields.title]
label = Title
type = string

[fields.body]
label = Body
type = string

[fields.footer]
label = Footer
type = string
```
- `test_platform.lektorproject`:

```
[project]
name = test_platform
url_style = absolute

[alternatives.en]
name = English
primary = yes
locale = en_US

[alternatives.hi]
name = Hindi
url_prefix = /hi/
locale = hi
```
- `templates/404.html`:

```
{% extends "layout.html" %}
{% block title %}
    {{ bag('error', this.alt, 'error_title') }}
{% endblock %}

{% block body %}
    {% if this._path != '/' %}
    <h2>{{ bag('error', this.alt, 'error_title') }}: Opt 2</h2>
  {% endif %}

  {{ bag('error', this.alt, 'error_tag') }}
{% endblock %}

{% block footer %}
    {{ bag('error', this.alt, 'error_tag') }}
{% endblock %}
```

Output
- Image 1: the normal 404 works fine
  ![image](https://cloud.githubusercontent.com/assets/11780602/14416183/9a10eeb2-ffea-11e5-9538-5a1d12e8ec41.png)
- Image 2: the alt does not work again
  ![image](https://cloud.githubusercontent.com/assets/11780602/14416194/b91067c0-ffea-11e5-9386-8dd480fa7ba8.png)
- Image 3: manually navigating to alt works fine
  ![image](https://cloud.githubusercontent.com/assets/11780602/14416224/e1f586de-ffea-11e5-839b-79eeac509e2e.png)

Please Note: I am submitting this Issue for the first time. If any other specific information is needed, please let me know and I'll come back as quickly as I can. 

Thanks so much.

Tat

**Comment by mitsuhiko** [comment]
If I understand correctly you want different error pages in different "languages"? This will be tricky because at least github pages and some other systems only support one 404 page.

**Comment by tathagatbanerjee** [comment]
Hi Armin,

Yes that is the requirement. However I understand more and get why it is complex. Thanks for coming back to me. 

Tat

**Comment by mountainash** [comment]
An alternative to two 404 pages, is to have one page with all languages output on it. You could (if desired) use Javascript `navigator.language` to only show the required translation.
