### ISSUE TITLE
Loading Interface ... after lektor 2 update

### ISSUE THREAD

**Issue by Astate** [lektor/lektor#196]
after pip install lektor update,  when i whant to connect in admin i have the message : Loading Interface ... 

```
    var $LEKTOR_CONFIG = {
      admin_root: "/admin",
      site_root: "",
      lang: "fr"
    };
```

**Comment by Astate** [comment]
I have same problem with new installation, quickstart blog
i use curl -sf https://www.getlektor.com/install.sh | sh

**Comment by ggranger** [comment]
Same here, same config (french language).
Chrome console shows the following error:
i18n.jsx?6ab6:39 Uncaught TypeError: Cannot read property 'BACK_TO_OVERVIEW' of undefined

**Comment by mitsuhiko** [comment]
What's the language on your computer set to?

**Comment by ggranger** [comment]
The computer is set to fr_FR language (OSX 10.11.4)

**Comment by Astate** [comment]
Me fr_CA

**Comment by Astate** [comment]
Just to be clear i dont use OSX, i use linux

**Comment by mitsuhiko** [comment]
Yeah, this was fixed in 2.2 independent of OSX.

**Comment by Astate** [comment]
its because i just find a change version here in bugfix  [9dfa6cc](https://github.com/lektor/lektor/commit/9dfa6cc13c54d54f822ebf36946f03be57625eb5)

**Comment by mitsuhiko** [comment]
@Astate the bugfix was that i correctly built the translation cache before pushing it to pypi.

**Comment by diramazioni** [comment]
I have the exact same error on ubuntu with **it** locale using lektor master and python 2 venv. The admin interface doesn't get loaded. Where is LEKTOR_CONFIG ? It is working with just **en** locale?
