### ISSUE TITLE
Custom sort function?

### ISSUE THREAD

**Issue by ChillarAnand** [lektor/lektor#199]
Pagination ordering supports only asc/desc of selected field types. Is it possible to define custom sort function?

---

I have created a model called [book](https://github.com/ChillarAnand/ProjectChalam/blob/master/models/book.ini) which has titles in english and telugu languages. I would like to show telugu titles first and then english titles.

**Comment by mitsuhiko** [comment]
Unfortunately Python's collation support does not permit this. Currently there is no way this can be implemented which is why I will close this as wontfix.  That said, if someone wants to undergo that work I will accept patches.
