### ISSUE TITLE
overriding parent _hidden field in content does not have desired effect

### ISSUE THREAD

**Issue by krosaen** [lektor/lektor#203]
Per docs [here](https://www.getlektor.com/docs/api/db/system-fields/hidden/) on the `_hidden` system field:

> This also automatically applies to all children of a page unless they forcefully override this setting.

I'm trying to use this in a website to expose urls like:

/podcasts/pistons/3

while having a 404 for

/podcasts/

Here's a branch illustrating:

https://github.com/krosaen/brosaen-lektor/compare/unhidden-content-children?expand=1

note I'm hiding `/podcasts/` and attempting to unhide `/podcasts/pistons/`. Should this be possible? Not sure if this is a bug or a feature request / misunderstanding of the docs.

**Comment by photong** [comment]
I have the same problem. The docs state that for child configuration:

hidden: if this is set it can override the parent's hidden flag for all children. This is particularly useful if you want to have a folder for error pages or other special pages where the parent itself should not be rendered but all children are. The default is not set.

In the "Categories" guide (https://www.getlektor.com/docs/guides/categories/), if "project-categories/contents.lr" has "_hidden: yes", then children give 404 even though they are _not_ hidden (e.g., children] hidden = no"). There seems to be no way to have a hidden parent and rendered children.
