### ISSUE TITLE
Lektor documentation in PDF format !

### ISSUE THREAD

**Issue by jigarmistry** [lektor/lektor#210]
Is there any way to have lektor documentation in PDF format?

**Comment by odeckmyn** [comment]
any offline format would fit for me !

I use https://kapeli.com/dash for offline documentation and getting Lektor added there would be delightful !

**Comment by mitsuhiko** [comment]
There is no documentation in PDF format and there are no plans for it. It would be cool to have but maintaining this is too much work for me right now.
