### ISSUE TITLE
HTML in Markdown

### ISSUE THREAD

**Issue by zanderle** [lektor/lektor#211]
Based on [markdown syntax documentation](https://daringfireball.net/projects/markdown/syntax), one should be able to use HTML in Markdown. However Lektor escapes the content and makes it impossible to use HTML in a markdown field.

I think this should either be fixed, or mentioned explicitly in the documentation.

**Comment by dairiki** [comment]
HTML in Markdown fields works for me.

Can you give an example of markdown source which is causing problems?

**Comment by zanderle** [comment]
@dairiki ah, silly me. I tested three times before submitting an issue to make sure. And now, while copying to the thread, I saw that I had a typo in the code. My bad.

I guess that's a sign that I should call it a day.
