### ISSUE TITLE
curl based installer needs to be improved (Ubuntu installation needs stuff in $Path)

### ISSUE THREAD

**Issue by ghost** [lektor/lektor#213]
I'm throwing the installation command in a Ubuntu terminal and get an error message.

> Error: None of the items in $PATH are writable. Run with sudo or add a $PATH item that you have access to.

I ran the same command as sudo but to no avail. The documentation just says:

> Once you have those installed and have made sure that they are on your PATH, you can get Lektor installed with our installation script

I have no idea how to do that and feel it is an unnecessary burden to make it a premise to install lektor.

Can't this be done by the script?

**Comment by pyjavo** [comment]
I had the same problem and this is what worked for me:

I created a virtualenv, activated and then run the curl command in it. The error message didn't show up and everything worked great. Didn't have to do anything with $PATH at all.

**Comment by davidism** [comment]
If you're creating a virtualenv, you might as well just pip install it.  The recommendation is _not_ to install Lektor in a virtualenv though.  Modify `PATH` in `~/.bashrc` to add `.local/bin` (or wherever you want) to your path.  Then open a new terminal.

```
export PATH="$HOME/.local/bin:$PATH"
```

This should probably be included in the docs.

**Comment by ghost** [comment]
> Modify PATH in ~/.bashrc to add .local/bin (or wherever you want) to your path.

I have no idea what that means. The only instance of "path" in my `.bashrc` is in:

```
# If set, the pattern "**" used in a pathname expansion context will
# match all files and zero or more directories and subdirectories.
#shopt -s globstar
```

Where do I want to add `.local/bin` ?
Can't this be done automatically?

**Comment by davidism** [comment]
You literally put that line at the end of the file.  It should not be done automatically.

**Comment by ghost** [comment]
Here is what I did:
1. open`~/.bashrc`
2. add `.local/bin`
3. open a terminal
4. enter `export PATH = "$HOME/.local/bin:$PATH"`
5. enter `sudo curl -sf https://www.getlektor.com/install.sh | sh`
6. I get:

```
Welcome to Lektor

This script will install Lektor on your computer.

Error: None of the items in $PATH are writable. Run with sudo or add a $PATH item that you have access to.

```

I'm probably missing something obvious. I can't see it though.

**Comment by davidism** [comment]
So, instead of adding the line I posted in step 2, you just added `.local/bin`?  And then you entered the line I posted in the termainl?  That's not what my instructions were.

**Comment by davidism** [comment]
Put the full `export` line, not just the name of the directory, _in_ `.bashrc`.  Make sure the directory exists.  Open a new terminal.  Run the command.

**Comment by ghost** [comment]
Here is what I _now_ did:
1. open`~/.bashrc`
2. add `export PATH = "$HOME/.local/bin:$PATH"`
3. make sure ~/.local/bin exists _(it does and contains pip, pip2 & pip2.7)_
4. open a terminal
5. enter `sudo curl -sf https://www.getlektor.com/install.sh | sh`

What I get is the same error again.

**Comment by davidism** [comment]
My bad, typo.  There shouldn't be any space around the `=` in the `export` command.  Actually you should have seen an error with that.  And don't use `sudo` in front of the curl command (it's not doing anything anyway, you would need it in front of the `sh` command (but don't do that either)) If that's not it then I can't reproduce your issue.

**Comment by ghost** [comment]
After your suggestions and running `source ~/.bashrc` to "refresh" the new setting I finally could install lektor!
Thank you!

Isn't there a way to make this a non-issue for ubuntu users in the future?

**Comment by pyjavo** [comment]
what do you think about it @mitsuhiko ? Maybe now that @mray has an answer he can make a collaboration on this issue.

**Comment by mitsuhiko** [comment]
The installer should be improved for sure! I will update the title.

**Comment by arbonap** [comment]
Hi @mitsuhiko -- we should merge Issues #250 and this one (#213), since they seem to be one and the same.

**Comment by xlotlu** [comment]
The curl-based installer is gone since https://github.com/lektor/lektor-website/pull/298. Please open a new issue if the problem still exists.

**Comment by amachefe** [comment]
> The curl-based installer is gone since [lektor/lektor-website#298](https://github.com/lektor/lektor-website/pull/298). Please open a new issue if the problem still exists.

I tried to install lektor using the command like option and get the same results as mentioned. After reading this comment, i went back to search for alternative "non curl based installer" but could not see. 
Infact the website listed the curl based installation as the main option
