### ISSUE TITLE
Add datetime type and timezone support

### ISSUE THREAD

**Issue by item4** [lektor/lektor#22]
I can use [date type](https://www.getlektor.com/docs/api/db/types/date/) but it can not save time info.

Please add datetime type

Known Issue:
- timezone?

**Comment by mitsuhiko** [comment]
Yep. That's missing, largely because it needs a story for timezones.

**Comment by item4** [comment]
@mitsuhiko Do you have any plan about datetime for official type? or I want to make plugin for my blog.

**Comment by niijv** [comment]
Datetime is planned as an official type as far as I know.

**Comment by mitsuhiko** [comment]
I will merge this, just need docs and everything else too which is why it's not done yet.

**Comment by mitsuhiko** [comment]
This one is actually in now.
