### ISSUE TITLE
[not an issue] thanks for making Lektor!

### ISSUE THREAD

**Issue by ericmjl** [lektor/lektor#221]
I'm in the process of switching my personal website to Digital Ocean from Bluehost, and [Lektor](http://www.ericmjl.com) from [Wordpress](http://www.ericmajinglong.com). Big kudos to @singingwolfboy for introducing me to it! Just wanted to drop a note to say thanks 😄. Huge speed-ups, website is much cleaner as well.

Definite plus of using the admin GUI: one-click publishing after setting it up with rsync!

**Comment by mitsuhiko** [comment]
\o/
