### ISSUE TITLE
Packaging and distribution of templates

### ISSUE THREAD

**Issue by nomorepanic** [lektor/lektor#226]
I was wondering if Lektor is going to have a standard for packaging and distributing sets of templates and assets (themes if you like the term).

Here on the issues and on the docs there is no mention of anything like this.

**Comment by milibopp** [comment]
Interesting, I am looking into a similar problem right now. Trying to use [gitman](https://github.com/jacebrowning/gitman) for this at the moment, because it seems like a concern that is orthogonal to Lektor itself.

**Comment by milibopp** [comment]
So after trying to do this for a while, I think the main issue here is some kind of theming support. For inspiration it may be interesting to look at [Hugo's theme feature](https://gohugo.io/themes/overview/).

Very basic requirements that might make sense from my experience working on Hugo:
- Support loading templates, models, etc. from a different folder, e.g. `my_theme/templates/`
- Allow extending and overriding of these external templates locally. Say you have `my_theme/templates/` and `templates/`. In that case, `templates/` should take precedence.

**Comment by mitsuhiko** [comment]
I would be happy to get something like this in but I probably would need help with it.

**Comment by singingwolfboy** [comment]
[Cookiecutter](https://github.com/audreyr/cookiecutter) seems like it might be a useful resource for building themes and templates, as well.

**Comment by capriosa** [comment]
Isn't it possible to use Lektor's very own install script?  
lektor quickstart build a skeleton
This may be extended so one can build a own skeleton with lektor name_of_theme

**Comment by milibopp** [comment]
@capriosa that would help some use cases, yes. But if you want to share layouts between repositories it doesn't help, because that's only done once, when you start the project and not updated after that.

**Comment by capriosa** [comment]
@aepsil0n ok, I see. Hugo has all themes on github. May be that's a solution.

**Comment by spyoungtech** [comment]
@capriosa I like that idea. I think it keeps things simple and flexible.

**Comment by xlotlu** [comment]
Closed in v3.1. https://www.getlektor.com/docs/themes/
