### ISSUE TITLE
Hosting the Admin Interface?

### ISSUE THREAD

**Issue by ollieh** [lektor/lektor#237]
Is it possible to host the admin interface and make it password protected or account based?

**Comment by mitsuhiko** [comment]
It is not yet possible but the plan exists :)

**Comment by ndarilek** [comment]
If there's a plan, has any of it been implemented yet? Or is there any way to follow development?

I'm working on [Sandstorm](https://sandstorm.io) integration, which may be a partial solution. Sandstorm could secure the admin interface, but what appears to be missing is VCS integration, or at the very least, some mechanism to run commands on administrative actions. What I'd like to do is run a git commit whenever a file is saved so I can update the Sandstorm-hosted git repository when admin area changes are made. With that in place, I can at least partially solve this issue for anyone wanting to use Sandstorm for hosting. Maybe there could be some mechanism for accepting a templated command with placeholders? For instance, maybe something for relative/absolute paths, the model label, and a date/time so I can run a git commit with a meaningful commit message.

**Comment by timmarinin** [comment]
@ndarilek: how is it going with Sandstorm integration?

**Comment by ndarilek** [comment]
Shelved for now. I was pushing the site to a Sandstorm-hosted Git 
repository, then letting Sandstorm build it remotely. Unfortunately this 
fails with plugins, as Sandstorm does not allow apps to connect to 
external sites like the package index.

I'm not familiar enough with Python to know what a good solution would 
look like. Basically, plugins need to be referenced from the 
configuration and entirely vendored in the repo. Thoughts welcome.

**Comment by ollieh** [comment]
I got this sort of going by putting Lektor behind a nginx reverse proxy, and getting that to do the password protection.
