### ISSUE TITLE
iframe html in markdown halts further rendering of template

### ISSUE THREAD

**Issue by nsfmc** [lektor/lektor#241]
Suppose you have some markdown content, ala

``` ini
; blog.ini
;...
[fields.content]
label = Page Content
type = markdown
```

and a template that renders that

``` jinja
{# blog.html #}
{{ this.content }}
```

if one of your blog contents.lr files looks like this:

``` markdown
Here is a gyfcat iframe embed of some rotating triangles

<iframe src="http://gfycat.com/ifr/LinearWideeyedHorsefly" frameborder="0" scrolling="no" width="600" height="200" style="-webkit-backface-visibility: hidden;-webkit-transform: scale(1);"></iframe>

this text never renders even though the above iframe does
```

However, if you update `blog.html` to 

``` jinja
{{ this.content|safe }}
```

the entirety of the markdown is rendered.

**Comment by mitsuhiko** [comment]
Also why is this not `{{ this.content }}`?

**Comment by nsfmc** [comment]
oh whoops, sorry, i just was freehanding the jinja bits! (will edit the issue). let me test with other tags

**Comment by nsfmc** [comment]
ok, i am _suuuuuper_ sorry to bother you, but i found what the problem is, and it appears to be with mistune (i'll report there)

here's a small piece of failing markup:

``` shell
In [38]: mistune.markdown('<iframe src="http://gfycat.com" ></iframe>', escape=False)
Out[38]: '<p><iframe src="http://gfycat.com" >&lt;/iframe&gt;</p>\n'
```

but

``` shell
In [39]: mistune.markdown('<iframe src="http://gfycat.com"></iframe>', escape=False)
Out[39]: '<p><iframe src="http://gfycat.com"></iframe></p>\n'
```

on checking the raw source, i'm seeing that the rest is indeed rendered correctly by jinja2, i just reported this bug poorly originally by changing both the markup and the filter at the same time, i confounded myself. :( thanks again, sorry for the inconvenience

**Comment by mitsuhiko** [comment]
Does this mean I can close this here?

**Comment by nsfmc** [comment]
yes, sorry about that
