### ISSUE TITLE
Some JPG image thumbnails dont work

### ISSUE THREAD

**Issue by ericmjl** [lektor/lektor#242]
While trying to figure out how to use thumbnails, I noticed that all of the documentation examples only showed `image.thumbnail(width)`, rather than `image.thumbnail(width, height)`. In my hands, I have always had to explicitly specify both `width` and `height`; specifying only `width` causes image rendering to fail.

Might I be missing something?

**Comment by ollieh** [comment]
I am experiencing the same issue. End of the traceback:

```
  File "/nix/store/mxz550a80vm0mp0qabrbzypl4k7qd1pn-python2.7-Lektor-2.3/lib/python2.7/site-packages/lektor/db.py", line 780, in thumbnail
    width=width, height=height, crop=crop)
  File "/nix/store/mxz550a80vm0mp0qabrbzypl4k7qd1pn-python2.7-Lektor-2.3/lib/python2.7/site-packages/lektor/imagetools.py", line 382, in make_thumbnail
    source_height)
  File "/nix/store/mxz550a80vm0mp0qabrbzypl4k7qd1pn-python2.7-Lektor-2.3/lib/python2.7/site-packages/lektor/imagetools.py", line 331, in computed_height
    return int(float(actual_height) * (float(width) / float(actual_width)))
TypeError: float() argument must be a string or a number
```

**Comment by ollieh** [comment]
I figured out what was causing the issue:

`get_image_info()` in `imagetools.py` is using `imghdr.what()` on the first few bytes of images to identify their type (jpg, png, whatever). It's failing on some jpgs and not identifying them as anything, and returning `None`. I managed to fix the jpgs that it was having problems with by using imagemagicks convert command line utility like so:

`convert offendingimage.jpg offendingimage.jpg`
or for all the files in a directory
`find . -type f -name "*.jpg" -exec convert {} {} \;`

 I'm wondering if perhaps `imghdr` needs more than the bytes `get_image_info` gives it for some types of jpg?

**Comment by jschwartzenberg** [comment]
I just ran into this issue as well. The above conversion tip solved it. Thanks!

**Comment by ericmjl** [comment]
@singingwolfboy any help needed on this issue?

**Comment by jschwartzenberg** [comment]
I just discovered something. The 'file' command also gives different output for Images for which metadata can be read:

working images either have:
```
JPEG image data, JFIF standard 1.01
```
or:
```
JPEG image data, EXIF standard
```

images where it doesn't work show:
```
JPEG image data
```

**Comment by jschwartzenberg** [comment]
Maybe useful for others running into this, a script which fixes up the non-conforming images. It depends on ImageMagick.
```
#!/bin/bash

shopt -s globstar
for filename in **/*.jpg
do
  FILETYPE=`file -b "$filename"`
  if [[ $FILETYPE != *"JFIF"* && $FILETYPE != *"EXIF"* ]]; then
    convert "$filename" "$filename"
  fi
done
```

**Comment by madebr** [comment]
How about using [`identify`](http://www.imagemagick.org/script/identify.php)?

**Comment by xlotlu** [comment]
Given the silence on this one I think it's safe to consider it closed.
