### ISSUE TITLE
"Failed to install shell commands"

### ISSUE THREAD

**Issue by rajbala** [lektor/lektor#250]
I installed lektor.app 2.3 and attempted to install the shell commands, but get an error:  "Failed to install shell commands."

When I try to install using "sudo curl -sf https://www.getlektor.com/install.sh | sh" I get a different error:

Error: None of the items in $PATH are writable. Run with sudo or add a $PATH item that you have access to.

I Googled and found a thread that refers to Ubuntu, but not sure that it applies to OSX.  Am I doing something wrong?

I am using OSX 10.11.5, El Capitan btw.

**Comment by rajbala** [comment]
I am not running it directly from the dmg.  I launched Lector from the Applications folder.

**Comment by davidrpmorris** [comment]
+1
macOS 10.11.6

**Comment by evilangel-ru** [comment]
I've had same problem, just fixed. Looks like SIP is the problem. Try to disable it and reinstal Xcode Command Line Tools. For example here is a good [instruction](https://ohthehugemanatee.org/blog/2015/10/01/how-i-got-el-capitain-working-with-my-developer-tools/).

**Comment by xlotlu** [comment]
The curl-based installer is gone since https://github.com/lektor/lektor-website/pull/298. Please open a new issue if the problem still exists.
