### ISSUE TITLE
Certain Attachments copied to build output folder

### ISSUE THREAD

**Issue by ollieh** [lektor/lektor#265]
I have a `_redirects` file (for netlify) in the root of my content folder, and it doesn't get copied. I assume this is because of the lack of extension, or possibly the underscore.

**Comment by nixjdm** [comment]
From #423, @danielknell says:

> I tried to add a netlify _redirects file to my assets folder and it was ignored at build time, removing the underscore causes it to be copied.

> I am assuming the python convention of underscore prefixes denoting something that is not public is being applied to all files?

Seems like this is because of the underscore, but perhaps it's over-determined. I'm marking this as a bug.

**Comment by xlotlu** [comment]
Closing this in favour of the duplicate #423 , because of the clearer description.
