### ISSUE TITLE
Virtual env magic?

### ISSUE THREAD

**Issue by goanpeca** [lektor/lektor#266]
Great project :-)

**Lektor actively manages virtualenvs for plugin installations in very specific ways and this might or might not work in your setup. We support pip installations for deployment environments and local development only.**

Why does lektor manage virtualenvs?

Should not plugins just work by doing

`pip install lektor-some-plugin` ?

**Comment by goanpeca** [comment]
@singingwolfboy ?

**Comment by kylecrawshaw** [comment]
@goanpeca By using a virtualenv, plugin dependencies will not impact your local system python packages. Also if you use `lektor plugins add lektor-some-plugin` you'll only need to do that one time to add it to your `.lektorproject` and then your project configuration is far more portable and easier to setup on a new computer or environment. I think the goal is just to minimize the amount of ongoing dependency management that you as the user have to do.

**Comment by cvengler** [comment]
This basically makes it impossible to build a Lektor page in Nix, as its build sandbox does not allow for internet access, thereby making venv pip installs failing. :/

**Comment by dairiki** [comment]
> This basically makes it impossible to build a Lektor page in Nix, as its build sandbox does not allow for internet access, thereby making venv pip installs failing. :/

I am not familiar with Nix and its sandboxing, but note that it's possible to avoid using Lektor's venv magic altogether.  All that's necessary is to install plugins into the same top-level virtual environment as Lektor itself is installed in.  (Dependency management tools like uv, pdm, and poetry can be used for this.)

Note that this discussion continues (albeit at a somnolent pace) on #1087.
