### ISSUE TITLE
iOS application

### ISSUE THREAD

**Issue by DotTheI** [lektor/lektor#269]
Any chance of an iOS application for Lektor to be released?

**Comment by singingwolfboy** [comment]
Unfortunately, Python doesn't run on iOS, so I don't think this is possible.

**Comment by chipperdoodles** [comment]
I think there's a bee ware project for ios python apps, but the biggest problem here is that you'd need to package the project folder along with the application because of the sandboxing, so it doesn't make a lot of sense?
