### ISSUE TITLE
`resize_image` plugin or thumbnail quality parameter?

### ISSUE THREAD

**Issue by skorokithakis** [lektor/lektor#273]
The thumbnail method currently works fine for creating thumbnails (which are small, low-quality images), but it produces very ugly images when used for larger sizes. My use case is that I add a 21 MPixel photo to the directory and use `.thumbnail()` to generate the various sizes, which works fine for the very small ones (for the mosaic), but makes the photos look very compressed at sizes of 1000ish px.

Could we have a quality parameter, or another function that we could use to not compress images so much?

**Comment by tariquesani** [comment]
FWIW Reading the code shows me that the quality defaults to 75 for png and 85 for jpgs. This I have found to be a bit too high in most cases. Can you share a few hi-res images for me to experiment?

**Comment by skorokithakis** [comment]
Sure, you can get as many as you want [from Unsplash](http://unsplash.com/). However, this issue is more about making quality a parameter than about changing the default.

**Comment by tariquesani** [comment]
Let me see if I can code something on Monday. Will put in a pull request and hope it gets merged into the main project.

**Comment by tariquesani** [comment]
https://github.com/lektor/lektor/pull/292 - have created a pull request. If you want you can clone https://github.com/tariquesani/lektor/tree/feature/thumbnail-quality this and use it right away.

**Comment by skorokithakis** [comment]
That's fantastic, thank you. I'll use it right away.

**Comment by skorokithakis** [comment]
Thank you for implementing this, I think this can be closed.
