### ISSUE TITLE
Mac OS app does allow creating new projects

### ISSUE THREAD

**Issue by cpg** [lektor/lektor#282]
The mac app appears to not allow the user to create a new project.

This is all I see http://dl.dropbox.com/u/364883/Screenshots/lektor-skeltor.png when I open the app.

There is an icon with a pencil, but it's disabled and there is no menu to start a new project.

I would say that is a usability bug, if the app actually is capable of starting a project the user to create a project. Or maybe it's some permission issue? Or maybe the app cannot start new projects?

**Comment by mitsuhiko** [comment]
Correct. This is not really something that is expected to be implemented. The expectation is that a developer sets this up with the command line client.
