### ISSUE TITLE
Gallery of images

### ISSUE THREAD

**Issue by autoferrit** [lektor/lektor#288]
I would like to put together a gallery of images. Although I need them in a specific order. They are pairs of images as `before` and `after`. The gallery will be a 2 column page with before on the left and after in the right. Images would also have a category, which will group them on the page. So far i don't see an example to do this with the built in system. The docs on making a portfolio seem sort of close.

Example. Suppose i have these images

```
some_title-section_a-before.png
some_title-section_a-afterpng
some_title-section_b-before.png
some_title-section_b-after.png
another_title-section_b-before.png
another_title-section_b-after.png
```

Section a header would have one row with a pair of images and section b header would have 2 rows each with a pair of images in it.

I could also organize the images by category/section by having them in subdirectories if needed. I'm open to how the content is laid out.

What I'm wondering is what is the best way to setup images in a gallery like this. Would they be attachments? I was hoping to get some input. Or would it be best to just simply make the layout by hand? I was hoping to make it easy and just be able to upload an image for it to work.

**Comment by tariquesani** [comment]
Hi, 

Show what you have done till now and we can take it further. I have created albums with images as attachments - code can be seen at https://github.com/tariquesani/tariquesani.net 

P.S. The gitter chat is a great place to chat https://gitter.im/lektor/lektor

**Comment by joyhchen** [comment]
You can create a field that allows you to select an image from your attachments. Take a look here: https://github.com/joyhchen/lektor-foundation/blob/master/flowblocks/select-image.ini

If you use flow blocks you can then specify and change the order you want to display your images in.

**Comment by autoferrit** [comment]
I havent done it yet. i am currently thinking about using lektor for rebuilding a site (currently in wordpress) as they just need a static site. And it currently has a gallery built this way. I am building my own site using lektor already. I will check out those code samples you guys linked and let you know if they fit what im doing. thanks.
