### ISSUE TITLE
Install problem on Ubuntu 14.04 TLS

### ISSUE THREAD

**Issue by miratcan** [lektor/lektor#294]
```
mirat@ISM-LenovoDesktop:~$ sudo curl -sf https://www.getlektor.com/install.sh | sh

Welcome to Lektor

This script will install Lektor on your computer.

Error: None of the items in $PATH are writable. Run with sudo or add a $PATH item that you have access to.
```

My path values are:

```
mirat@ISM-LenovoDesktop:~$ echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
```

And I can create files on these locations:

```
mirat@ISM-LenovoDesktop:~$ sudo touch /usr/bin/test.txt
mirat@ISM-LenovoDesktop:~$ 
```

**Comment by singingwolfboy** [comment]
You can write to those directories using `sudo`, but you don't have permission when you are _not_ using `sudo`. When you're trying to install Lektor, you are running `curl` under `sudo`, but not `sh`. As a result, even though you have `sudo` at the front of your command, it's still not running as the root user.

I would recommend doing the following things, instead:
- Download the `install.sh` file to your computer using `curl`
- Read it to be sure it's not malicious (i.e. that you weren't subject to a man-in-the-middle attack)
- Execute it with `sudo sh install.sh`

That should work the way you expect.
