### ISSUE TITLE
Javascript tests fail when following README instructions

### ISSUE THREAD

**Issue by tariquesani** [lektor/lektor#295]
Doing 

```
$ virtualenv venv
$ . venv/bin/activate
$ pip install --editable .[test]
$ make test

```

The Python test run fine but 

```
---> running javascript tests

> lektor@0.0.0 test /home/tariquesani/tmp/lektor/lektor/admin
> jasmine

sh: 1: jasmine: not found
npm ERR! Test failed.  See above for more details.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?
make: *** [test-js] Error 1
```

Guess some parts of build-js need to be a dependency here.

**Comment by kylecrawshaw** [comment]
@tariquesani I just tested this with the changes that @singingwolfboy made in #318 and this issue appears to have been resolved. Now `build-js` is called before `test` which ensures that all node dependencies are installed.

**Comment by tariquesani** [comment]
Yes, this has been fixed now.
