### ISSUE TITLE
server loop with relative output path

### ISSUE THREAD

**Issue by ghost** [lektor/lektor#298]
`lektor build` accepts a relative output path and has no problem. When I do `lektor server -O somedir` it starts an endless loop of build/prune but does actually build successfully into the chosen output directory. Specifying a full path with `-O` or `--output-path` works fine. Verbose flag doesn't provide any useful information.

I'm on Arch, have tested this with Lektor 2.3 and 3.0 and with a fresh project.

```
Started source info update
Finished source info update in 0.05 sec
Started build
U index.html
U projects/index.html
U about/index.html
U blog/index.html
U static/style.css
U blog/first-post/index.html
Finished build in 0.07 sec
Started prune
Finished prune in 0.00 sec
Started build
Finished build in 0.02 sec
Started prune
Finished prune in 0.00 sec
Started build
Finished build in 0.02 sec
Started prune
Finished prune in 0.00 sec
Started build
Finished build in 0.01 sec
Started prune
Finished prune in 0.00 sec
Started build
Finished build in 0.01 sec
Started prune
Finished prune in 0.00 sec
Started build
```

**Comment by odeckmyn** [comment]
same here (w/ 2.3)
