### ISSUE TITLE
Werkzeug Debugger Access

### ISSUE THREAD

**Issue by eligundry** [lektor/lektor#311]
I'm currently trying to port an existing site over to Lektor and am having a little bit of trouble determining what my variables in my template look like. When I run into this situation while developing a traditional Flask application, I will attempt to raise an exception in the template and then use the Werkzeug Debugger to sus out what my template variables are like. The issue that I am running into is that it doesn't seem like there is a way to disable the builtin errorhandler and make it use the Werkzeug one.

I suspect that this is a conscious decision from a design perspective (the amount of people deploying Flask apps using the builtin server in debug mode makes me shudder), so maybe adding this via an explicit CLI switch and/or requiring `LEKTOR_DEV` to be true in order to use it might make sense.

**Comment by xlotlu** [comment]
This is impossible due to the way the dev server is architected: it runs an actual builder in a background thread, and in fact serves static files.

So closing this. If you have alternate ideas for improving debugging, they're welcome.
