### ISSUE TITLE
Why can Lektor server not serve an .mp4 but an .ogv?

### ISSUE THREAD

**Issue by benjaminweb** [lektor/lektor#312]
602bcaf adds mp4 to lektor.

Which steps are required to reproduce the problem?
1. Download: http://www.w3schools.com/HTML/mov_bbb.mp4
2. Attach `mov_bbb.mp4` to page (confirm type in parentheses to be video).
3. Open `localhost:5000/my_page/mov_bbb.mp4`
4. Observation: mov_bbb.mp4 can't be played in the browser (Chrome, Opera) directly: play button can't be clicked.

If I do the same with an .ogv, there is no problem.

**Comment by runfalk** [comment]
This does sound like a codec issue. Some Linux distros ship without H.264 codecs. That commit only marked mp4 attachments as videos.
