### ISSUE TITLE
Publishing failure when using Docker

### ISSUE THREAD

**Issue by meatballs** [lektor/lektor#315]
I've attempted to use lektor within a docker container and hit an error when attempting to publish. The full details are on this stackoverflow question: http://stackoverflow.com/questions/40504793/how-can-i-run-lektor-within-a-docker-container

The problem appears to be the fact that the project files are mounted on a separate volume within the container. Since the build path is elsewhere within the container, the filesystems are different and the hard linking in `publisher.link_artifacts` fails.

Can I suggest an extra condition at the top of that method which checks whether the project folder and the temporary folder are on the same volume and, if not, uses `shutil.copy` rather than `os.link`?

**Comment by meatballs** [comment]
Perhaps using `os.path.ismount(path)` on the project folder would be sufficient

**Comment by meatballs** [comment]
To be clear - I'm happy to fix this and submit a PR. I just wanted to check first that it's the way to go.

**Comment by singingwolfboy** [comment]
A pull request would be great!

**Comment by tariquesani** [comment]
@meatballs will you be submitting a pull request?

**Comment by meatballs** [comment]
My apologies - I had forgotten all about this. I'll put something together in the next few days.

**Comment by tariquesani** [comment]
@meatballs  Sorry to bug you but once again will you be submitting a pull request? :smile:

**Comment by tgpfeiffer** [comment]
I think this has been fixed in #416

**Comment by nixjdm** [comment]
I think you're correct. Thanks for pointing it out!
