### ISSUE TITLE
Github page's custom domain gets overwritten when new build deployed

### ISSUE THREAD

**Issue by kuc2477** [lektor/lektor#322]
I'm really enjoying the lektor's super easy build & deploy system with Github Page which is really outstanding and smooth compared with other static site generators.

But there's a little issue with this deploy system when using with custom domain configured Github Page. 

The problem is that custom domain setting of Github Page is overwritten with empty string whenever I deploy a new build even when I set custom domain for my Github Page in `settings` tab explicitly right before the deployment.

Except for this issue, I'm really enjoying and feeling thankful for your works with this awesome static CMS system. 

Thanks.

**Comment by singingwolfboy** [comment]
@kuc2477 Have you checked out the documentation for this? https://www.getlektor.com/docs/deployment/ghpages/#cname-support

Is this documentation confusing? Is there a way that we can make it more clear or discoverable?

**Comment by kuc2477** [comment]
@singingwolfboy Thanks for the quick feedback. I think it would be better to warn people in the documentation that lektor overwrites Github Page's CNAME file with the `cname` parameter given in lektorproject configuration.

**Comment by singingwolfboy** [comment]
@kuc2477 that's great feedback! Can you make a pull request to edit the website and add that warning? https://github.com/lektor/lektor-website/blob/master/content/docs/deployment/ghpages/contents.lr

**Comment by ramonsuarez** [comment]
The cname gets deleted with or without the cname parameter in the target . In the documentation it says this will be overwritten by lektor each time, but it does not happen. I have to manually enter it on the repos' settings page every time I deploy. Should I submit this as a new bug? Thanks for building lektor!
