### ISSUE TITLE
Admin crashes with - TypeError: Super expression must either be null or a function, not object 

### ISSUE THREAD

**Issue by tariquesani** [lektor/lektor#325]
Whenever I try to navigate to the admin it crashes with the following error 

TypeError: Super expression must either be null or a function, not object

Tried this on Ubuntu 16.04

![screenshot from 2016-11-16 12 58 33](https://cloud.githubusercontent.com/assets/27067/20338379/afe085a4-abfc-11e6-8d35-ec548c4b49c2.png)

**Comment by singingwolfboy** [comment]
@tariquesani can you include a full traceback?

**Comment by tariquesani** [comment]
Running npm install in the admin directory fixed it. I guess nothing to do for now. 

Thanks
