### ISSUE TITLE
JSON data bags have to contain top level object

### ISSUE THREAD

**Issue by belteshassar** [lektor/lektor#329]
JSON databags have to contain an object at the top level. Specifically, users might try to e.g. load a databag with an array as the top level datastructure. In this case, the `get_bag()` method returns an empty `OrderedDict`. This happens because on [line 51](https://github.com/lektor/lektor/blob/master/lektor/databags.py#L51), the loaded json is merged with an empty OrderedDict(). The `merge()` function has no way to handle merging a `dict` with a `list` and thus resorts to the default case of just returning the first argument.

A simple workaround is to wrap the array in an object, like this:

```JSON
{
  "array": [
    "elem0",
    "elem1",
    "elem2"
  ]
}
```

**Comment by krzysztof-sikorski** [comment]
This behaviour is (IMHO) by design - as the name suggests, a "databag" is a "bag with data", in other words a dictionary - which in JSON world translates to object type.
