### ISSUE TITLE
Question: How to clean uninstall after install manually?

### ISSUE THREAD

**Issue by item4** [lektor/lektor#335]
I was installed lektor manually, but I use lektor in virtualenv only. I want to uninstall globally-installed lektor but there is no document.

**Comment by item4** [comment]
I think someone must make related document.

**Comment by singingwolfboy** [comment]
@item4 Can you clarify exactly what steps you took to install Lektor? I can't help you uninstall Lektor if I don't know what you did to install it. (I know you said you "installed lektor manually", but I don't know what that _means_. Can you tell me _exactly_ what you did?)

**Comment by item4** [comment]
Oh, I add some info.

I am use macOS and I installed lektor (maybe v1) via official *.dmg file from website. I want to uninstall it.

```console
$ which lektor
/usr/local/bin/lektor
$ lektor
Traceback (most recent call last):
  File "/usr/local/bin/lektor", line 7, in <module>
    from lektor.cli import main
  File "/usr/local/lib/lektor/lib/python2.7/site-packages/lektor/cli.py", line 3, in <module>
    import json
ImportError: No module named json
```

**Comment by yagebu** [comment]
Since this relates to the GUI bundle on macOS that was removed, I'm closing this issue.
