### ISSUE TITLE
Cannot access the Admin (Python 3.5 and 3.6)

### ISSUE THREAD

**Issue by jeremy886** [lektor/lektor#336]
I'm installing Lektor again during the holiday. However, after installation, I couldn't access the Admin page either by clicking at the Pencil or typing in http://localhost:5000/admin/root/edit. 

Possible error messge:
/Users/apple/workplace/py35/lektor/lektor/admin/modules/serve.py:89: ResourceWarning: unclosed file <_io.BufferedReader name='/Users/apple/Library/Caches/Lektor/builds/4455e1397a88f878c9fc317ecd86f208/index.html'>
  edit_url=posixpath.join('/', request.script_root, 'admin/edit'))

**Comment by aavrug** [comment]
It might be the ES6 issue. Just inspect into console, hopefully that will help.

**Comment by singingwolfboy** [comment]
@jeremy886 that error message should be resolved by #339.
