### ISSUE TITLE
document body.toc, sort_key

### ISSUE THREAD

**Issue by vindarel** [lektor/lektor#35]
In getlektor.com sources, I see that the menu of the left, representing the toc of the documentation, is built with a few tricks: 

```
      {% if this.body.toc %}
```

and a search of all pages, where I guess the `sort_key` data in a content.lr file is responsible for the ordering

```
title: Quickstart

---
summary: Covers how to create a very basic website project with Lektor and run it.

---
sort_key: 60

---
body:
```

in `doc-page.html`:

```
    {% for child in docs.children recursive %}
      <li{% if this._path == child._path %} class="active"{% endif
          %}>{{ get_doc_link(child) }}
        {% if this.is_child_of(child) %}
        <ul>{{ loop(child.children) }}</ul>
        {% endif %}
    {% endfor %}
```

Are `sort_key`, `this._path`, `doc.children`, `this.body.toc` all jinja features ? If not, more doc is welcome, or that's an idea for a next blog post :)

thanks !

**Comment by mitsuhiko** [comment]
The `.toc` comes from a plugin that the website uses. The sort key is used for the default ordering that is set up in the model for it and freely configurable.  There is nothing particularly special about it _yet_.

**Comment by mitsuhiko** [comment]
This plugin adds the `.toc` for the markdown output: https://github.com/lektor/lektor-website/tree/master/packages/markdown-header-anchors

**Comment by vindarel** [comment]
Thanks, a mystery solved. And I see you put it in the official list of plugins.
