### ISSUE TITLE
Tests failing for master branch

### ISSUE THREAD

**Issue by tariquesani** [lektor/lektor#352]
Have attached the complete output but typically getting errors similar to 

`import file mismatch:
imported module 'data.clientmodule_test' has this __file__ attribute:
  /home/tariquesani/Projects/lektor/venv/lib/python2.7/site-packages/astroid/tests/testdata/python2/data/clientmodule_test.py
which is not the same as the test file we want to collect:
  /home/tariquesani/Projects/lektor/venv/lib/python2.7/site-packages/astroid/tests/testdata/python3/data/clientmodule_test.py
HINT: remove __pycache__ / .pyc files and/or use a unique basename for your test file modules
 ERROR collecting venv/lib/python2.7/site-packages/astroid/tests/testdata/python3/data/suppliermodule_test.py 
`

[testreport.txt](https://github.com/lektor/lektor/files/753733/testreport.txt)

**Comment by coreygrunewald** [comment]
This is the same thing I saw locally, however, the CI build for my PR (https://travis-ci.org/lektor/lektor/jobs/198731896) doesn't see the same issue.

**Comment by singingwolfboy** [comment]
This looks like a problem with [`asteroid`](https://github.com/PyCQA/astroid), which is a part of [`pylint`](https://pylint.org/). You can run the tests without pylint, if you want: just delete the [`pytest.ini`](https://github.com/lektor/lektor/blob/master/pytest.ini) file and run `make test` again.

**Comment by tariquesani** [comment]
May be I am doing something wrong but deleting  [`pytest.ini`](https://github.com/lektor/lektor/blob/master/pytest.ini) did not change anything. I tried after removing the  __pycache__  and .pyc files.

**Comment by singingwolfboy** [comment]
@tariquesani hmm, that's odd. Are you able to reproduce this with a new virtualenv? (If you're not familiar with virtualenv, it's [an installable tool for Python 2](https://pypi.python.org/pypi/virtualenv), which has been [pulled into the Python standard library in Python 3](https://docs.python.org/3/library/venv.html).) Try creating a new virtualenv, installing Lektor's dependencies into that virtualenv, and then running the tests. If you can still reproduce the issue, please attach a traceback of all the commands you ran, from creating the virtualenv to getting the error.

**Comment by tariquesani** [comment]
OK, let me try with the new virtualenv. Thanks for being so helpful.

**Comment by tariquesani** [comment]
Not much difference. I am on a default install of Ubuntu 16.04. Here is what I did 

```
git clone https://github.com/lektor/lektor
cd lektor
virtualenv venv
. venv/bin/activate
pip install --editable .[test]
make test
```
and ended up with the output in this file - 
[testreport.txt](https://github.com/lektor/lektor/files/770159/testreport.txt)

**Comment by singingwolfboy** [comment]
@tariquesani If you run `which python` and `python -V`, what output do you get?

**Comment by tariquesani** [comment]
@singingwolfboy 
/home/tariquesani/projects/tmp/lektor/venv/bin/python
Python 2.7.12

**Comment by singingwolfboy** [comment]
Ah, I see the problem. The README says to create the virtualenv inside of the `lektor` directory, but if you do that, then pytest will pick up all the files inside the virtualenv and try to test them as well. If you create the virtualenv _outside_ of the `lektor` directory, then most of the tests pass -- except for two, which seem to be failing on Ubuntu locally. I'm not sure what's going on with those tests, but I'll look into it in the next few days.

Could someone else please verify that removing the `venv` directory and using a different virtualenv outside of the `lektor` directory works correctly? If so, I would love a pull request updating the install documentation.

**Comment by tariquesani** [comment]
Moving  `venv` outside indeed did the trick. Infact all 164 tests passed for me!

Bah! I should have figured that one out myself - the error messages indicates that. Hmmm... hindsight is always 20/20
