### ISSUE TITLE
Lektor can't find imagemagick on Windows

### ISSUE THREAD

**Issue by cprecioso** [lektor/lektor#362]
I'm using the latest Windows 10, and I've tried installing lektor and imagemagick through chocolatey, scoop and manual install, but when I build my website, thumbnails don't work, it says it can't find imagemagick.

I've tried it in a couple of Windows 10 PCs and in a vanilla one, and it hasn't worked in any.

**Comment by tariquesani** [comment]
Can anyone who uses Windows help?

**Comment by iancarnation** [comment]
I just solved this on my Win7 setup..noticed there was no convert.exe file in the ImageMagick directory as called from imagetools.py. That led me to find out that the "`magick`" command has replaced the "`convert`" command in the new version of IM. 

Fix: 
- re-install ImageMagick with the binary from http://www.imagemagick.org/script/download.php
- there is a checkbox to "Install legacy utilities (e.g. convert)" in the Additional Tasks dialog of the installer process - check it!

Sources:
https://www.imagemagick.org/discourse-server/viewtopic.php?t=29582
http://imagemagick.org/script/porting.php#cli

**Comment by iancarnation** [comment]
I may submit a pull request after testing a fix for this in imagetools.py.. haven't done a PR before but this looks like a fun little opportunity :)

**Comment by andygarfield** [comment]
Any updates on this?

**Comment by iancarnation** [comment]
No time for an official fix from me, unfortunately - I'd recommend just using the workaround method :)

**Comment by xlotlu** [comment]
this was closed in #434
