### ISSUE TITLE
Use original image when Lektor can't find Imagemagick

### ISSUE THREAD

**Issue by cprecioso** [lektor/lektor#363]
It'd be great if Lektor could use the original image when the template has set `.thumbnail(w,h)`, but there's no Imagemagick installed (or can't find it). Maybe that option could be set behind a flag or in the configuration file, so it doesn't yield unexpected behaviour when it's absolutely neccessary to resize that image.

If none of this is possible, there could be an option in the `thumbnail` method that said that it would be ok to fallback to the original image.

My use case for this is that the build server does have imagemagick, but the person editing it doesn't neccessarily, or can't be correctly located (as in #362).

**Comment by xlotlu** [comment]
Design decision needed. I personally don't consider this an enhancement, and lean towards failing loudly when imagemagick is not found. Explicitly requesting a thumbnail and getting something else is not much of a feature. Also, #362 which prompted this and was the real issue has been solved.

**Comment by nixjdm** [comment]
I agree with @xlotlu. Lektor shouldn't do this by default, because then there would surely be many instances of people not being careful and building sites without realizing their images appear very different than they intended.

I'm sceptical of the use case for an option that does this as well. Even having the option seems like an opportunity for confusion and bad surprises. Hopefully with 362 resolved this is a non-issue, but if not, I'm inclined to disagree.

**Comment by dairiki** [comment]
An option would be to have `.thumbnail()` issue a console error/warning message, but return a `jinja2.Undefined` instance.  This would allow for explicit fallback handling in the template, should the user want.  E.g.
```html+jinja
<% set thumb = image.thumbnail()|default(image) %>
<img src="{{ thumb|url }}">
```

(I'm not positive, but from brief inspection of the current code, it appears that currently in this case, `.thumbnail()` returns a valid Thumbnail instance, so there is no sign of failure available by inspecting the return value.  The failure isn't reported until later when the attempt is made to build the thumbnail artifact.)

**Comment by nixjdm** [comment]
That seems fine to me. I'll make a new ticket for it and quote this.
