### ISSUE TITLE
Duplicate directories with `rstrip("/")` appended to name are sent to S3

### ISSUE THREAD

**Issue by jimrybarski** [lektor/lektor#364]
I have a static site hosted on S3. I've noticed there are duplicate directories for each blog post, but with `.rstrip("/")`appended to them. For example, `www.example.com/whatever/` hosts the same content as `www.example.com/whatever.rstrip("/")/`. Strangely, these duplicate directories do not exist on my local machine after building the site.

**Comment by singingwolfboy** [comment]
I also have a static site hosted on S3, and I don't have this problem. Can you find a reproducible test case for this issue? Otherwise, I don't think we'll have much luck tracking it down.

**Comment by tariquesani** [comment]
Tried it. Cannot replicate

**Comment by tariquesani** [comment]
Is this still a problem? Can you give steps to reporduce?

**Comment by jimrybarski** [comment]
No. I rebuilt my blog from scratch and the problem no longer occurs - the only difference was that I limited how much I modified one of the templates. So I suspect that I just deleted something that led to a parsing error, but I doubt I'll be able to reproduce it. Sorry for the trouble.
