### ISSUE TITLE
Sometimes before-build-all isn't triggered before after-build

### ISSUE THREAD

**Issue by emilyalbini** [lektor/lektor#365]
This was reported to me in pietroalbini/lektor-minify#1 and while I can't reproduce it I think it's an issue in Lektor itself.

My plugin uses the `after-build` event to do everything, but it used to use the `before-build-all` event to initialize some state (now it initializes everything in the first event). @tariquesani found that when he was using the development server the plugin was crashing because the state wasn't initialized. While I can't reproduce the issue at all, after moving everything in `after-build` he stopped having issues.

Is it possible that the `before-build-all ` event isn't guaranteed to be executed? I looked at the code and it doesn't seem so, but this bug showed up...

**Comment by tariquesani** [comment]
As far as I have tested `before-build-all` is getting executed when you build all. Closing this issue.
