### ISSUE TITLE
asseturl's relative paths break down on 404 pages

### ISSUE THREAD

**Issue by anemitz** [lektor/lektor#368]
Let's say you have a global `templates/layout.html` which includes your stylesheet as follows:

`<link rel="stylesheet" href="{{ '/static/dist/style.css'|asseturl }}>"`

You also have a `templates/404.html` which extends from `layout.html`.

If you try and access `http://localhost:5000/some-invalid-path/` you'll be greeted with a well styled 404 page.

If you try and access `http://localhost:5000/some-invalid-path/and-another-level-deeper/` you'll get a 404 page which can't load the `/static/dist/style.css` file since `get_asset_url` is going to generate the path `../static/dist/style.css` which will try and get the css from `http://localhost:5000/some-invalid-path/static/dist/style.css` instead of `http://localhost:5000//static/dist/style.css`

![screenshot 2017-03-17 14 02 46](https://cloud.githubusercontent.com/assets/437264/24058959/785a2a28-0b23-11e7-9c92-c1b1acc090ac.png)

One way to fix this is to change https://github.com/lektor/lektor/blob/master/lektor/context.py#L29 to 
```
    return '%s?h=%s' % (
        ctx.source.url_to('!' + asset.url_path, absolute=True),
        info.checksum[:8],
    )
```
Is there a better way to fix this?

**Comment by mitsuhiko** [comment]
You can set the url style to absolute in the config. Relative links cannot work on 404 pages.
