### ISSUE TITLE
Accessing admin after deployment

### ISSUE THREAD

**Issue by MaxHalford** [lektor/lektor#373]
Hello,

I have deployed a Lektor website with GitHub pages and now I would like to access the administration interface. However, when I go to [https://theblueparrot.github.io/ziboinboin.com/admin](https://theblueparrot.github.io/ziboinboin.com/admin) I get a 404.

I couldn't find any documentation on this; my question is thus: is the administration panel accessible after deployment?

Best regards.

**Comment by wgwz** [comment]
That's not going to work with github pages. The github pages deploy is only serving the static html files that get built by Lektor.

**Comment by davidism** [comment]
You're going the wrong direction: you're supposed to use the admin to write and deploy, not deploy then use the admin.

**Comment by MaxHalford** [comment]
I see, my bad; it perfectly makes sense now that I think about it.
