### ISSUE TITLE
Where is the macOS dmg?

### ISSUE THREAD

**Issue by svandragt** [lektor/lektor#382]
The Lektor website points to https://github.com/lektor/lektor/releases to get the Desktop Application but the last version of the dmg file was released as part of Lektor 2.3.

Is the GUI application still supported and if so how do I get it without compiling / packaging it?

**Comment by nixjdm** [comment]
Hi @svandragt, the dmg file for 3.0 / 3.0.1 is not at right now. I'm working making it and let you know (and close this issue) when I've uploaded it.

One of my top priorities is to streamline the release process so this delay doesn't happen in the future, and to make Lektor as accessible as possible. I do specifically want to keep the dmg files supported.

**Comment by nixjdm** [comment]
FYI, I'm making progress on this, sorry it's taking a while. I've set up a Mac with a developer account and done some needed cleanup of the makefiles (that were broken). I'm not quite done yet but I wanted to tell you I haven't lost site of this. Some documentation will be made after this.

**Comment by svandragt** [comment]
It's much appreciated and I think one of lektors strengths compared to similar solutions - especially as it combines nicely with a post editor marketing wise.

The package also makes it easy to update

**Comment by nixjdm** [comment]
@svandragt your long wait is over! https://github.com/lektor/lektor/releases

Enjoy, and please continue to post issues is you spot problems. Thanks!
