### ISSUE TITLE
install.sh fails on Python 3

### ISSUE THREAD

**Issue by enkore** [lektor/lektor#385]
```py
Traceback (most recent call last):
  File "<stdin>", line 139, in <module>
  File "<stdin>", line 127, in main
AttributeError: module 'urllib' has no attribute 'urlopen'
```

**Comment by singingwolfboy** [comment]
Thanks for reporting this! It should be fixed by https://github.com/lektor/lektor-website/commit/ca22f06a5bb673951d132571a476d1d21a904559. Can you give it another try, and let me know if it works this time?

**Comment by enkore** [comment]
Fixed it, thanks!
