### ISSUE TITLE
this.title doesn't yeild anything in quickstart blog

### ISSUE THREAD

**Issue by smth** [lektor/lektor#386]
The blog.html template includes `{% block title %}{{ this.title }}{% endblock %}`, but this leaves the title blank.

**Comment by tariquesani** [comment]
Show us your code.

**Comment by smth** [comment]
It's what you get if you run the quick-start, I think it's the same as the code in this repo. So:

- https://github.com/lektor/lektor/blob/master/example/templates/blog.html
- https://github.com/lektor/lektor/blob/master/example/models/blog.ini

blog.ini needs the below added, if it is to work as expected.

```
[fields.title]
label = Title
type = string
```

As well as a `title` in https://github.com/lektor/lektor/blob/master/example/content/blog/contents.lr

**Comment by nixjdm** [comment]
@smth You're right, I see it too. I think you're fix is appropriate as well. Could you submit a pull request? I can if you want.

**Comment by smth** [comment]
Can do. Would it be those files under /example that need editing? Is that where the files created with the quickstart are derived?

**Comment by nixjdm** [comment]
Almost.

/example is an option for developers to test code against without a quickstart, and it needs changed too. Quickstart itself builds from code in lektor/quickstart-templates/project that looks very similar. So you'll need to make the same changes in both lektor/quickstart-templates/project/content/blog/contents.lr.in and example/content/blog/contents.lr.in, and then also in the paired model files.

Sound alright?
