### ISSUE TITLE
Does admin need extra npm modules? Use of deprecated features?

### ISSUE THREAD

**Issue by madebr** [lektor/lektor#387]
Hey, I'm no npm expert, but the admin module does not work in current git for me.

I had to install the following modules in `lektor/admin/node_modules` in order for the admin menu to appear.

- fbjs
- setimmediate
- object-assign
- strict-uri-encode

That way, all Uncaught Exceptions at load time disappear.
The Developer Console does still show some warnings about deprecated React features + an Uncaught TypeError (Cannot read property '_currentElement' of null)

**Comment by nixjdm** [comment]
What node and npm version are you using?

I'm trying to reproduce your error, but I am not getting any console errors in admin on the master branch. Checking `npm list` and that node_modules folder, I have all of your missing dependencies installed. fbjs for example is a dependency for react, so it should be installed if react is installed. Did you run `make build-js` as in the [README](https://github.com/lektor/lektor/blob/master/README.md)?

Thanks!

**Comment by madebr** [comment]
Hey,

I installed the extra packages because I saw an error about missing modules.
Anyway, I removed node_modules from the admin folder and re-executed the steps in the README file. (fbjs is indeed a dependency of react)

I can still reproduce the error. The first Uncaught Error is about not finding "strict-uri-encode" (some page also have an error about missing "setimmediate").

I have copy pasted the error from the Developer Console to a [gist](https://gist.github.com/madebr/18e6d3f704bff2a4aee810478c5fc821#file-chrome-console-developer-output). The output of [npm list](https://gist.github.com/madebr/18e6d3f704bff2a4aee810478c5fc821#file-npm_list) can also be found there.



My versions are:
```
$ node --version
v4.7.3
$ npm --version
2.15.11
$ cat /etc/fedora-release 
Fedora release 24 (Twenty Four)
$ google-chrome-stable --version
Google Chrome 59.0.3071.104 
```

**Comment by nixjdm** [comment]
I have reproduced your error with your versions of node and npm. The four packages you listed all do not get installed at with this node version on `make build-js`. When I tried it again with node=8.1.2 and npm=5.0.3. I do not have any `Module not found` errors anymore on `make build-js`. Could you please try upgrading node and confirming that this issue disappears for you?

FWIW, I do not know the precise version(s) of node that are compatible with Lektor, but the latest (8.1.2) seems to work for me. I'd love more data points, and then to mark compatible versions in the README.

**Comment by nixjdm** [comment]
I'm pretty sure I've reproduced your error and it can be fixed as per my previous comment, so I'm closing the ticket. If that is not the case, let me know and I can reopen it.

**Comment by ikus060** [comment]
Could we add a warning or error message if the npm version is too old ?? Cause I'm facing the same issue using `npm`package from my distro.

**Comment by nixjdm** [comment]
Yes, in a number of ways. I've been thinking about some options, but I'll go ahead and post a general ticket for it.
