### ISSUE TITLE
Simple debug of the templates?

### ISSUE THREAD

**Issue by torian257x** [lektor/lektor#393]
I am coming from a none python background

I have the docs from here

http://jinja.pocoo.org/docs/dev/templates/#pprint

none of this gives me any useful information:

```
{% for image in this.attachments.images %}
<div>{{image|pprint(true)}}</div>
{% endfor %}

{% for image in this.attachments.images %}
<div>{{image|pprint}}</div>
{% endfor %}
```

it only returns

`<Image model='none' path=u'/blog/first-post/aadv3ae_700b.jpg'>`

is there no easy way to see what I can do on the image object?

yes yes, the docs. The docs have very little in them. Say: I want just the filename.
say I want the full directory path

just generally, how to debug / inspect elements?

**Comment by nixjdm** [comment]
There is no way I know of to simply list all available kinds of data and filters on a particular object from the templates. The objects are Python objects though, so you can do things like `{{ obj.__dict__ }}`, dot chaining methods and attributes, to delve into  what is available on that particular object.

Like you said, there is more in the docs ;) I don't think the docs have consolidated what you're looking for all in one place though. For instance, you may write `{{ img|url }}` for the image's url or `{{ img._slug }}` for just it's slug (the last part of the url). I want to direct you to the following pages in particular. Hopefully what you're looking for is in there. If you need more help on how to find what you're looking for or generally use Lektor, please visit https://gitter.im/lektor/lektor and ask your question there.

- https://www.getlektor.com/docs/api/db/system-fields/
- https://www.getlektor.com/docs/templates/imageops/
- https://www.getlektor.com/docs/api/templates/filters/
