### ISSUE TITLE
Nested flows?

### ISSUE THREAD

**Issue by torian257x** [lektor/lektor#394]
say I want to give the content creator the possibility to create content with bootstrap

So I guess I want him to create a bootstrap row. I would assume this is best done via a flow block

and then inside that bootstrap row, I want him to add columns, so i guess that would be another flow block. And then inside the bootstrap column, I want him to add a text / image block.

Is that even possible?

**Comment by nixjdm** [comment]
Yes, this is possible in Lektor. Take a look at [this example](https://bitbucket.org/terminal_labs/tl-lektor/src/master/flowblocks/subnav-item.ini). Note the `[fields.images]` has `type = flow`, yet this file is a flow model itself.
