### ISSUE TITLE
image attachments - avoid lose random group. How to assign images to categories / groups?

### ISSUE THREAD

**Issue by torian257x** [lektor/lektor#396]
i want to be able to upload a "featured image"
now lektor lets me upload lose random groups of images, but there seems to be no way for me to say, have 10 images attached to a page, and then easily identify the featured image.

Is it possible to upload an image for a flow block? e.g. a featured image flow block, and the uploaded image gets available for that?

say I have:
color categories

red, blue, green

each category has a couple images

how can I easily assign an image to a category?

**Comment by tariquesani** [comment]
Take a look at how I have implemented featured image 

https://github.com/tariquesani/tariquesani.net/blob/master/models/blog-post.ini

**Comment by torian257x** [comment]
awesome thanks a lot!

**Comment by nixjdm** [comment]
Seems like this question is answered!
