### ISSUE TITLE
Make Lektor's GUI generator agnostic?

### ISSUE THREAD

**Issue by davidbgk** [lektor/lektor#4]
More a feature request/discussion: how hard is it to use the GUI on top of another static website generator?

I'm guessing that a lot of people already have their own generators in place but would be very happy with the admin to ease the file generation :).

**Comment by mitsuhiko** [comment]
The GUI uses the model system of Lektor to render out the admin stuff and that also requires good support for writing back the files.  I don't think that works particularly well without dragging in the model and `.lr` content file system.

**Comment by mitsuhiko** [comment]
Going to close this :)
