### ISSUE TITLE
Link back to source file on github?

### ISSUE THREAD

**Issue by p-hennessy** [lektor/lektor#409]
Wondering if i'm missing something; is there a way to link a generated page back to the markdown file that was used to produce it? i assume one would have to at least prepend the url with the right github repo 

Thanks!

**Comment by davidism** [comment]
The https://www.getlektor.com website does this at the bottom of each page, the source is at
https://github.com/lektor/lektor-website. Specifically, it builds the link for the current page in the layout template: https://github.com/lektor/lektor-website/blob/master/templates/layout.html.

**Comment by p-hennessy** [comment]
Thanks!
