### ISSUE TITLE
Field Order Sometimes Wrong

### ISSUE THREAD

**Issue by mitsuhiko** [lektor/lektor#41]
The fields when added to a page sometimes seem to be in correct.

**Comment by nixjdm** [comment]
Do you mean the order of the fields in admin? I think I need a little more detail on this if it's still an issue. They've been reliable for the things I've done, but I might not have done what caused this for you, or didn't notice it.

**Comment by nixjdm** [comment]
I'm marking this as on-hold pending the outcome of #457.

**Comment by nixjdm** [comment]
Since we've had further discussion on #457 / #458, I'm removing the on-hold label.

**Comment by yagebu** [comment]
This still lacks a reproduction is almost certainly fixed now (this probably happened when incorrect keys where used in React, which shouldn't be the case for the fields now)
