### ISSUE TITLE
Deployment fails if site directory on different filesystem from temp directory

### ISSUE THREAD

**Issue by jgoodson** [lektor/lektor#415]
I have my Lektor site on a network-mounted filesystem. When deploying, Lektor creates a empty git repo and fills this with the generated site cache in my Lektor site directory (on my network share), and fills it from the OS defualt cache directory (on my hard drive). In the link_artifacts() function in publisher.py the last link calls link() to either link or copy files depending on whether os.link is found. 

The problem is that os.link() does not work on different filesystems. Attempting to publish with this setup results in a "OSError: [Errno 18] Cross-device link". There are several other places in this function where it switches to shutil functions instead of os on Exception. Since shutil.copy is apparently an acceptable alternative to os.link, I would think that replacing:

```
link(full_path, dst)
```
with
```
try:
    link(full_path, dst)
except OSError:
   shutil.copy(full_path, dst)
```
would fix the issue where os.link fails because of a different-filesystem issue. Modifying the source in this way fixed my issue.

See https://github.com/lektor/lektor/pull/416

**Comment by nixjdm** [comment]
Thank you very much for this explanation with the pull request!
