### ISSUE TITLE
ghpages deploy via https is not working on python 3

### ISSUE THREAD

**Issue by goanpeca** [lektor/lektor#418]

**Comment by nixjdm** [comment]
Hey @goanpeca, do you get an error you can report? The tests for ghpages aren't failing, so I'm wondering if we can improve them to catch this bug, and then fix the bug. That would allow me to more easily see it too, since I don't have any ghpages of my own set up.

**Comment by goanpeca** [comment]
@nixjdm I ha da project all env variables set up and travis was ismply saying invalid username or password. I switched to py27 and it just worked, I can look into it more later this week

**Comment by ericmjl** [comment]
@nixjdm I'd like to confirm that this also fixed the issue that I had with authentication (Issue #464).

It's taken me 2 days to debug this, quite a bit too long for a bug like this, but I guess understandable given the migration headaches between py2k and py3k.

Please let me know if there is something I can do to help here.

**Comment by rlaverde** [comment]
I can confirm this issue too:

This is not only  failing in Travis, trying to deploy it locally also  fails:
`lektor deploy production --username rlaverde --password TOKEN`

Changing this [line](https://github.com/lektor/lektor/blob/master/lektor/publisher.py#L543) (removing the encode) fix this issue (but I bet that will break python2.7).

`return rv if rv else None`
