### ISSUE TITLE
Install on Windows and Python3 fails - no module named _winreg

### ISSUE THREAD

**Issue by dr-leo** [lektor/lektor#422]
In Python3 it is simply called winreg. Happy to send the traceback if needed.

**Comment by rlaverde** [comment]
I think this isn't a Lektor bug, instead a Flask bug, which Flask version are you using? try updating it

**Comment by dr-leo** [comment]
I've update flask to no avail:



C:\users\leo\documents\dev\pysdmx>@powershell -NoProfile
-ExecutionPolicy Byp
ass -Command "iex ((new-object
net.webclient).DownloadString('https://getlektor.
com/install.ps1'))
Traceback (most recent call last):
  File "<string>", line 12, in <module>
ImportError: No module named '_winreg'




Unfortunately, the traceback is not very informative: What module?




Am 14.08.2017 um 03:54 schrieb Rafael Laverde:

**Comment by doowonee** [comment]
1. get the script from https:/https://getlektor.com/install.ps1
2. replace `_winreg` to `winreg` in the file though text editor.
3. run power script as an admin and type `Set-ExecutionPolicy RemoteSigned`.
3. `iex install.ps1` then done!

**Comment by dr-leo** [comment]
Thanks for these instructions. I'll consider trying this out or looking
into an install on Linux via Docker to avoid such fiddling.


So do we agree that this is a Lektor bug? Do you intend to fix it? Then
you may well close this issue.


It should arguably be fixed by something like


try:

    import _winreg

except Import Error

    import winreg as _winreg



Am 16.08.2017 um 05:56 schrieb the1900:

**Comment by nixjdm** [comment]
I believe I've fixed this in https://github.com/lektor/lektor-website/commit/beb5c3d0f094b89ba590a0857f330ebf958524a7 . https://getlektor.com/install.ps1 is now updated.

I'm going to close this now as fixed, but if it's not working for you @dr-leo or you have another problem let us know. Thanks for finding it.
