### ISSUE TITLE
Assets beginning with an underscore are ignored

### ISSUE THREAD

**Issue by danielknell** [lektor/lektor#423]
I tried to add a netlify `_redirects` file to my assets folder and it was ignored at build time, removing the underscore causes it to be copied.

I am assuming the python convention of underscore prefixes denoting something that is not public is being applied to all files?

**Comment by nixjdm** [comment]
I'm quoting this in the older #265, and marking this as a duplicate. Thanks @danielknell  for verifying that the underscore is a problem.
