### ISSUE TITLE
Install script fails on Windows and Python3 - json file must be of type str not bytes

### ISSUE THREAD

**Issue by dr-leo** [lektor/lektor#425]
So yet another Python3 bug. I give up as I lack the time to go through any number of bugs going further. The docker way seems more interesting anyway even though it may have its own challenges.

Despite the issue title, this seems to be a classical 2to3 issue, unrelated to Windows or any other OS. 

Btw: there is even a syntax error in the windows command to be copied from the Lektor installation page. When omitting the final set path command, it works though. There is still some work to do. 

Here's the traceback for reference:
   Installing at:
   C:\Users\leo\AppData\Local\lektor-cli

Continue? [Yn] y
Traceback (most recent call last):
  File "<string>", line 149, in <module>
  File "<string>", line 135, in main
  File "C:\Users\leo\anaconda3\lib\json\__init__.py", line 268, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "C:\Users\leo\anaconda3\lib\json\__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'

**Comment by vanadium23** [comment]
@nixjdm dive into this issue and can't reproduce this error, but there is another interesting bug on install.ps1 from getlektor website.

If you make virtualenv and install pyyaml everything will be fine:
```
python -m venv .venv
.\.venv\Scripts\Activate.ps1
pip install pyyaml
```

but if you install lektor than:
```
python -m venv .venv
.\.venv\Scripts\Activate.ps1
pip install lektor
....
collecting pyyaml
.....
UnicodeDecodeError
```

**Comment by xlotlu** [comment]
I couldn't reproduce this. Successfully installed on py3.7 / win7. Leaving it open for now, but should probably be closed.

**Comment by andoresuperesu** [comment]
Can't reproduce either on py3.7/ win10. I'll ask anaconda users in local python comunity to check if it is anaconda specific.

**Comment by xlotlu** [comment]
Well, it was a while ago. It might have been a bug in that old lib version.

**Comment by vanadium23** [comment]
Also can't reproduce anymore.
