### ISSUE TITLE
Add Git script to run linter before pushing

### ISSUE THREAD

**Issue by nixjdm** [lektor/lektor#428]
@coreygrunewald had a great suggestion [here](https://github.com/lektor/lektor/pull/354#issuecomment-278771962) to add a git pre-push script. This issue is for making that script that runs the js linter before a push such that it displays any error output and ends the push if there is a problem. Instructions should also be added to the README for how to symlink this to `.git/hooks/pre-push` in the instructions section for doing development on Lektor.

**Comment by vanadium23** [comment]
@nixjdm I'd like to make pr, can you assign issue to me?

**Comment by jab** [comment]
In case you haven't seen, http://pre-commit.com is a great way to automate adding and running best-of-breed git pre-commit hooks, both locally and as part of the CI build.

**Comment by vanadium23** [comment]
@jab yeah, agree (:

**Comment by nixjdm** [comment]
@vanadium23 Github won't let me assign things to people not in the organization (a policy I question), but I can definitely informally give this to you! Please go right ahead.

I'm open to this being either pre-commit or pre-push. Doesn't make a big difference to me. Perhaps devs would find pre-commit less annoying than pre-push.

@vanadium23 Just the linter is fine for this issue, but if you have ideas for similar handy hooks, I'm all ears. For instance a trailing-whitespace commit block is pretty standard and could be added.
