### ISSUE TITLE
checkbox ouput error?: [u'option, option, option ']

### ISSUE THREAD

**Issue by andrearicci** [lektor/lektor#441]
Hello,
in my **project.html** I have:
 `      <tr>         <th scope="row">Phase</th>         <td>{{ this.phase }}</td>       </tr>`
while in my **project.ini**:

> [fields.phase]
> label = phase
> type = checkboxes
> choices = competition, schematic project, final plans, construction documents, artistic supervision, construction administration
> choice_labels = competition, schematic project, final plans, construction documents, artistic supervision, construction administration
> width = 1/4

but in the ouput I get unexpected
>**Phase:** [u'schematic project', u'final plans', u'construction documents', u'artistic supervision']

That was of course the sample of a specific project, but I have the same problem for every single checkbox field.
Any help?
Thank you

**Comment by andrearicci** [comment]
here is my lektor project folder
[ar-lektor.zip](https://github.com/lektor/lektor/files/1298784/ar-lektor.zip)
(I removed the images to make it lighter)
I work with lektor 3.01, python 2.7.13 on win7/64
Website shold go soon online http://andrearicci.it
Here we go: you can se the ouput error here http://andrearicci.it/projects/palazzo-italia/ in the "role", "phase" and "type" fields - it's in any "project" layout.

**Comment by xlotlu** [comment]
@andrearicci sorry, I didn't bother to open the zip and test the project. Can you please tell us if this is still an issue (and if the old code is still a valid testcase)?

**Comment by andrearicci** [comment]
Hi, I've already fixed it with the help of someone else. Just let me write here the suggestion if someone else has the same problem. I think I had the answer on a jinja forum.
(Notice: I just followed the instructions, I don't understand what I did.)
in the template **project.html**
`{{ this.phase }}`
needs to be changed to
`{% for item in this.phase %}{{ item }}{% if not loop.last %}; {% endif %}{% endfor %}`
Thank you for you interest.
