### ISSUE TITLE
ability to set a build directory in the project

### ISSUE THREAD

**Issue by andrearicci** [lektor/lektor#446]
I would like the ability to set the build directory in the project file, so not to have to search it in the filesystem. 
Of course if not set it could be the default location, and it can be changed as usual when building if a `--output-path` is given.
Thank you

**Comment by runfalk** [comment]
I think this is pretty useful for continuous integration cases. It makes it easier to figure out where the build directory is. It's also beneficial when disk space is sparse on one partition (though that can be solved with symlinks on Linux and macOS).

If `--output-path` is added I think it makes a lot of sense to add a configuration option to `<project>.lektorproject` as well. Absolute paths are a bit non-portable between Windows and UNIX-like systems, but relative paths could be very useful.

If allowing this option there would also be a need for santity checks like:
- Is this a Lektor build directory?
- Is this directory a parent directory of the project?

**Comment by andrearicci** [comment]
i personally use (and find useful) a `_BUILD` directory inside the project, the underscore to make the directory transparent to the buoil process itself. 
This could be a possible default.

**Comment by xlotlu** [comment]
I'd really like to see this happen too.

Edit: this has already happened in https://github.com/lektor/lektor/pull/695/ and is documented: https://www.getlektor.com/docs/project/file/.

**Comment by andrearicci** [comment]
Thank you xlotlu
