### ISSUE TITLE
Update Node packages

### ISSUE THREAD

**Issue by nixjdm** [lektor/lektor#449]
Time for another round of updating our packages as much as we can without breaking anything. This should regularly be done to keep compatibility with our dependencies. If we discover an update would break something, that can be fixed here or we can put that particular package update and fix together in a separate ticket. Ample testing and care should be taken with this issue. I'd like to have this pulled into master not long after 3.1 is released so we have plenty of time to test it on master before reaching 3.2.

Suggested by: https://github.com/lektor/lektor/issues/430#issuecomment-328800515

on-hold because of #457

**Comment by rlaverde** [comment]
Using a tool for monitor dependencies will prevent them for getting outdated.

I don't know too much about the js/node world, but after some google searching I found https://greenkeeper.io/ and https://david-dm.org/

**Comment by nixjdm** [comment]
Since we've had further discussion on #457 / #458, I'm removing the on-hold label.

**Comment by runfalk** [comment]
This has been done for now I think.
