### ISSUE TITLE
Server : live reload ability

### ISSUE THREAD

**Issue by andrearicci** [lektor/lektor#453]
wish: live reload ability in the server.
As of today I have always to click reload on the browser to check my modifications.

**Comment by nixjdm** [comment]
Are you talking about the preview tab in admin, the live website view (not in admin), or both?

**Comment by andrearicci** [comment]
live website view - at the moment I have to click on reload button of the browser, it is not autmatically reloaded at any change as other softwares do (hugo, atom-live-server plugin in atom etc)

**Comment by tariquesani** [comment]
Doesn't `lektor build --watch` cut it?

**Comment by andrearicci** [comment]
@tariquesani wow, yes it does, thank  you.
But at this point I'm a bit confused: that's what I was expecting with the `server` command. At this point I hardly see the need of it (I tested `lektor server --watch` with an error response).
Joining this with the issue #446 my wish is to have an easy to set-up build directory (in the project file?), and maybe merge `server ` and `build ` commands to avoid confusion.
Is this this confusing only for windows users, maybe?
Anyway at least the option should be added to the `--help` command:
 ```
 The lektor management application.

  This command can invoke lektor locally and serve up the website.  It's
  intended for local development of websites.

Options:
  --project PATH   The path to the lektor project to work with.
  --language TEXT  The UI language to use (overrides autodetection).
  --version        Show the version and exit.
  --help           Show this message and exit.

Commands:
  build              Builds the entire project into the final...
  clean              Cleans the entire build folder.
  content-file-info  Provides information for a set of lektor files.
  deploy             Deploy the website.
  dev                Development commands.
  plugins            Manages plugins.
  project-info       Shows the info about a project.
  quickstart         Starts a new empty project.
  server             Launch a local server.
```
Thank you.

## EDIT: 

after a bit of testing here's why you need the server:

my link internally are all pointing to directories, **I need a server to serve up the relative index.html** file, elsewhere I only reach a directory.
So no, `build --watch` is sadly not an option. 
Adding a `server --watch` would better fill my needs.
Thank you again

**Comment by tariquesani** [comment]
When you save your page the latest versions do get rebuilt. They are also shown in the admin frame. I am not sure what server --watch would do extra.

**Comment by andrearicci** [comment]
after a bit of testing here's why you need the server:

my link internally are all pointing to directories, I need a server to serve up the relative index.html file, elsewhere I only reach a directory like:
`http://localhost:5000/projects/projectdir/`
![immagine](https://user-images.githubusercontent.com/1193266/30584775-13898e3c-9d2b-11e7-8f0e-fa10f9d972e7.png)
So no, `build --watch` is sadly not an option.
Adding a `server --watch` would better fill my needs.
Thank you again

**Comment by tariquesani** [comment]
Please refer to my reply above...

**Comment by andrearicci** [comment]
@tariquesani that's what I did, the difference between `build `and `server `is that, (if my links are relative to directories, and not files):

- **server** renders also pages "index.html" inside a directory
- **build --watch**  doesn't - it just open the directory

**Comment by andrearicci** [comment]
Ouch
I did'nt want to close

**Comment by tariquesani** [comment]
My contention is that the server does rebuild and show the changed contents when you save any page. That is equivalent to --watch

**Comment by andrearicci** [comment]
Testing with he commands `server`, `build --watch` and with the administrator web interface, I noticed that changes made in the working directory are immediately reflected in the output files (both in cache or build dir) but this do not trigger an automatic reload in the opened broser windows.

If this is the expected behaviour then I would like the "live reload" implemented.
If this is not the expected behavior then it's a bug.

tested on Chrome 60.0.3112.113 ( 64 bit), Firefox 55.0.3 (64 bit), IE 11
Lektor 3.0.1 on Win7/64

**Comment by nixjdm** [comment]
It is expected. I'm pretty confident the only JS that's added to the site as seen in the browser is for the admin edit link in the top right corner. JS could be added to refresh the page every so often (naive solution, which I'm fine with, at least for a while), or actually hook into the server somehow and poll for the knowledge of a change before refreshing. The preview in admin could do the same.

**Comment by drebs** [comment]
I think @andrearicci is proposing something like **Emacs HTML Impatient Mode**:

* https://github.com/skeeto/impatient-mode
* https://www.youtube.com/watch?v=QV6XVyXjBO8

I'm not sure how it'd fit with `server` and/or `build --watch`, but it would be a really handy feature.

**Comment by majidaldo** [comment]
I used `build --watch`. Then I opened the build directory with Visual Studio Code Live Server. Auto-reloads saved changes and I'm happy!

**Comment by xlotlu** [comment]
> I think @andrearicci is proposing something like **Emacs HTML Impatient Mode**:

Exactly, this is about live reload in the browser.

https://github.com/livereload/livereload-js

Yes, one can make it happen with other tools, inotify / some scripting etc., but this is a feature that should be in core, for any modern web development product.

Just try developing with hugo. You'll never want to go back to Ctrl+r.

**Comment by frostming** [comment]
Guys, I have worked out a solution in PR #1027 , and would love to see feedback about the feature.

**Comment by andrearicci** [comment]
I'm running 3.3.8, and I develop my site with VSCode on one monitor with a browser pointing to localhost on a second monitor launching it with `lektor.exe server`. VSCode has autosave enabled.  
With this setup there's non live reload enabled, I have to switch to the browser and reload the page to check my changes. Neithre I see any option for live reload in the admin interface. What am I missing?  
Thank you

**Comment by dairiki** [comment]
@andrearicci 
The live-reload PR #1027 is only in master and in pre-releases >=3.4.0b4.  So — there is no live-reload in 3.3.8.
(Pass the `--pre` flag to `pip` when installing/upgrading Lektor to install the pre-release version.)

At present, there are no admin controls — live-reload is always on.

I don't use VSCode, but as long as whatever browser is used supports our JS, I don't expect there should be issues related to that.  If there are, check the Javascript console for error messages, then let us know.

**Comment by andrearicci** [comment]
I did the installation with `pipx` and it doesn't seem to support `--pre`. So I have to wait. I hope you'll publish 3.4 soon. Thank you

**Comment by dairiki** [comment]
@andrearicci
The secret with pipx is the `--pip-args` parameter to `pipx upgrade` (or `pipx install`) which can be used to override the default arguments that pipx passes to pip.  It is a bit clumsy.

```sh
$ pipx upgrade --pip-args "--pre lektor" lektor
# => upgraded package lektor from 3.3.8 to 3.4.0b5 (location: /home/username/.local/pipx/venvs/lektor)

# to get back to 3.3
$ pipx upgrade --pip-args "lektor<3.4" lektor
# => upgraded package lektor from 3.4.0b5 to 3.3.8 (location: /home/username/.local/pipx/venvs/lektor)

**Comment by andrearicci** [comment]
Thank you for the instructions.
It seem to work now.
