### ISSUE TITLE
Replacing React in UI, possibly rewriting it from scratch

### ISSUE THREAD

**Issue by runfalk** [lektor/lektor#457]
It came to my attention there has been some discussion about replacing React, which is used for the frontend. I assume this is related to the weird extra patent clause Facebook has added to React's license which has caused [Wordpress](https://ma.tt/2017/09/on-react-and-wordpress/), all [Apache Foundation](https://issues.apache.org/jira/browse/LEGAL-303) projects and probably more to move away from it.

Until this is resolved it might be unwise to work on the following issues: #449, #431, #430, #376, #324, #41, #7, #98,  #217, #388, #384.

Putting political/ideological issues aside I think there are some other problems that might warrant rewriting the current admin. There is a lot of weird coupling between components going on:

- It is designed in a way that makes it seem like it should be possible to run multiple admins on one page (useful for testing). That's not possible due to a shared event bus for dialogs.
- All views such as edit, add-child, preview, etc. are dynamically injected to the application but their presence is required by the side-bar component. To add a new view the side-bar must be modified manually anyway.
- Routing state must be manually passed around which makes things really awkward in a lot of places, and it's hard to track what's being passed.
- Global hotkeys are handled by the Breadcrumbs component instead of the app itself.
- It depends heavily on the unsupported v2 of React-Router. Quite a few things needs fixing before upgrading (#430)

Lektor's small size (about 4,5k lines of JavaScript+JSX for the frontend) should make it pretty easy to replace. Before a rewrite can happen I think all features of the current admin should be thoroughly specified as checklists. That way there will hopefully be no major regressions.

The other issue is finding an alternative framework. There is an almost API compatible alternative called [Preact](https://preactjs.com/). It might also be interesting to look at the discussion and choices of Gutenberg (https://github.com/WordPress/gutenberg/issues/2733).

**Comment by nixjdm** [comment]
I will take a look at those issues and mark at least some of them as on hold, and look some for more. I'll also start an edit of your opening post and add a checklist at the bottom. I'll put a few things in there to get it started but I have the intention of growing the list over time. I want to hijack your opening post to make sure it's easily visible for when we actually begin working on this.

Some of my opinions: The ethos of Lektor is power in simplicity. React offers an awful lot, but comes at a very real development cost, especially to this community without a full time dev team. I'm becoming convinced the trade off in this case isn't worth it. Lektor's CMS can be built with Flask, Jinja (tools this community is probably more familiar with), and some JS just fine. The 'some JS' bit may be contentious, but I'm leaning toward tooling that is widely known with a shallow learning curve. What comes to mind first for that is jQuery and Bootstrap, again, with ample use of Jinja templating. Certainly, that lacks some features React or some of it's peers has, but it's probably more than sufficient.

**Comment by nixjdm** [comment]
There is also the potential here to decouple the admin from the core of Lektor. See https://github.com/lektor/lektor/issues/324#issuecomment-288117320 and https://github.com/lektor/lektor/issues/217. This would allow other's to potentially build a custom admin for Lektor. I'm not sure there's a huge need for that, but allowing for it might not be that hard.

**Comment by mitsuhiko** [comment]
Since lektor is not a company I do not see how the patent clause would be an issue.

**Comment by nixjdm** [comment]
If any company uses Lektor though, they could be caught by it.

**Comment by mitsuhiko** [comment]
Only if they were to modify the lektor admin UI itself.

**Comment by nixjdm** [comment]
It isn't clear to me when exactly someone might be liable, but it does seem clear that there's a lot concern around this. Enough that WordPress decided to not fight the argumentation and just side-step it. It seemed like a big reason [Matt Mullenweg](https://ma.tt/2017/09/on-react-and-wordpress/) wants to ditch React for WordPress is that he wasn't comfortable forcing his users to accept inheriting it, even though he thought the clause was rather clear.

@tariquesani spurred on this topic by bringing up the news about WordPress and this license, but there are other reasons to refactor the admin. There's several ways we can improve it. If that's approximately as easy to do by ditching React as it is by keeping it, then we might as well kill off another potential headache at the same time, IMO.

**Comment by runfalk** [comment]
@nixjdm feel free to edit the post as much as you want to

I don't think moving away from an all JS admin UI is a good idea. I feel like building traditional user interfaces starts off nice and structured, but the more features you add using JavaScript, the more convoluted your codebase gets. In the end you have hard to maintain spaghetti. Even the traditional Jinja route pretty much requires a JS build system, so that complexity is probably not going away either.

Since the amount of contributors is pretty small, I'd say the simplest way would be to try to fix the weirdness of the current admin system step by step and then try to make it work with Preact if React is problematic. That way the progress hopefully won't get stuck waiting for the new UI to happen.

**Comment by mitsuhiko** [comment]
I'm going to make an executive decision here: react will stay as far as the license is concerned. If there are other reasons to drop it then we can restart this conversation. If one wants to switch to preact for other reasons I won't stay in the way.

**Comment by mitsuhiko** [comment]
I probably closed this issue too early but I wanted to cut the conversation away from the license / patent grant or dropping JS altogether.

**Comment by ngrilly** [comment]
Anyway, Facebook is relicensing React under the MIT license. Problem solved.

**Comment by torian257x** [comment]
there are many reasons why the admin should be easy to customize.

I give you one: we use a flat model. E.g. all blog posts sit in `/`. Now I want to get a list of all blog posts in the admin. Well?

What about something else: I want all blog posts with the state `pending review`

I want my own little thing for the backend, well call me crazy, but I want a wysiwyg editor. What are my options?

I have written angularjs projects before, I have never used react.

Why are we using react?

KISS

we clearly do not need react for the backend or any "insertfancyjsframework"

the pull got plugged on angularjs (being replaced with no chance to migrate by angular)
the pull gets plugged on react as well, for different reasons maybe

why are people hyping that stuff anyway? if worked with it, I wasn't impressed.

for me you should use a JS framework if your backend code is JS. So you can actually profit from it.

Or use something that integrates well with a framework like vuejs and laravel that are literally recommended together.

but apart from that, something that works well and is easy to customize is what we want

having said that, if there are many libs and projects relying on our react backend, we should probably keep it

@tariquesani did not modify the admin backend because react is just another fancy js lib to deal with for little effect

I want to quote this one:

>  I have commented on #458 I have put off learning React after starting a couple of times because every time it soon started looking over engineered.

I agree with this.
