### ISSUE TITLE
install script under virtualenv picks bad binary paths

### ISSUE THREAD

**Issue by tiagoantao** [lektor/lektor#46]
The default script with fail when the default python is version 3.

I have started working on a version that is python agnostic (attached). But this still seems to fail when using a python distribution like anacoda, for example is installs binaries on
/home/USER/.local/
without consideration for the local environment,

[install.zip](https://github.com/lektor/lektor/files/72544/install.zip)

pip install works fine, BTW

**Comment by mitsuhiko** [comment]
Can you be a bit more specific in what it does with `.local`?  I assume your `python` executable is Python 3 and not Python 2? On which system are you where this is the case?  Or is this an activated virtualenv?

**Comment by mitsuhiko** [comment]
I changed the install script to also try python2 an executable. Not sure if that resolves your issue.

**Comment by tiagoantao** [comment]
It installs on /home/user/.local/lib/lektor

You assume correctly, my default Python is Python 3.

This is Linux, anaconda with an activated conda environment

**Comment by mitsuhiko** [comment]
> It installs on /home/user/.local/lib/lektor

Correct. That's what it is supposed to be doing.  I just want to find out why that would be a problem / relevant for the issue here.

> This is Linux, anaconda with an activated conda environment

I suppose Lektor should reject the installation if a virtualenv is activated.  Does conda use virtualenv or how does one go about detecting it?

**Comment by tiagoantao** [comment]
> > It installs on /home/user/.local/lib/lektor
> 
> Correct. That's what it is supposed to be doing. I just want to find out
> why that would be a problem / relevant for the issue here.

This is a problem with virtual environment isolation, as what you do on a
env should be invisible outside of it

> > This is Linux, anaconda with an activated conda environment
> 
> I suppose Lektor should reject the installation if a virtualenv is
> activated. Does conda use virtualenv or how does one go about detecting it?

Using environments to test software is a typical use pattern, I guess.
Anaconda does its own env management outside virtualenv. Maybe reject and
suggest pip? I would guess that anaconda environment based users would be
knowledgeable enough to pip.

**Comment by mitsuhiko** [comment]
> This is a problem with virtual environment isolation, as what you do on a env should be invisible outside of it

I'm not sure I follow. `~/.local/lib` is not a virtualenv, `~/.local/lib/lektor` however is the default location where the Lektor installation script will place a new virtualenv.

> Anaconda does its own env management outside virtualenv. Maybe reject and suggest pip? I would guess that anaconda environment based users would be knowledgeable enough to pip.

I'm really confused about what the actual issue is other than that Lektor attempts to install with Python 3 which was fixed.  Lektor does not install into existing virtualenvs through the installation command, it makes it's own which it will manage itself.  Pip installation is supported only for Travis and build environments, not for Lektor itself.

Maybe the docs are unclear about this?

**Comment by tiagoantao** [comment]
This might be a bad interaction with anaconda. There are two different problems:
- Directories (irrespective of the Python version):
  I am getting:

```
Installing at:
  bin: /home/tiago_antao/miniconda/envs/lektor/bin
  app: /home/tiago_antao/.local/lib/lektor
```

Whereas I was expecting:

```
Installing at:
  bin: /home/tiago_antao/miniconda/envs/lektor/bin
  app: /home/tiago_antao/miniconda/envs/lektor/lib/lektor
```

This is mostly a consistency issue as part of the installation goes inside the conda environment and part outside.
- Another problem is that this is not working with python 3. Note this without virtualenvs

```
$ sh install.sh 

Welcome to Lektor

This script will install Lektor on your computer.

Installing at:
  bin: /home/tiago_antao/miniconda/bin
  app: /home/tiago_antao/.local/lib/lektor

Continue? [Yn] 
Using base prefix '/home/tiago_antao/miniconda'
New python executable in /home/tiago_antao/.local/lib/lektor/bin/python
/home/tiago_antao/.local/lib/lektor/bin/python: error while loading shared libraries: libpython3.5m.so.1.0: cannot open shared object file: No such file or directory
```

Note that it is pointing to a python inside .local/lib/lektor/bin ?????

My anaconda python3 installation performs correctly with all other applications

**Comment by mitsuhiko** [comment]
I see. This is because the only path the installer finds that it has access to is tor anaconda bin folder. I probably need to consider this somehow.

**Comment by cldershem** [comment]
While trying to upgrade to 2.0 (for whatever reason it hasn't done this on its own) I've run into a similar problem and remembered I had this issue when I first installed Lektor.

I think I've got the fix (or at least a workaround), but since the script lives on (lektor-website)[https://github.com/lektor/lektor-website/blob/master/assets/install.sh] should I submit the pull request over there?

**Comment by mitsuhiko** [comment]
Yes please :)

**Comment by yagebu** [comment]
I'm closing this issue since the install.sh script was completely replaced by a Python script some time ago.
