### ISSUE TITLE
._path and categories

### ISSUE THREAD

**Issue by smth** [lektor/lektor#461]
When using categories, as described [here](https://www.getlektor.com/docs/guides/categories/), `this._path` returns project path, rather than, as I would have expected, the path comprised of the slug, as defined [here](https://www.getlektor.com/docs/guides/categories/#project-categories/contents.lr). Is this intentional? If so, how would you return the path as it appears in the address bar? i.e `/projects/categories/my-category` rather than `/project-categories/my-category`

**Comment by xlotlu** [comment]
That is not a field (see https://www.getlektor.com/docs/api/db/system-fields/) but it's the object's URL. `{{ this | url(absolute=True) }}` should do it. https://www.getlektor.com/docs/api/templates/filters/url/
