### ISSUE TITLE
images with an `@` in the filename create > AttributeError: 'NoneType' object has no attribute 'is_undiscoverable'

### ISSUE THREAD

**Issue by torian257x** [lektor/lektor#463]
> Cjossnaz@osboxes:~/IdeaProjects/lektor_ironscales/src$ lektor server
>  * Project path: /home/jossnaz/IdeaProjects/lektor_ironscales/src/lektor_ironscales.lektorproject
>  * Output path: /home/jossnaz/.cache/lektor/builds/aee0e3bca93424dd2c4f468dc6ad4bdb
>  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
> Started source info update
> Finished source info update in 0.66 sec
> Traceback (most recent call last):
>   File "/home/jossnaz/lektor/lektor/devserver.py", line 46, in build
>     builder.update_all_source_infos()
>   File "/home/jossnaz/lektor/lektor/builder.py", line 1150, in update_all_source_infos
>     self.extend_build_queue(to_build, prog)
>   File "/home/jossnaz/lektor/lektor/builder.py", line 1111, in extend_build_queue
>     queue.extend(prog.iter_child_sources())
>   File "/home/jossnaz/lektor/lektor/db.py", line 1011, in __iter__
>     for item in iterable:
>   File "/home/jossnaz/lektor/lektor/db.py", line 882, in _iterate
>     if self._matches(record):
>   File "/home/jossnaz/lektor/lektor/db.py", line 852, in _matches
>     if not self._include_undiscoverable and record.is_undiscoverable:
> AttributeError: 'NoneType' object has no attribute 'is_undiscoverable'

error was that I uploaded an image with `@` in the filename

**Comment by dwt** [comment]
I reached this point too when I added an image asset@2x.png - after I discovered that @ is a reserved character in urls I worked around by switching @ for _.

**Comment by nixjdm** [comment]
Duplicate. Closing this in favor of older ticket #245.
