### ISSUE TITLE
get_doc_link for the toc: once points to the good alternative page, once not.

### ISSUE THREAD

**Issue by vindarel** [lektor/lektor#48]
Hey,

I copied the sources of getlektor.com and added some alternatives, in order to build a multilingual website. My problem is that the urls of the toc menu on the left always point to the default alternative, consequently with their title in the wrong language too, when the ones at the bottom of the page work correctly. The `get_doc_link` macro is working for the bottom of the page, is it not working for the left menu ? How can we achieve that ?

in [templates/doc-page.html](https://github.com/lektor/lektor-website/blob/master/templates/doc-page.html#L13) this macro is called once to build the toc on the left: (so the urls only go to the default alternative andt the titles are of the wrong language)

```
        {% set docs = site.get('/docs') %}
        {% for child in set.get('docs').children recursive %}
          <li{% if this._path == child._path %} class="active"{% endif
              %}>{{ get_doc_link(child) }}
            {% if this.is_child_of(child) %}
            <ul>{{ loop(child.children) }}</ul>
            {% endif %}
        {% endfor %}
```

and again when building the two-columns links at the bottom:

```
        {% for cols in this.children|batch(2) %}
          <div class="row">
            {% for page in cols if page %}
            <div class="col-md-6 child">
              <h4>
                {{ get_doc_icon(page) }}
                {{ get_doc_link(page) }}
              </h4>
              {% if page.summary %}
                <p class="summary">{{ page.summary }}</p>
              {% endif %}
            </div>
            {% endfor %}
          </div>
        {% endfor %}
```

In `Website.lektorproject` I defined those alternatives:

```
[alternatives.fr]
primary = yes
name = French
locale = fr

[alternatives.en]
name = English
locale = en_US
url_prefix = /en/

[alternatives.es]
name = Castellano
locale = es_ES
url_prefix = /es/
```

I tried to modify the environment before the first call, with no success.

I'm using pypi's latest (v1.0). I can point to a live example if you wish.

Thanks !

**Comment by mitsuhiko** [comment]
`site.get` uses the primary alternative by default.  Use `site.get(..., alt=alt)` in the templates to load it in the current alternative.

Pleas use gitter for support questions and not this issue tracker.
