### ISSUE TITLE
urls in custom pages

### ISSUE THREAD

**Issue by madebr** [lektor/lektor#483]
When I create a custom page (as documented [here](https://www.getlektor.com/docs/guides/error-pages/)) in a subdirectory, lektor thinks that the custom page is in a subdirectory of its parent. Paths therefore cease to work.

File structure:
```
[content]
  +->[folder_a]
  |    +->contents.lr
  |    +->[form.php]
  |         +->contents.lr (_template: form.php, _model: none)
  +->contents.lr
[templates]
|->form.php (contains {{ this.parnet | url }}
```
`form.php` currently renders as `../../folder_a` where I would expect it to be `../folder_a/`.

`{{ site.get('/folder_a') | path }}` also renders as `../../folder_a`.

~~Is this expected?~~

I just noticed that the doc page I mentioned above does include a warning about using absolute paths.

Isn't this a bug that relative paths are not allowed when using custom pages?

**Comment by xlotlu** [comment]
@madebr how is this related to custom error pages?

> `form.php` currently renders as `../../folder_a` where I would expect it to be `../folder_a/`.

Which looks perfectly fine. To navigate from `form.php` to its parent you'd need either `../` or `../../folder_a`. Your expectation `../folder_a/` would lead instead to `/folder_a/folder_a`.

> I just noticed that the doc page I mentioned above does include a warning about using absolute paths.
> Isn't this a bug that relative paths are not allowed when using custom pages?

You are not dealing with custom error pages as per the doc. Yours is a very regular page that happens to be named `form.php`. Please reopen if you think I closed this in error.
