### ISSUE TITLE
Give user a cue for date format in blog post create/edit

### ISSUE THREAD

**Issue by willingc** [lektor/lektor#49]
As an enhancement, giving the user a visual cue of the date format to be entered would be helpful. It took me a while to find default format in api docs. I also tried clicking on the mini-calendar thinking it would pop up a date picker.
<img width="427" alt="screen shot 2015-12-27 at 1 01 14 pm" src="https://cloud.githubusercontent.com/assets/2680980/12012102/8dcf68dc-ac9c-11e5-9e14-3ded4c3de87e.png">

Overall, a very cool project :sunny:

**Comment by mitsuhiko** [comment]
Yeah. That also misses a calendar widget.

**Comment by tariquesani** [comment]
With addition of input type 'date' for date field in https://github.com/lektor/lektor/pull/350 This is fixed.
