### ISSUE TITLE
Upgrade jquery to v3

### ISSUE THREAD

**Issue by nixjdm** [lektor/lektor#494]
Github recently has warned us of jquery being out-of-date and thus a security vulnerability, and recommends an upgrade to v3 (we're on v2). I won't assume this is a trivial change. I changed it to 3.3.1 locally and nothing appeared broken at my glance, at least, but we might have to change something if we rely on any of the breaking changes listed [here](https://jquery.com/upgrade-guide/3.0/).

**Comment by yagebu** [comment]
@nixjdm: I did this in #746 :)

We're only using it for data fetching and didn't use any of the removed methods. I think at some stage, I'll try to replace it completely with plain `window.fetch`

**Comment by xlotlu** [comment]
Thanks @yagebu .

> I think at some stage, I'll try to replace it completely with plain `window.fetch`

That would be nice. Does that require a polyfill or is considered widespread now?

Now, the bot keeps bugging us about `/gui` (#771) but that's a different matter entirely. I'll close this.

**Comment by yagebu** [comment]
> Does that require a polyfill or is considered widespread now?

Apart from the usual annoying suspect (IE), it's widely supported (https://caniuse.com/#search=fetch), so for IE support, it would require a polyfill.
