### ISSUE TITLE
Remove AltGr+S key binding for saving in admin

### ISSUE THREAD

**Issue by krysros** [lektor/lektor#496]
I can not enter polish "ś" (AltGr+S) in the fields of the Lektor Admin panel. The AltGr+S keyboard shortcut saves the changes and redirects to the preview. Saving changes should be done by pressing Ctrl+S.

* Lektor 3.1
* Python 3.6.4
* Windows 10

**Comment by nixjdm** [comment]
Interesting. I discovered that myself a while back, but I considered it a feature, since I was used to typing Alt-x Alt-s to save in emacs. I haven't tried Ctrl-s, but it makes sense that that should save too.

I hear you, AltGr+s should change. Is Alt-s problematic for you too or just AltGr+s?

**Comment by krysros** [comment]
Ctrl+S also saves changes. There is no problem with Alt+S; AltGr+S is the only problem here.

**Comment by nixjdm** [comment]
Thanks. I've marked this as a bug since it was probably an unintended action that should be changed.

**Comment by eljoest** [comment]
I've created a branch in my fork for this. The required part is adding isMetaKeyOnly.
In #579 @davidism mentioned that .which is deprecated. But according to https://caniuse.com/#feat=keyboardevent-which the replacements (.keyCode or .key) are either deprecated as well or not available in some browsers/versions.

**Comment by yagebu** [comment]
This should be fixed by eabc3d97a8d08d4d2ebda24a1c167ba3ad2adb17
