### ISSUE TITLE
Allow URL field type to contain relative URLs?

### ISSUE THREAD

**Issue by sherbondy** [lektor/lektor#51]
Wondering what your thoughts were on this before having a go at implementing.

**Comment by mitsuhiko** [comment]
I think at that point it probably makes sense to just store it as a string.  What's the advantage of using the URL type there?

**Comment by sherbondy** [comment]
Hey I just realized that the url type does not actually stop users from saving relative urls, just marks as invalid. I don't really have an issue with this. Maybe I'll have a go at making a plugin with a relative url type. Benefit might be that I could validate the relative url against the site to see if a route exists for it. Maybe even provide autocomplete options or a warning if the route got deleted next time somebody edits the data. 

Closing!
