### ISSUE TITLE
"lektor serve" 

### ISSUE THREAD

**Issue by fmaida** [lektor/lektor#516]
With both Jekyll and Hugo when you want to launch the built-in server you can write `jekyll serve` and `hugo serve`, or you can either write `jekyll server` and `hugo server`. They're both allowing users to interchange the command `server` or `serve` to launch the built-in serve.

I know that the difference between the two commands are minimal, but I got used to the word "serve" from the other SSGs...

Could you possibly consider to add the command `lektor serve` as a (tiny) shortcut in addition to the existing command `lektor server` in a future release ? 

Thank you and best regards

**Comment by nixjdm** [comment]
I don't see a problem with a little alias. :) Should be really easy to add, too.

**Comment by fmaida** [comment]
Thank you very much !
