### ISSUE TITLE
Restore compatibility with lektor-thumbnail-generator

### ISSUE THREAD

**Issue by nixjdm** [lektor/lektor#520]
The plugin https://github.com/skorokithakis/lektor-thumbnail-generator currently doesn't work with 3.1 / master, because of [this commit](https://github.com/lektor/lektor/commit/b867261f27426670a250ea3b5e77b80152f9f967#diff-6189d81443cffb507c815d0c2ec6e783) that introduced another param, `format`,  on `computed_height`.

This addition isn't needed. We could extract the format in other ways from existing code in imagetools.py. For instance, possibly from `get_image_info`. If we do that then we also will restore compatibility with the thumbnail generator plugin.

**Comment by skorokithakis** [comment]
I agree with retrieving the format from the file, as that's the sanest way to do detection (relying on the user to pass the right format sounds frustrating for the user).

In the future, I'd like to advise that, if a new parameter is added, it is added at the end of the parameter list with a default (i.e. that it's a keword parameter). That way, you can be more backwards-compatible.
