### ISSUE TITLE
Add `lektor dev new-theme` command

### ISSUE THREAD

**Issue by nixjdm** [lektor/lektor#527]
This command should be very similar to the existing `lektor dev new-plugin` command, and use the same style prompts to query for basic information that will be used in creating a very basic theme. This theme should then be placed in `themes/` with a specified name, and contain a `theme.ini`. The `theme.ini` should be populated by the answers to the prompts.

I think there should also be a trivial amount of content in the new theme. Perhaps a single `layout.html` template file with very basic contents.

Like `lektor dev new-plugin`, this new command should be able to accept a `--path` option, and a `theme_name` argument.

**Comment by nixjdm** [comment]
A follow-up to this should be making an issue for updating the docs over at https://github.com/lektor/lektor-website

**Comment by lsrdg** [comment]
Thanks for creating the issue @nixjdm !

So, in instead of `$ lektor new theme <theme-name>` (as it is [documented](https://www.getlektor.com/docs/themes/creating/)), it should be `$ lektor dev new-theme`, with optional `--path` and `theme_name`, and prompts as needed?

I'll make a PR for the docs once there's a minimal `dev new-theme` on the way. (:

**Comment by nixjdm** [comment]
You're welcome! Yes, go with `lektor dev new-theme`, and `path` and `theme-name`, all to match the `lektor dev new-plugin` command. I changed those docs yesterday by the way :) You might be looking at a local cached page.

**Comment by nixjdm** [comment]
@lsrdg I've added some tests for `lektor dev new-plugin` here https://github.com/lektor/lektor/blob/master/tests/test_devcli.py that you can model tests for this command off of. They should look pretty similar. The plugin ones are a tad more complicated because it will create more files.

**Comment by lsrdg** [comment]
Thanks @nixjdm . 

I've copied and adapted the `new-plugin` structure to `new-theme`. Basically, just substituting occurrences of `plugin|plugins|Plugin` etc for `theme|themes` etc. So, there's also an `lektor/themesystem.py`. But I'm sure that this will need some cleaning afterwards. 

Right now, I guess I'll need to work on the following (quoting you on gitter):

> Note that the Generatorlooks for a dir in
lektor/lektor/quickstart-templates/ of a calculated name. In this case, that's
where a themes/theme.ini.in would go, that would be the template (with jinja-ish
template code in it) for the outputted theme.ini.

I haven't looked on this yet, and if it is ok, I'll get done with understanding how the generator works first before moving to the tests.

And by the way, this the branch: https://github.com/lsrdg/lektor/tree/lektor-527

Thanks for your patience and for coming up with those tests, they will certainly help a lot.

**Comment by nixjdm** [comment]
@lsrdg Sure, I expect the tests will come at the end. They're just ready when you get there. :)

We probably don't need a `themesystem.py`. Taking a look at `pluginsystem.py`, I don't think any of that is really relevant for themes. Themes don't have any python, and really are much simpler because of it. We don't need to load them in the same way as plugins, there's no event hooks, and there's no `class Theme` that needs importing in a theme module. Themes won't have a `setup.py` or module.

I double checked and searched the code base for `pluginsystem` to look at all of the imports. I don't think themes will have any corresponding imports. That should save quite a bit of complexity. The only python files you should need to touch are `devcli.py`, `test_devcli.py`, and `quickstart.py`. If you do think of a helper function, it could go in `themesystem.py`, but you don't need to copy `pluginsystem.py`.

Make sense?

**Comment by lsrdg** [comment]
It does make a lot sense now. :tada: 

After cleaning the mass (`setup.py`, `theme_module`, etc) I'm working towards the creation of `theme.ini` and how to populate it. Thanks for the explanation and for double checking everything.

**Comment by nixjdm** [comment]
@lsrdg I'm going to go ahead and take this over since I've got a bit of time and I want to put some energy into theme tickets right now. Thanks!
