### ISSUE TITLE
Proposal to move to a standardised content format

### ISSUE THREAD

**Issue by madisvain** [lektor/lektor#532]
This topic has caused issues for a few other people as well and the related issues would be:
* https://github.com/lektor/lektor/issues/439
* https://github.com/lektor/lektor/issues/477

It is a specific format used only in Lektor (https://www.getlektor.com/docs/content/) that needs a specialised parser and is not something that is widely used.

The proposal I'm making here would be to move to a industry wide standard that could be used in Static site CMS solutions like Netlify CMS for example: https://www.netlifycms.org/docs/add-to-your-site/

So these standard types would be:
* JSON
* YAML
* TOML

Looking at what we currently have TOML would be the most similar one. This would move the solution to a standard that is accepted industry wide and maybe would be of benefit to all?

**Comment by madisvain** [comment]
@nixjdm I completely understand the question of compatibility and respect the effort into keeping it working for people who have been with Lektor for some time.

Just for reference I'll add a comment from Armin:

> JSON does not support comments, so that's out of the question and making my own file format is not something I plan on doing. TOML is pretty terrible and user unfriendly, so that was out too. YAML is way too complex to deal with to automatically write back without destroying the comments in the file if a system updates it.
> 
> There are cases where lektor updates the files for you (for instance when you use the command line to add a plugin) so it's important the comments survive.
> 
> Another benefit of .ini: it diffs really well because it's inherently line based.

This discussion can be found [here](https://www.getlektor.com/docs/content/) in the comments section

**Comment by nomorepanic** [comment]
I am of the idea that markdown with frontmatter should be used for the content. There are many reasons for this, mostly boiling down to there's no real technical gain from using .lr -- infact, most of the times you can just change the extension to have a valid front-matter markdown file.

Otherwise, .lr should be standardized and pushed around as a better markdown, with all the effort that comes from that.

**Comment by goanpeca** [comment]
@Vesuvium 

>mostly boiling down to there's no real technical gain from using .lr 

There is as mentioned in the listed issues by @nixjdm 

> most of the times you can just change the extension to have a valid front-matter markdown file

Not true.

>Otherwise, .lr should be standardized and pushed around as a better markdown, with all the effort that comes from that.

It is an internal representation that served a specific purpose that probably only makes sense for this project.

**Comment by nixjdm** [comment]
YAML, TOML, JSON, and `.lr` files are entirely key / value. That's the big reason we can't easily switch to `.md`.

What about Hugo and Pelican? AFAIK, they can use a `.md` file, but what they contain is a beginning section of YAML, TOML, or JSON, followed by **a single block** of markdown. That last part is part is the key difference. `.lr` files can have any number of content fields that are text, html, markdown, rst, etc. all in one `.lr` file, without even using flowblocks. I don't think you can (or are supposed to) do this in Hugo and Pelican.

I get the desire to conform to their formats, and it would have benefits, but as far as I can tell their content files just don't store the same complexity of content as our `lr` files, unless it's mainly embedded in their early metadata sections, but I think that would be frowned upon and kind of an abuse of their system. If I'm wrong about this I'd love to see an example of how they would do it.

We need that key/value pairing for the whole file. Perhaps in unindented TOML (and a `.md` extension) GitHub would be tricked into rendering a file in a way that's half-way useful. I don't think we can get as close to a real `md` file as Hugo and Pelican can though.

**Comment by nixjdm** [comment]
As a separate point, as stated in #439 I believe, we could add a feature to import an entire file as txt, html, markdown, or whatever, in a quick reference. That has a use case and I don't see a problem with it.

**Comment by nixjdm** [comment]
I've come to the opinion that we should not modify the contents files' format at this time, so I'm going to close this issue and #439, which is very similar.

What we really need is #477, and once we get that, I don't think there is any large benefit to actually changing the contents files' whole format, especially if we do #541 as well. I've put an additional comment in https://github.com/lektor/lektor/issues/477#issuecomment-390292860, and just made #541 because of these two tickets.
