### ISSUE TITLE
Make appveyor builds more fault tolerant

### ISSUE THREAD

**Issue by nixjdm** [lektor/lektor#534]
Downloading and installing ImageMagick has been a thorn in my side for too long, and I would greatly appreciate someone taking that thorn out and burning it.

Chocolatey sometimes fails to download and install it. If that happens, tests fail. This seems to fail in fits. For some time I'll see builds work just fine, and then for a few hours, or days, I can't get a set of builds to pass.

Caching chocolatey install dirs has proven to be a bad solution. The cache itself is prone to corrupt refreshes. I've read several other accounts of this happening on Appveyor's forums. It does not seem robust.

The preferred solution is either an alternate download/install method that's actually reliable, or some try / retry method that detects a download/install failure, and retries it until it passes, resulting in a passed build.

I am not a Windows dev. Any help is appreciated. :)

**Comment by starworldx** [comment]
It looks like the project has transitioned to GitHub Actions. Are the appveyor issues still applicable?

**Comment by runfalk** [comment]
Nope, guess I'll close this one :)
