### ISSUE TITLE
python3 not able to be used to install lektor

### ISSUE THREAD

**Issue by wamcvey** [lektor/lektor#538]
With an image with python3 installed, but no python2, on Ubuntu there will be no "/usr/bin/python" in the PATH and thus the install script fails to run. Many common unix systems (notably, Ubuntu) will not link python3 as "python", so if python2 is not installed, the Lektor install script fails.

**Comment by nixjdm** [comment]
It looks like you're right https://github.com/lektor/lektor-website/blob/894b2471c344fd7af4bbdc82443a352a58a05b3f/assets/install.sh#L14-L19

I was unaware that distros we're finally pulling Python 2 out. I'll update that soon. That code is over in the website repo though, so I'll make an issue there and close this one. Thanks for pointing that out!

**Comment by nixjdm** [comment]
See https://github.com/lektor/lektor-website/issues/202
