### ISSUE TITLE
Can be used jinja2 tags in markdown or html fields?

### ISSUE THREAD

**Issue by clsource** [lektor/lektor#539]
Hello, 
I would like to use jinja2 tags inside a markdown or html field.
So for example I have a `body` markdown with this code.

`contents.lr`

```md
body : 
## {{ bag('index', this.alt, 'salute') }}
```

It should render Hello or something. But In the output it shows the raw jinja tags.

Is there a way to force parsing that output?

I know that you could use `contents+lang.lr` for translation purposes. But this could be also helpful for rendering more complex data like tables or something like that.

I'm currenty trying to include some images but since I can't use `{{ 'image.jpg' | url }}` in order to put the right path.

Thank you 👍

**Comment by nixjdm** [comment]
You can't do this natively in Lektor, but I wrote a plugin for it: https://github.com/terminal-labs/lektor-jinja-content

For some image manipulation specifically, it sounds like you may also be interested in https://github.com/skorokithakis/lektor-thumbnail-generator

**Comment by clsource** [comment]
cool
thanks 👍
