### ISSUE TITLE
Meta Menu for CMS layout

### ISSUE THREAD

**Issue by alan-cugler** [lektor/lektor#544]
Lektor needs the ability to manipulate the CMS layout. 

Currently, all of our fields in the CMS populate on top of each other reflecting the order in the .ini files the fields were created. The field extends horizontally across the window in the CMS regardless of their type and data actually inserted in the fields.

(1) I'm proposing a pop out menu for a catch all default layout style to apply to system fields.
(2) Then a button & pop out menu for each field for individual changes.

The available options in the pop out menu would include manually setting buttons native width (which is currently a css variable `width="100%"`), allowing them to be horizontally parallel with each other if width settings permit it, and  flowblock button limiter (this will be another issue).

This will make the CMS more compact and less "white space" wasted as a result.

**Comment by goanpeca** [comment]
That exists already and stacks things horizontally according to the fraction you provide. Have you used it?

https://www.getlektor.com/docs/models/


>`width`: defines the width of the input in the admin as a fraction. For instance 1/4 sets it to a quarter of the width, 1/2 to a half etc.
>`size` can be set to normal, small or large to affect the size a field is rendered in the admin UI.

**Comment by alan-cugler** [comment]
That moment when you mess up your github comment. {face palm}

Yes, I've used that but forgot when writing this issue. That does meet the part about manipulating the width of fields from the programming side. 

However, the main point of this issue is to get a meta menu created. 
There are other use cases for the meta menu, but I thought it more appropriate to make an issue for the meta menu with a small scope goal.
If this issue did get completed then I would add in additional new issues related to the meta menu options.

**Comment by nixjdm** [comment]
> However, the main point of this issue is to get a meta menu created.
There are other use cases for the meta menu, but I thought it more appropriate to make an issue for the meta menu with a small scope goal.
If this issue did get completed then I would add in additional new issues related to the meta menu options.

@alan-cugler I guess my question then is, what other option are you thinking of for a "meta menu"? Is this all about styling the admin - from within the admin?

**Comment by davidism** [comment]
The intention of Lektor is that someone designs the models, templates, etc., then users can use the UI to edit the content. I don't think the UI was ever intended to be an editor for project files, only for content.

**Comment by nixjdm** [comment]
The UI definitely wasn't designed for editing code.

I get the want to style the admin as you see fit. A little bit of that can be done with models now, but as for larger changes like skinning or something we have #324 and #458 that basically cover that. If we're going to be able to change the admin's look from within admin it should definitely come after those tickets, and after offering that ability at all. Since you say so @alan-cugler, I'll close this. We'll re-evaluate custom styles later.
