### ISSUE TITLE
Even read only git commands trigger build with `lektor serve` 

### ISSUE THREAD

**Issue by textshell** [lektor/lektor#550]
If the `.git directory` is in the site root, every git command triggers a build.

This is annoying when running `lektor serve` in the background in the same terminal when doing these git operations.

Lektor should have a way to ignore changes to git's internal state(i.e. lockfiles, etc).

**Comment by nixjdm** [comment]
There may be another solution to this, but the best solution would simply be to not watch directories we don't care about, like `.git`. [Unfortunately, it looks like Watchdog does not offer the ability to watch a subset of directories.](https://github.com/gorakhargosh/watchdog/issues/212)

Again, there are probably other ways of doing this, but that would have been the low hanging fruit I think.

**Comment by nixjdm** [comment]
An option in lieu of using an upstream fix for that issue, we could specify several watch dirs ourselves, and trigger rebuilds based on events in those several watchers.
