### ISSUE TITLE
ftp deploy on python 3 broken

### ISSUE THREAD

**Issue by nixjdm** [lektor/lektor#554]
From @uwekamper on gitter:

> This line causes an error for me: https://github.com/lektor/lektor/blob/05a541120e6f6add0d5d9d30d0585166f838594c/lektor/publisher.py#L280
when the self.con.login() is called, I get an error message saying "must be str, not bytes"

It looks like ftp doesn't work on python 3.

**Comment by uwekamper** [comment]
My immediate work-around for this bug was to create simple upload script:

    #!/bin/bash
    ( cd $(lektor project-info --output-path) ; \
        find . -type f -exec curl -u <username>:<password> --ftp-create-dirs -T {} ftp://<ftp-server- hostname>/{} \; )

**Comment by nixjdm** [comment]
This was fixed when #555 was merged, and didn't autoclose.
