### ISSUE TITLE
publish call via local server/api missing server_info

### ISSUE THREAD

**Issue by eljoest** [lektor/lektor#569]
When publishing via CLI the publisher gets a keyword parameter containing the server_info.
When publishing via the local server (from browser) the publisher does not get the server_info.

Additional parameters can not be retrieved by the publisher (e.g. lektor-s3) when publishing from the UI.

**Comment by nixjdm** [comment]
Fixed in #570

**Comment by nixjdm** [comment]
Thanks for the report, fix, and patience @eljoest!
