### ISSUE TITLE
Shortcut, propose meta+e for editing

### ISSUE THREAD

**Issue by Daniel-at-github** [lektor/lektor#582]
My proposal is adding `meta+e`as shortcut for editing in the `preview` page.

And please, add the shortcuts in the documentation:

`ESC` close slides
`meta+g` find files 
`meta+s` save. I think this comment is wrong:

https://github.com/lektor/lektor/blob/14fa9dfdee0f3ffde8dd445c7efaaf745395d19e/lektor/admin/static/js/views/EditPage.jsx#L54

**Comment by nixjdm** [comment]
I'd love to have M-e. Thanks for the suggestion. I've made a separate ticket for the docs changes https://github.com/lektor/lektor-website/issues/269

**Comment by yagebu** [comment]
This was added in https://github.com/lektor/lektor/commit/802fb8b87070865109d7ee0b6ffa530fb4c498b3
