### ISSUE TITLE
Please add example for event `markdown-lexer-config`

### ISSUE THREAD

**Issue by paternal** [lektor/lektor#587]
According to the [documentation](https://www.getlektor.com/docs/api/plugins/events/markdown-lexer-config/) event `markdown-lexer-config` *"is where lexer configuration can be set"*.

However, there is no example, and I could not find anybody using it (see for instance [this github search](https://github.com/search?q=on_markdown_lexer_config)).

I would like to implement a plugin adding a new lexer, but I do not understand how to use this event.

(Note that I could use [lektor-shortcodes](https://github.com/skorokithakis/lektor-shortcodes) as a starting point, which I did, but the [commit introducing `markdown-lexer-config`](https://github.com/lektor/lektor/commit/9e8d302937342cf248c572050f7236fa9546e46d) explicitly says that *"he new hook is of use to plugins like lektor-shortcodes, which seek to add new lexing rules to the Markdown syntax"*. So I think there might be a simpler way to do this than to follow `lektor-shortcodes` way?)

Thanks

**Comment by nixjdm** [comment]
This is more appropriate for the lektor-website repo, so I moved it over there https://github.com/lektor/lektor-website/issues/245
