### ISSUE TITLE
Change theme.ini format to support Python ConfigParser defaults

### ISSUE THREAD

**Issue by Andrew-Shay** [lektor/lektor#599]
I think the theme.ini file should be able to be loaded with ConfigParser defaults.
It currently cannot.

### Expected

1) Default ConfigParser will load theme.ini without exception
2) Values will not have quotes around them
3) PyCharm will not show errors in the ui due to keys starting with spaces

### Actual

1) theme.ini raises `configparser.MissingSectionHeaderError: File contains no section headers.` because the contents do not start with a section header. It starts with keys.
2) Because values have quotes around them, when printing the values, the quotes remain by default
3) PyCharm highlights in red, `name` under the `author` section. Removing the leading spaces removes this error/warning.

### Steps to repro

`code`
```python
from configparser import ConfigParser
parser = ConfigParser()
with open("theme.ini", 'r', encoding='utf-8') as f:
    parser.readfp(f)
print(parser)
```

`sample config`
```ini
name = "ThemeName"
license = "MIT"
licenselink = "https://google.com"
description = "Simple Theme "
homepage = "https://github.com"
tags = ["simple", "minimal", "blog"]
features = ["blog"]
lektor_required_version = 3.1

[author]
    name = "foobar"
    homepage = "http://github.io/"

[original]
    author = "origAuthor"
    homepage = "https://github.com"
    repo = "https://github.com/repo"

[packages]
    lektor-disqus-comments = 0.2
```

### Suggestion

1) Require all keys be in sections
2) Do not quote values
3) Do not start keys with leading spaces
4) EDIT: Lists/Arrays should just be a CSV string

`Sample Suggested theme.ini`
```ini
[theme]
name = ThemeName
license = MIT
licenselink = https://google.com
description = Simple Theme
homepage = https://github.com
tags = simple, minimal, blog
features = blog,
lektor_required_version = 3.1

[author]
name = foobar
homepage = http://github.io/

[original]
author = origAuthor
homepage = https://github.com
repo = https://github.com/repo

[packages]
lektor-disqus-comments = 0.2
```

**Comment by Andrew-Shay** [comment]
@nixjdm

**Comment by nixjdm** [comment]
@Andrew-Shay That all sounds fine to me. The primary section being `theme` is fine, and the other items are pretty obvious too. Let's do it.

**Comment by Andrew-Shay** [comment]
@nixjdm Additional thought. Should we simplify the list values to CSV strings?

Current `tags = ["simple", "minimal", "blog"]`
Proposed `tags = simple, minimal, blog`
We would do a split on the comma, then a strip on each value.

Pros: Easier to parse and read
Cons: It's not obvious that a value is a list when a sample only has one value

**Comment by runfalk** [comment]
If we want to keep the array, maybe we simply want to rename it to `theme.toml`. It looks to me like it's TOML-compatible. Are these files parsed anywhere? I tried to look but didn't find anything.

**Comment by nixjdm** [comment]
There is currently nothing public that parses this file yet, but @Andrew-Shay is working on a private plugin for lektor-website that would use it, and of course the other theme tickets would start using it.

I want to stay consistent with what we're doing elsewhere in this project. We don't currently (and likely won't for a while if ever) support alternatives to inis elsewhere in lektor, and they shouldn't be supported here separately.

If you look through the docs, you'll see the de facto standard in lektor projects is to use csv strings instead of arrays. Good catch. So that's the way we should do it in these files too.

**Comment by rlaverde** [comment]
It's parsed using https://github.com/mitsuhiko/python-inifile, see https://github.com/lektor/lektor/blob/master/lektor/environment.py#L87

I implemeted it using ini to reuse the existing code, and load themes configurations in the same way as Lektor configurations.

I also in favor of moving to toml (It's more powerful than ini, and has a standard definition), although It will break backward compatibility.

**Comment by nixjdm** [comment]
@rlaverde So then python-inifile supports what you have, as well as the proposed changes, correct?

Edit: For future theme tickets then, someone could get away with a theme.ini formatted in either way. I would still change the https://github.com/lektor/lektor-themes Readme to be consistent with other inis in our docs.

**Comment by rlaverde** [comment]
> So then python-inifile supports what you have, as well as the proposed changes, correct?

Yes, I suppose, I'm not sure, python-inifile looks like a black box to me 😕

**Comment by nixjdm** [comment]
@Andrew-Shay We should make these changes to conform the existing theme.ini to the standard config-parser compatible ini format wherever it isn't. In this repo, that's only in the example project and a couple tests. Then there are the docs and actual themes. Making all of those changes should be pretty simple and quick, even if it's a little tedious.

**Comment by Andrew-Shay** [comment]
@nixjdm Cool, Ill make the changes

**Comment by nixjdm** [comment]
This is completed as far as this repo is concerned in #601, and nearly complete everywhere. I've done all I can. I pulled your PRs @Andrew-Shay, updated the lektor-themes readme, and my own theme, and submitted a few quick PRs to the other themes, owned by @Andrew-Shay, @rlaverde, and @hannylicious.
