### ISSUE TITLE
Development environment setup

### ISSUE THREAD

**Issue by briancappello** [lektor/lektor#60]
This continues the discussion from issue #59 with regards to the Admin UI and Webpack file watching.

**Comment by mitsuhiko** [comment]
@briancappello you need to do `pip install --editable .` instead of `python setup.py install`.

**Comment by briancappello** [comment]
@mitsuhiko Ah perfect, thank you, that did the trick!

**Comment by mitsuhiko** [comment]
Clarified it in the README: 0a960890537e6b328a25d16cb6b626bc6877fa29
