### ISSUE TITLE
thumbnails are not named according to reality and can yield duplicates 

### ISSUE THREAD

**Issue by xlotlu** [lektor/lektor#608]
Currently thumbnail filenames are generated using only the requested value(s), which isn't precise enough and can differ from the real dimensions anyway.

They should instead be written out with full details, i.e. both width & height regardless of which one was provided, and with real values, which would avoid useless duplicates.

This isn't a breaking change, and it's not complicated either, but it implies regeneration of thumbnails for a whole many people. Ideally the commit would avoid this by bringing along a mechanism that simply renames the old stuff.

**Comment by xlotlu** [comment]
closed in #1139?

**Comment by dairiki** [comment]
> closed in #1139?

Yes, I think so!  At least, modulo the part about a mechanism to rename from the old thumbnail names to the new ones.
