### ISSUE TITLE
Lektor thumbnail: set colorspace in imagemagick

### ISSUE THREAD

**Issue by rponline** [lektor/lektor#611]
People tend to feed lektor any JPG files - also with e.g. Photoshop-CMYK-JPGs.

But JPGs with uncommon colorspaces tend to compress very badly and so on.  
For me, it resulted in JPG files wtith a few MB filesize on the website.

 I propose to add `-colorspace sRGB` (it's the most common in the web) in every imagemagick operation.

**Comment by rponline** [comment]
https://github.com/lektor/lektor/compare/master...rponline:patch-1

**Comment by xlotlu** [comment]
On a related note, it seems that much of the filesize is in fact due to the embedded color profile itself:

```shell
$ convert cmyk.jpg -strip cmyk-x.jpg 
$ convert rgb.jpg -strip rgb-x.jpg 
$ stat -c '%n: %s' cmyk*.jpg rgb*.jpg 
cmyk.jpg: 1041608
cmyk-x.jpg: 80345
rgb.jpg: 80148
rgb-x.jpg: 71582
```

**Comment by nixjdm** [comment]
I don't know, but if there is no safe and good colorspace (as asked in the PR), which intuitively seems reasonable to me, then we shouldn't force one. Maybe make it an optional parameter?

**Comment by rponline** [comment]
Optional parameter sounds good. 
Maybe also for the strip flag.

**Comment by xlotlu** [comment]
I personally lean towards the initial suggestion: hardcode it for any thumbnail operation. Given that browsers have to do the conversion anyway, and a thumbnail ready for print doesn't make sense, I don't even see a point in making it a default and giving control to the users. (... it may be a good idea for some future-planned operations, like simple conversion, but not for thumbnailing).

The one question that needs answering is if it's the right / safe thing to do in all cases. A short and inconclusive test shows that imagemagick doesn't touch grayscale images, despite the `-colorspace sRGB`, and in all other cases... everything uses sRGB, correct?

P.S.: I'd even go so far to make `-strip` default, or at least `+profile '*'` (as strip clears both profiles and comments). I've read someplace that browsers assume sRGB if they don't find an embedded profile, but this should be investigated.

**Comment by skorokithakis** [comment]
What do we want to do here? Just add `-strip` or also `-colorspace sRGB`? It's a pretty straightforward change, and since `process_image` is only called by `make_image_thumbnail`, it shouldn't be too dangerous.

**Comment by xlotlu** [comment]
I think ideally there should on one hand be a default to convert the colorspace to sRGB, and another default to strip all info.

I'm thinking these should be overridable in case we'll do other image operations in the future besides thumbnailing. (e.g. just convert the format but preserve everything else)

**Comment by skorokithakis** [comment]
I'd go with YAGNI and make them overridable when we actually need to override them. It's not like it's hard to do, and I don't know if it would be wise to add flags that nobody wants to use. Then again, plugins...

**Comment by xlotlu** [comment]
> I'd go with YAGNI

Fair enough..

**Comment by nixjdm** [comment]
Changed in https://github.com/lektor/lektor/pull/694
