### ISSUE TITLE
how can use databags as source for checkbox field

### ISSUE THREAD

**Issue by Arstman** [lektor/lektor#614]
hi, i try to access databags from modeling file of a page, and below is the way i do:

[fields.label]
label = labels
type = checkboxes
source = site.databags.get_bag('categories')

and i got a error: TypeError: string indices must be integers

how can i use databags as a source of checkbox field?

thanks

**Comment by Arstman** [comment]
thanks for reply Joseph, I am trying to make a plugin to do this, still working with docs.

**Comment by iainhallam** [comment]
I came across this while looking for how to do the same with a select field!

**Comment by dairiki** [comment]
Is there a desire to have PR #1155 back-ported to the stable Lektor 3.3.x branch?  (If so, say so.)

**Comment by iainhallam** [comment]
> Is there a desire to have PR #1155 back-ported to the stable Lektor 3.3.x branch? (If so, say so.)

I suppose it depends on whether this will make it into 3.4, and if so, how long it might be until a release.

**Comment by dairiki** [comment]
> I suppose it depends on whether this will make it into 3.4, and if so, how long it might be until a release.

It's currently in the `master` branch, so it will be in the next 3.4.0b pre-release (which can be made very soon, if you would like it to be).  3.4 "should" be out of pre-release sometime soon-ish (but it's been that way for a while, so who knows?)
