### ISSUE TITLE
install.ps1 not working on Windows 10 with Python 3.7.1

### ISSUE THREAD

**Issue by tonnydourado** [lektor/lektor#617]
When running the install.ps1 script, it fails when it tries to create the virtualenv. 

The issue is that the install script will try to run `virtualenv.py` from `<temporary dir>\\<virtualenv name>`, but there's no `virtualenv.py` file in this folder: the file is in `temporary dir>\\<virtualenv name>\\src` (maybe it's a change on how virtualenv is packaged?). I solved it in my machine by just adding `"src"` to the `os.path.join` call on the `install` function, like this:
```
Popen([sys.executable, 'virtualenv.py', lib_dir], cwd=os.path.join(t, virtualenv_filename, "src")).wait()
```

I wanted to submit a patch but I couldn't find the install.ps1 file anywhere, is it not in this repository?

**Comment by andoresuperesu** [comment]
Could you please provide the output of the error? I've got the same setup
but didn't get any errors on install. No breaking change is stated on
virtualenv's documentation either.

**Comment by nixjdm** [comment]
That file is a downloadable asset for getlektor.com, so it's stored over here: https://github.com/lektor/lektor-website/blob/master/assets/install.ps1, for now at least.

**Comment by grushkovsky** [comment]
Windows 10, Python 3.7.1

```
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

PS C:\Windows\system32> iex ((new-object net.webclient).DownloadString('https://getlektor.com/install.ps1'))

Welcome to Lektor

This script will install Lektor on your computer.

   Installing at:
   C:\Users\Nikolay\AppData\Local\lektor-cli

Continue? [Yn] y
C:\Python\Python37\python.exe: can't open file 'virtualenv.py': [Errno 2] No such file or directory
Traceback (most recent call last):
  File "<string>", line 149, in <module>
  File "<string>", line 144, in main
  File "<string>", line 110, in install
  File "C:\Python\Python37\lib\subprocess.py", line 769, in __init__
    restore_signals, start_new_session)
  File "C:\Python\Python37\lib\subprocess.py", line 1172, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

**Comment by xlotlu** [comment]
> That file is a downloadable asset for getlektor.com, so it's stored over here: https://github.com/lektor/lektor-website/blob/master/assets/install.ps1, for now at least.

Yet another example of the unfortunate separation between project files and site files. https://github.com/lektor/lektor-website/issues/226
