### ISSUE TITLE
Templates: relative links to alternatives doesn't work if _slug is set

### ISSUE THREAD

**Issue by duebbert** [lektor/lektor#62]
Using `{{ '.'|url(alt='ru') }}` as per https://www.getlektor.com/docs/templates/urls/ doesn't work correctly if a _slug was set in the contents+ALT.lr file.

For example:
1. page `/about` with alternatives `en` (primary) and `de`. 
2. contents+de.lr has `_slug=/bio`.
3. The link generated for `{{ '.'|url(alt='de') }}`is incorrectly `/de/about/bio` instead of `/de/bio`.

Workaround for now is to use `{{ this._path|url(alt='de') }}` instead of the relative link.

**Comment by mitsuhiko** [comment]
I think this fixes it.  However it also slightly changes behavior so it will land in 2.0.  Maybe you could verify it works for you.
