### ISSUE TITLE
imghdr.what fails to determine image format for this image

### ISSUE THREAD

**Issue by nixjdm** [lektor/lektor#624]
Here's the image: http://i.imgur.com/HC4fuSI.jpg

Tested with Python 3.7.0

If you use this image, https://github.com/lektor/lektor/blob/12518a246e5ef0b012c78bba8075a7a076d4c186/lektor/imagetools.py#L334 will fail to determine the format of the image, and return `None`. Thus any thumbnail operation will fail with `RuntimeError: Cannot process unknown images` from imagetools.py

I don't know why that image fails, or if any better introspecting is available. If we can fix that, great. Regardless, I'm wondering if we should fall back onto simply using the file extension when we can't detect the image format.

FWIW, this image came from a video I took with my phone last year, and then thumbnailed with https://github.com/lektor/lektor/pull/497 If it's helpful, I might be able to generate more images, or a source video that I'm willing to share.

**Comment by xlotlu** [comment]
I think you have uncovered a bug in imghdr. :) 

They have a pretty bad jpeg test:
https://github.com/python/cpython/blob/ef223a19f76101a914ccff8b4690d9e4717e109e/Lib/imghdr.py#L37 -- it holds true only for jfif / exif images (which, debatably are what you're likely to find, but apparently not always), but doesn't really test that the image is truly a jpeg file (i.e. it has a start-of-image marker).

Note that your image is conformant to the initial standard -- every tool i tried manages it just fine, and if you replace `fmt = 'jpeg'` in imagetools.py, `get_image_info` will work just fine.

**Comment by nixjdm** [comment]
#653 basically replaces this ticket.
