### ISSUE TITLE
Multi level menu

### ISSUE THREAD

**Issue by georgkaser** [lektor/lektor#638]
Hi,
I searched a little bit - nothing found: How to implement a multi level menu? I want to generate it automatically for example from a .json file. Is this possible? I need to sort the menu entries.
Thanks!

**Comment by runfalk** [comment]
You can use the recursive loop feature of Jinja (http://jinja.pocoo.org/docs/2.10/templates/#for) together with a loop over a page's children.

If you want to generate a menu from the site root, loop over `site.query("/")`. I haven't tested the code but you could probably do something like:

```jinja
{% for p in site.query("/") recursive %}
    <li>
        <a href="{{ p|url }}">{{ p.title }}</a>
        {% if p.children %}
            <ul>{{ loop(p.children) }}</ul>
        {% endif %}
    </li>
{% endfor %}
```

While I don't think this belong on the bug tracker, it makes sense to add to the documentation. I'll leave the issue open for now.

**Comment by georgkaser** [comment]
Yes sure, it's not a bug - you're right, maybe its good to add it to the documentation.
I found in the documentation that it's possible to iterate recursive (https://www.getlektor.com/docs/templates/navigation/#recursive-tree-navigation) - it works great, but here I have no possibility to sort the entries. But I found out it works with the sort_key - maybe you want to have the code for the documentation:

```django
<ul class="tree-nav">
{% set root = site.get('/') %}
{% for child in root.children.order_by('sort_key') recursive %}
    <li{% if this._path == child._path %} class="active"{% endif %}>
        <a href="{{ child|url }}">{{ child.title }}</a>
        {% if this.is_child_of(child) %}
            <ul>{{ loop(child.children.order_by('sort_key')) }}</ul>
        {% endif %}
    </li>
{% endfor %}
</ul>
```
Great software by the way!

**Comment by runfalk** [comment]
Right, the current documentation is a bit har to navigate. I actually looked without finding that example.

Does this solve your problem?

**Comment by georgkaser** [comment]
Yes, thanks for your help!!

**Comment by runfalk** [comment]
Great, I'm closing this issue then. If people find this in the future I recomend dropping by our gitter channel (https://gitter.im/lektor/lektor) if you have questions like this.
