### ISSUE TITLE
Admin edit button is inserted after </body>

### ISSUE THREAD

**Issue by akx** [lektor/lektor#639]
The rewriter function https://github.com/lektor/lektor/blob/5cc3ef09350a0336c32bf7a2e2bb531b01680115/lektor/admin/modules/serve.py#L68 should be made smarter, namely to at least attempt to insert the code before the closing `</body>` if there is one.

Content after `</body>` is a validation issue.

**Comment by runfalk** [comment]
I don't see why we couldn't change this. The button already assumes the template is UTF-8, and Jinja probably does the same. The only problem I can think of is performance for larger pages, which is probably a non-issue.

Do you have a particular case where this is causing an issue for you?

**Comment by akx** [comment]
I was just running some HTML validation against a `lektor server` and it kvetched about every page, since every page had the edit button following the actual markup. :)

**Comment by tgpfeiffer** [comment]
Just moving it before the closing `</body>` is simple, but it won't fix the validation issue, since `<style>` isn't allowed within `<body>`. One would probably have to split the `<style>` and `<script>` and append them to the `<head>` and `<body>`, respectively.

**Comment by akx** [comment]
[MDN says](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/style) `<style>` is okay within `<body>`:

> The <style> element can be included inside the <head> or <body> of the document, [...]
