### ISSUE TITLE
Strange scroll behaviour with flow elements on Firefox

### ISSUE THREAD

**Issue by georgkaser** [lektor/lektor#640]
A very annoying scroll behaviour happens with flow elements in Firefox:

![Firefox](https://user-images.githubusercontent.com/6472869/54293607-95206680-45b0-11e9-8bd3-35225f92ebd3.gif)

This is what it looks like in Chrome (Chromium in my case) - it's much better:

![chrome](https://user-images.githubusercontent.com/6472869/54293643-a5d0dc80-45b0-11e9-8b99-974eee642c42.gif)

I don't want to use Chrome so it would be nice when it can be fixed soon ;)

**Comment by runfalk** [comment]
I think this is related to how the dynamic height of the textarea is calculated. I think it involves temporarily setting the height to a very small value which is the cause of the scroll bar jump. This is done on every keystroke.

A solution for this I did in another project is to wrap the textarea in a div. When the size is recalculated the height of the wrapping div can be set to the height of the inner textarea + 2* its vertical padding + 2 * its vertical border width. This way the scroll remains at the exact same location.

**Comment by runfalk** [comment]
I was hoping the change *"Smoother scrolling: Scroll anchoring keeps content from jumping as images and ads load at the top of the page"* in Firefox 66 would fix this. I tried, and it did not.

**Comment by achimnol** [comment]
This is happening in Lektor 3.3.0 with Chrome 96 on macOS Monterey 12.1 as well.
When the textarea's height exceeds the view height, typing any character in it resets the scroll to the top.

Manually removing `input` event handlers using the developer tools resolves the issue.
![image](https://user-images.githubusercontent.com/555156/147813543-1852f82a-c9ef-493e-9926-52a258b86096.png)

**Comment by yagebu** [comment]
The scroll-adjusting logic always seemed a bit dodgy to me. I've tried it in both Chromium and Firefox and it has some quirks. Without the scroll-adjusting it still seems to scroll weirdly some times (like when keeping Enter pressed for a while), but overall it seems to work better by sticking to the browser default of scrolling when the textarea changes. I'll make this change in #977
