### ISSUE TITLE
collapsing flow elements

### ISSUE THREAD

**Issue by mrVanDalo** [lektor/lektor#649]
This is a feature request, for collapsing flow elements.
When there are a lot of flow elements, it would be nice to collapse/shrink/minimize them, using a button next to the move up/down and close buttons.

For example 
![image](https://user-images.githubusercontent.com/839693/57155361-877ea480-6ddb-11e9-8fcd-b33aaede1db3.png)

**Comment by jtraub91** [comment]
I think I can take a crack at this. Would you mind supplying a code example using the flow elements as you mentioned?

**Comment by mrVanDalo** [comment]
@jtraub91 nice, well I don't meant a special flow element,  would just like to collapse the flow elements in the editor, so I can concentrate on the beef. I could send you a current screen shot and (maybe my gimp skills are good enough) a sketch und how I would like to have it.

**Comment by nixjdm** [comment]
@jtraub91 There's an example project embedded in this repo that has a trivial use of flow blocks. Look in the [example dir](https://github.com/lektor/lektor/tree/master/example). The /types page has a couple flow blocks. They aren't huge, but there's still content that could be collapsed, and you could add content easily.

If it can look good, being able to collapse *any* element would be nice, not just flow blocks. I can break that into a different issue if whoever does this just does the flow blocks.

The easy solution to this is just to allow simple collapsing. Better would be remembering if something was collapsed when navigating to different pages and back. An out-of-scope follow-up that could be nice is setting elements to default to being collapsed in the models - which may have occasional value where there are also default values for fields.

**Comment by jtraub91** [comment]
@nixjdm Thanks for the tips / suggestions. I should be able to make some headway today

**Comment by jtraub91** [comment]
Added simple collapse. Figured I would open PR before adding other features as mentioned above. Details in the PR here: https://github.com/lektor/lektor/pull/660
