### ISSUE TITLE
Replace use of imghdr to guess image formats

### ISSUE THREAD

**Issue by nixjdm** [lektor/lektor#653]
[PEP 594 is drafted to remove imghdr from Python](https://www.python.org/dev/peps/pep-0594/#imghdr). We use it to guess the format of an image only on this line: https://github.com/lektor/lektor/blob/723e9ecd97a305f128de369a4466a2863307b31a/lektor/imagetools.py#L334

We know imghdr provides a poor guess anyway. This ticket removes the use for an upstream fix for #624, so I'll close that.

**Comment by xlotlu** [comment]
Time to write that library of our own? :)

**Comment by runfalk** [comment]
It may not be desirable to add more external dependencies but I would consider [exiftool](https://www.sno.phy.queensu.ca/~phil/exiftool/#supported) to be very good when it comes to image formats and metadata. It has the additional benefit of providing exif data, i.e. we would no longer need our own exif parser.

The huge drawback is that it introduces Perl as a dependency, which should be fine on Linux, but Windows will suffer.

**Comment by xlotlu** [comment]
> It may not be desirable to add more external dependencies but I would consider exiftool

In the same manner, we could simply use imagemagick's `identify`, possibly `--verbose`. exiftool is pretty impressive, but do we really need all that power? There's also [exiv2](https://exiv2.org/), which is cross-platform.

Anyway, what we talked about a while ago was to have a library that accesses data only as needed, without reading more into the file than necessary, with lazy, cached access to image properties. 

P.S.: if we ever do this, [this database](http://owl.phy.queensu.ca/~phil/exiftool/sample_images.html) from exiftool is great to use for tests.
P.P.S.: We could start with a pythonic API around one of these command-line tools, and then move to per-format pure-python implementations, preserving the initial thing as fallback.

**Comment by skorokithakis** [comment]
> It may not be desirable to add more external dependencies

What's the actual harm of pure-python external dependencies? I've been avoiding adding more dependencies but I can't actually find any downside, as long as they don't need extensions/etc.

**Comment by xlotlu** [comment]
On 5/23/19 2:11 PM, Stavros Korokithakis wrote:
>     It may not be desirable to add more external dependencies
> 
> What's the actual harm of pure-python external dependencies?

He wasn't talking about a pure-python one, but in this case about 
something that would bring along the entire perl machinery.

IMO, if it's pure-python and it's something that provides reusable 
behaviour / features, separating out the code into a stand-alone project 
is in fact desirable.

**Comment by skorokithakis** [comment]
Oh, if we're talking about exiftool or other binaries, I agree, it's too heavy to include.

> We know imghdr provides a poor guess anyway

Does it? Do you have details on that, @nixjdm? I've never heard of anything like that, and I would expect looking at the headers to provide good guesses.

**Comment by xlotlu** [comment]
@skorokithakis I'll answer for @nixjdm since I'm already here. See the discussion under #624 for details. There's also a bunch of issues filed against in in the Python tracker, and... it's gonna be deprecated real soon anyway and be removed by 3.10 (see the link on top).

**Comment by runfalk** [comment]
Well, [PEP 594](https://www.python.org/dev/peps/pep-0594/) isn't accepted yet, so anything can happen.

**Comment by xlotlu** [comment]
> Well, [PEP 594](https://www.python.org/dev/peps/pep-0594/) isn't accepted yet, so anything can happen.

Aaand [the discussion](https://discuss.python.org/t/pep-594-removing-dead-batteries-from-the-standard-library/1704) already got heated for some items.

Either way, the need for something better than imghdr came way before #624, when I was working on #551. If you guys are in for this, I think within a few weeks we could come up with something that does what imghdr does (and more), with a nicer, cleaner API, and with efficiency in mind.

I did give this a lot of thought: I already have the API in mind, how it should work behind the scenes etc. (I even wrote some code a while ago). If you say yes I'll do a brain dump and we can work TDD-style.

(But if all we want for now is an imghdr replacement, one of the proposed substitutes in the PEP should do.)

**Comment by runfalk** [comment]
Are you planning on doing this from scratch or reusing some existing library? If possible I think it's better to depend on something battle tested, since images are very often not standards compliant.

If you want to build something yourself, maybe it's better to develop it outside of Lektor "core", and then use it as a dependency? I have no objection to letting such a package be part of the Lektor organization. It seems like something other projects could benefit from.

**Comment by nixjdm** [comment]
I agree that we should try to stay away from adding in non-pure-python dependencies unless the case is compelling, so I'm hesitant to go with exiftool. I haven't looked much into the other options though, or heard yours, so I'm not ruling it out. imagemagick is already here, so that's on the table from a packaging standpoint. That database you found @xlotlu looks pretty handy. I'd love to hear your thoughts. Strictly, all we *need* is probably a replacement for this one use, but I'd certainly welcome further improvements.

**Comment by davidism** [comment]
The PEP mentions both https://pypi.org/project/puremagic/ and https://pypi.org/project/filetype/ as substitutes for imghdr. They are both pure-Python and cross platform, and while they won't get you EXIF data, they should handle identifying the types we're dealing with here.

**Comment by xlotlu** [comment]
@runfalk:

> Are you planning on doing this from scratch or reusing some existing library? If possible I think it's better to depend on something battle tested,

From scratch, I never found anything that does quite what I want. There was some library that came close (or part of a larger project I think?), but I don't remember which it was. Maybe I will.

> since images are very often not standards compliant.

The funny thing is that at least as far as jpeg goes, all images I found were standards compliant, and it was imghdr that ignored the standard.

> If you want to build something yourself, maybe it's better to develop it outside of Lektor "core", and then use it as a dependency?

That was the plan all along.

> It seems like something other projects could benefit from.

Exactly.

@davidism:

> The PEP mentions both https://pypi.org/project/puremagic/ and https://pypi.org/project/filetype/ as substitutes for imghdr.

I like `filetype`. A lot.

@nixjdm:

> Strictly, all we _need_ is probably a replacement for this one use, but I'd certainly welcome further improvements.

Yes, the pragmatic thing to do is replace the use of `imghdr` with `filetype` above, and I think this is definitely the right thing to do to close this ticket (and fix #624).

In the long(er) run however, a library that merges filetype detection with image info retrieval would greatly speed things up, especially if it's written so it doesn't chew up uselessly through data. So, if you guys are onboard, at least with API feedback and code reviews, I personally would be extra-motivated to work on it. :)

**Comment by nixjdm** [comment]
@xlotlu I'm on board for feedback and code reviews for your vision. :) I love the imagetools improvements we've made so far. If we can speed up the image processing while improving our media related APIs, that sounds like a win to me, as long as it's something we can maintain support for. I'm curious to see what you've got cooking.

But yes, for this ticket, it would be sufficient to just replace `imghdr`. I think I'm superficially more attracted to `filetype`, but I don't have a strong argument in favor of it. It does seem more supported and well-known. The Go version it's based on is very popular.

**Comment by xlotlu** [comment]
> @xlotlu I'm on board for feedback and code reviews for your vision. :) [...] I'm curious to see what you've got cooking.

Let's set things up then? Wanna do it under the lektor umbrella?

> But yes, for this ticket, it would be sufficient to just replace `imghdr`. I think I'm superficially more attracted to `filetype`, but I don't have a strong argument in favor of it.

Well, I looked at this code and I liked it from the start: https://github.com/h2non/filetype.py/blob/master/filetype/types/image.py#L9

**Comment by nixjdm** [comment]
@xlotlu Sure, we can do that :) https://github.com/lektor/imageinfo, If you come up with a name you like better, we can change it before we publish it anywhere, as long as it's available on pypi. I believe you should have permissions to commit and  manage issues over there. Let me know if you have any trouble.
