### ISSUE TITLE
Improve error reporting when plugins don't catch extra_flags / **extra

### ISSUE THREAD

**Issue by nixjdm** [lektor/lektor#654]
By #652, some plugins may not be actually catching `**extra` or `extra_flags`. Since #651, they will need to. If they don't, Lektor should report a more useful error, indicating at least which plugin is causing trouble, so that it can be fixed.

**Comment by runfalk** [comment]
Couldn't we technically catch the error and call it without `extra` and/or `extra_flags` if necessary? Seems like a pretty cheap way to ensure compatibility.

**Comment by skorokithakis** [comment]
I agree with @runfalk, possibly printing a deprecation warning. If the second call fails, then we can fail completely, because it's obviously a larger problem.

**Comment by nixjdm** [comment]
Good ideas. I like the idea of adding in a deprecation warning if that's the only problem. We can include the plugin name in the warning.
