### ISSUE TITLE
Files with edits after first 4k are not elected for FTP upload.

### ISSUE THREAD

**Issue by rubenbe** [lektor/lektor#67]
When creating a one-page site, updates "mysteriously" stopped working. After a bit of digging, I saw in [lektor/publisher.py:407](https://github.com/lektor/lektor/blob/eee81a9f9a68a625a6c3d2843b3116fbae1be079/lektor/publisher.py#L407) that only the first 4k is hashed to check if an update is needed. As my changes are past this boundary, the file is never uploaded.

The most obvious fix would be to hash the entire file, but I guess the original idea was to avoid hashing very large files.

**Comment by mitsuhiko** [comment]
That's totally a bug.
