### ISSUE TITLE
Circular import in cli

### ISSUE THREAD

**Issue by apatrushev** [lektor/lektor#682]
Using cli as module is not working:
```sh
python -m lektor.cli
```
```python
Traceback (most recent call last):
  File "[python]/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "[python]/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "[venv]/lib/python3.6/site-packages/lektor/cli.py", line 615, in <module>
    from .devcli import cli as devcli  # pylint: disable=wrong-import-position
  File "[venv]/lib/python3.6/site-packages/lektor/devcli.py", line 12, in <module>
    from .cli import pass_context, AliasedGroup
  File "[venv]/lib/python3.6/site-packages/lektor/cli.py", line 615, in <module>
    from .devcli import cli as devcli  # pylint: disable=wrong-import-position
ImportError: cannot import name 'cli'
```
The reason is circular import:
https://github.com/lektor/lektor/blob/3.1.3/lektor/cli.py#L615
https://github.com/lektor/lektor/blob/3.1.3/lektor/devcli.py#L12

**Comment by runfalk** [comment]
I didn't know we had this use case, but it seems like it's intended to work: https://github.com/lektor/lektor/blob/3.1.3/lektor/cli.py#L631

**Comment by apatrushev** [comment]
> I didn't know we had this use case, but it seems like it's intended to work: https://github.com/lektor/lektor/blob/3.1.3/lektor/cli.py#L631

I just follow the blame and found command that works:
https://github.com/lektor/lektor/blame/3.1.3/lektor/cli.py#L631
https://github.com/lektor/lektor/commit/14a83b61ec3fd59c60c3e725ed88f2b4bda5ee7e

```sh
python -m lektor
```

**Comment by nixjdm** [comment]
Yes, see #523. Running it as a module is supposed to be able to help integration with pycharm, at least.  According to the associated PR this is what Flask does, at least as of the time of writing. If there's a problem here, it may be worth checking Flask.

**Comment by apatrushev** [comment]
> Yes, see #523. Running it as a module is supposed to be able to help integration with pycharm, at least. According to the associated PR this is what Flask does, at least as of the time of writing. If there's a problem here, it may be worth checking Flask.

Sorry I did not understand how the lektor cli problem is related to Flask.
And it is definitely makes this lines useless:
https://github.com/lektor/lektor/blob/3.1.3/lektor/cli.py#L631

Maybe we should just remove it?

**Comment by davidism** [comment]
Why is that line useless? That's what runs the cli when called as a module.

**Comment by apatrushev** [comment]
> Why is that line useless? That's what runs the cli when called as a module.

Because it is not working (and probably never worked as expected) as I described in original message. And the only working way is to call `lektor` itself (without `.cli`):
```sh
python -m lektor
```

**Comment by davidism** [comment]
It definitely worked as expected when I wrote it. Looking at it again, it probably is like that because Python 2 doesn't understand `__main__.py`, and Lektor doesn't have any code in `__init__.py`, so I made it work as `python -m lektor.cli` in Python 2, and `python -m lektor` in Python 3.

**Comment by apatrushev** [comment]
> It definitely worked as expected when I wrote it. Looking at it again, it probably is like that because Python 2 doesn't understand `__main__.py`, and Lektor doesn't have any code in `__init__.py`, so I made it work as `python -m lektor.cli` in Python 2, and `python -m lektor` in Python 3.

I just checked exact commit on Python 2.7.10 and it is also broken.
<details><summary>Details</summary>
<p>

```sh
$ python --version
Python 2.7.10
$ pip install https://github.com/lektor/lektor/archive/14a83b61ec3fd59c60c3e725ed88f2b4bda5ee7e.zip
...
```
```sh
$ pip list
Package      Version  
------------ ---------
argh         0.26.2   
asn1crypto   0.24.0   
Babel        2.7.0    
certifi      2019.6.16
cffi         1.12.3   
chardet      3.0.4    
Click        7.0      
cryptography 2.7      
enum34       1.1.6    
ExifRead     2.1.2    
Flask        1.1.1    
idna         2.8      
inifile      0.4      
ipaddress    1.0.22   
itsdangerous 1.1.0    
Jinja2       2.10.1   
Lektor       3.1.1    
MarkupSafe   1.1.1    
mistune      0.8.4    
pathtools    0.1.2    
pip          19.2.1   
pycparser    2.19     
pyOpenSSL    19.0.0   
pytz         2019.2   
PyYAML       5.1.2    
requests     2.22.0   
setuptools   41.0.1   
six          1.12.0   
urllib3      1.25.3   
watchdog     0.9.0    
Werkzeug     0.15.5   
wheel        0.33.4   
```
```sh
$ python -m lektor.cli
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/tosha/.local/share/virtualenvs/5218e3bc5fd1c9f5/lib/python2.7/site-packages/lektor/cli.py", line 615, in <module>
    from .devcli import cli as devcli  # pylint: disable=wrong-import-position
  File "/Users/tosha/.local/share/virtualenvs/5218e3bc5fd1c9f5/lib/python2.7/site-packages/lektor/devcli.py", line 12, in <module>
    from .cli import pass_context, AliasedGroup
  File "/Users/tosha/.local/share/virtualenvs/5218e3bc5fd1c9f5/lib/python2.7/site-packages/lektor/cli.py", line 615, in <module>
    from .devcli import cli as devcli  # pylint: disable=wrong-import-position
ImportError: cannot import name cli
```

</p>
</detail>
