### ISSUE TITLE
"No module named 'lektor'" on OS X

### ISSUE THREAD

**Issue by timkofu** [lektor/lektor#684]
I installed it with this command `curl -sf https://www.getlektor.com/install.sh | zsh`

Then on first run, I got this exception:
```
➜  ~ lektor
Traceback (most recent call last):
  File "/usr/local/bin/lektor", line 6, in <module>
    from lektor.cli import main
ModuleNotFoundError: No module named 'lektor'
```

**Comment by joksim** [comment]
Can also confirm when using linux (Manjaro latest).

Also when installing using pip as specified [here](https://www.getlektor.com/docs/installation/#pip), I'm getting the following error:

`ERROR: Can not perform a '--user' install. User site-packages are not visible in this virtualenv.`

Can't continue to install and use Lektor...

**Comment by ryentzer** [comment]
Is this an issue with zsh? I ran the same command today in a bash shell in OS X Terminal and did not have issues.

**Comment by joksim** [comment]
Output of `echo "$SHELL"` is `/bin/bash`. Using Manjaro linux (Archlinux derivative).

**Comment by runfalk** [comment]
@joksim the error message you have indicates that you have a virtualenv active. Could you check the value of `echo "$VIRTUAL_ENV"`?

**Comment by hannylicious** [comment]
I have created numerous Virtualenvironments (on MacOSX & Ubuntu linux) and been able to pip install and run sites without issue.

I can't seem to replicate these issues.

**Comment by timkofu** [comment]
This is now working for me as well https://asciinema.org/a/275862

When installed via `curl -sf https://www.getlektor.com/install.sh | sh` the error pops up, but when installed in a virtualenv it works.

**Comment by hannylicious** [comment]
So @timkofu if I'm understanding you correctly - when installing (systemwide) via the curl script it doesn't work, but when creating a virtualenv and installing it does work? When using virtualenv you're installing with pip, is that correct?

**Comment by timkofu** [comment]
@hannylicious yes. All correct.

**Comment by hannylicious** [comment]
@timkofu - I can't replicate this issue on Ubuntu, installing systemwide with Curl works without issue - as does PIP installing. I will try on a Mac OS tomorrow to see if it's specific to Mac. Which version of OSX are you on?

**Comment by timkofu** [comment]
@hannylicious Catalina

**Comment by hannylicious** [comment]
I am not on Catalina yet, because of the issues I had read about various applications struggling greatly.

However, I can confirm that installing via curl on OSX pre-Catalina works without issue.

I've been unable to replicate this on Mac OS-x pre Catalina or Ubuntu Linux using Pip installs or installing via Curl.

It sounds to me like it's a setup issue particular to your machines.

**Comment by timkofu** [comment]
@hannylicious Alright. Using it via a venv is working, so I'll go ahead and close the issue.
