### ISSUE TITLE
A file deleted and re-created won't be built

### ISSUE THREAD

**Issue by vindarel** [lektor/lektor#69]
I created a quickstart project, deleted the `layout.html` and re-created it, but it wasn't taken into account by the build system any more. In the browser, I simply had "TemplateNotFound: layout.html".

I had to delete the cached build.

I was expecting the file to be rebuilt so I think that's a bug :]

(note: I noticed something similar when I comment and uncomment comments in some html, which can lead to remaining problems if this breaks jinja tags).

**Comment by mitsuhiko** [comment]
@vindarel not at all (even when issuing `build` manually or heading to the page) or was it just not picked up by the watcher?

**Comment by mitsuhiko** [comment]
I know that the watcher does not detect such things but it will rebuild still if you load the page in the browser, if you manually invoke build or if you restart the dev server.

**Comment by vindarel** [comment]
Hi Armin, it didn't rebuild either when I loaded the page in the browser nor when I restarted the dev server. It's ok with the build command.

**Comment by mitsuhiko** [comment]
@vindarel In case you feel like it, can you try to see if the development version of Lektor behaves better?  I did some potential improvements on this and I tried on there and could not reproduce the issue there.

**Comment by vindarel** [comment]
The development version behaves better. I couldn't reproduce the issue with git's master, v2.0.dev either. Great !
