### ISSUE TITLE
Builtin not defined, UndefinedError: 'int' is undefined

### ISSUE THREAD

**Issue by relikd** [lektor/lektor#697]
Hi there,
I want to convert a unicode string to an integer but can't seem to do so.

```
<span>{{ int(this.time) // 60 }}</span>
-> (UndefinedError: 'int' is undefined)
```

This is my data model:

```
[fields.time]
label = Time
width = 1/8
type = select
choices = 5, 10, 15, 20, 30, 45, 60, 90
choice_labels = 5m, 10m, 15m, 20m, 30m, 45m, 1h, 1h 30m
```

Alternatively, a select type could have a type for the choices (related to https://github.com/lektor/lektor/pull/675?).

Also, is there a way to get the choice label instead of the choice value? I'd like to display the label on my webpage and use the integer-value for sorting etc.

**Comment by runfalk** [comment]
Hi there!

Lektor uses Jinja as its templating engine which doesn't have an `int` function built in. It does however expose the exact same thing as a filter (https://jinja.palletsprojects.com/en/2.10.x/templates/#int):

```html+jinja
<span>{{ this.time|int // 60 }}</span>
```

You can read more about filters in the Jinja documentation (https://jinja.palletsprojects.com/en/2.10.x/templates/#filters).

I don't know if you can access labels.

**Comment by xlotlu** [comment]
> Alternatively, a select type could have a type for the choices (related to #675?).

What you want is #625.
 
> Also, is there a way to get the choice label instead of the choice value? I'd like to display the label on my webpage and use the integer-value for sorting etc.

Aand #558. Sorry... :)
