### ISSUE TITLE
Markdown ordered lists broken </ol>

### ISSUE THREAD

**Issue by relikd** [lektor/lektor#708]
Hi there, I have a model with one of the fields being of type markdown.
Somehow, the content is not converted properly to HTML.

Input:
```
1. one
2. 2°C
3. three

continue text
```

Output:
```
<ol><p></p>
<p></p><li>one</li><p></p>
<p></p><li>2℃</li><p></p>
<p></p><li>three</li>
&lt;/ol&gt;<p></p>
<p>continue text</p>
</ol>
```

The problem arises when converting to string and back to markdown:
```
{{ this.directions|replace('°C', '℃')|replace('°F', '℉')|markdown }}
```

Leaving out `|markdown` will print the proper (escaped) HTML.
However, converting it back to markdown does not seem to work properly.

**Comment by relikd** [comment]
Found a workaround solution by accessing the `html` property. `this.directions.html|replace('°C', '℃')|replace('°F', '℉')`

**Comment by runfalk** [comment]
I think this is probably because it's double encoded. I assume `directions` is defined as a markdown field. This means that the value you are filtering is already HTML. I think you could also have done:

```jinja2
{{ this.directions.source|replace('°C', '℃')|replace('°F', '℉')|markdown }}
```

I'm closing this issue, but feel free to re-open it if your problem is not solved.
