### ISSUE TITLE
Allow relative urls abbreviated when they are on the same level

### ISSUE THREAD

**Issue by relikd** [lektor/lektor#713]
Can we have relative URLs that do not always go to the lowest folder and then back up again?

For example if I browse the following page:
`/articles/2019/07/brownies`
which has a subpage I would like to link to:
`/articles/2019/07/brownies/image-gallery`

The resulting relative url will be:
`../../../../articles/2019/07/brownies/image-gallery/`
instead of just:
`image-gallery/`

Also linking to any other resource may be shorter (e.g., same folder):
`../chocolate-cake/`

**Comment by runfalk** [comment]
I don't see why we can't do this. PRs are welcome.

**Comment by relikd** [comment]
I get an error on macOS:
```
$ make install-git-hooks
ln -sT [...]/lektor/bin/pre-commit .git/hooks/pre-commit
ln: illegal option -- T
```

**Comment by runfalk** [comment]
You can probably remove the T flag in https://github.com/lektor/lektor/blob/master/Makefile#L43 as a work around. It's probably a GNU extension:

```
-T, --no-target-directory
       treat LINK_NAME as a normal file always
```

**Comment by relikd** [comment]
Already did, PR is ready
