### ISSUE TITLE
Installer broken with virtualenv 20.x

### ISSUE THREAD

**Issue by mthuurne** [lektor/lektor#720]
I tried installing Lektor on Linux via the installer script at `https://www.getlektor.com/install.sh`. This resulted in the following error messages:
```
/usr/bin/python: can't open file './src/virtualenv.py': [Errno 2] No such file or directory
/usr/bin/python: can't open file './virtualenv.py': [Errno 2] No such file or directory
```
It seems the internal structure of the `virtualenv` package changed again. If I modify the installer script to force an older version of virtualenv, it works again:
```py
VENV_URL = "https://pypi.org/pypi/virtualenv/16.7.9/json"
```

**Comment by davidism** [comment]
It's no longer a single py file, but it can still be downloaded as a zipapp if Lektor needs a single file: https://virtualenv.pypa.io/en/stable/installation.html#via-zipapp

**Comment by freezed** [comment]
Is there any reason not to make a PR with @mthuurne  modification ?

**Comment by mthuurne** [comment]
My modification is a workaround that is useful if you want to install Lektor right now, but it's not a good long term solution. The zipapp approach suggested by @davidism is a much better basis for a PR.

**Comment by goanpeca** [comment]
@mthuurne agreed, but given the current issues  I would suggest you created a PR to fix the issue?

**Comment by kodmasin** [comment]
Hi, I just created patch (in attachment) for install.sh to use virtualenv zipapp, installation worked, next days I will check is installed Lektor working.
[install.patch.gz](https://github.com/lektor/lektor/files/4333640/install.patch.gz)

**Comment by davidism** [comment]
Here's the patch not as a mysterious gzip ;-)

```patch
--- install.sh	2018-12-04 20:01:31.000000000 +0100
+++ install.sh.my	2020-03-15 01:06:46.227843000 +0100
@@ -36,7 +36,7 @@
 
     sys.stdin = open('/dev/tty', 'r')
 
-    VENV_URL = "https://pypi.python.org/pypi/virtualenv/json"
+    VENV_URL = "https://bootstrap.pypa.io/virtualenv.pyz"
     KNOWN_BINS = ['/usr/local/bin', '/opt/local/bin',
                   os.path.join(os.environ['HOME'], '.bin'),
                   os.path.join(os.environ['HOME'], '.local', 'bin')]
@@ -114,17 +114,14 @@
 
     def install(virtualenv_url, lib_dir, bin_dir):
         t = tempfile.mkdtemp()
-        Popen('curl -sf "%s" | tar -xzf - --strip-components=1' %
+        Popen('wget "%s"' %
               virtualenv_url, shell=True, cwd=t).wait()
 
         try:
             os.makedirs(lib_dir)
         except OSError:
             pass
-        try:  # virtualenv 16.1.0, 17+
-            check_output([sys.executable, './src/virtualenv.py', lib_dir], cwd=t)
-        except CalledProcessError:  # older virtualenv
-            Popen([sys.executable, './virtualenv.py', lib_dir], cwd=t).wait()
+        Popen([sys.executable, './virtualenv.pyz', lib_dir], cwd=t).wait()
         Popen([os.path.join(lib_dir, 'bin', 'pip'),
            'install', '--upgrade', 'Lektor']).wait()
         os.symlink(os.path.join(lib_dir, 'bin', 'lektor'),
@@ -155,14 +152,7 @@
 
         if prompt: get_confirmation()
 
-        for url in json.loads(urlopen(VENV_URL).read().decode('utf-8'))['urls']:
-            if url['python_version'] == 'source':
-                virtualenv = url['url']
-                break
-        else:
-            fail('Could not find virtualenv')
-
-        install(virtualenv, lib_dir, bin_dir)
+        install(VENV_URL, lib_dir, bin_dir)
 
         print('')
         print('All done!')
```

**Comment by mthuurne** [comment]
Why the switch from `curl` to `wget`? Is there a reason this wouldn't work with `curl`? Otherwise, it seems that such a change should not be combined with this fix and instead be submitted as a separate patch.

On the topic of fetching files, would it be an option to use [`urllib.urlretrieve()`](https://docs.python.org/2/library/urllib.html#urllib.urlretrieve) (Python 2) and [`urllib.request.urlretrieve()`](https://docs.python.org/3/library/urllib.request.html#urllib.request.urlretrieve) (Python 3) instead? Then there is no dependency on a command line utility.

The rest looks good; thanks!

**Comment by kodmasin** [comment]
No reason except I am more familiar with wget. Here is curl version:

```patch
--- install.sh	2020-03-16 00:31:08.799577500 +0100
+++ /mnt/e/programs/lektor/install.sh	2020-03-16 00:28:00.551836200 +0100
@@ -36,7 +36,7 @@
 
     sys.stdin = open('/dev/tty', 'r')
 
-    VENV_URL = "https://pypi.python.org/pypi/virtualenv/json"
+    VENV_URL = "https://bootstrap.pypa.io/virtualenv.pyz"
     KNOWN_BINS = ['/usr/local/bin', '/opt/local/bin',
                   os.path.join(os.environ['HOME'], '.bin'),
                   os.path.join(os.environ['HOME'], '.local', 'bin')]
@@ -114,17 +114,14 @@
 
     def install(virtualenv_url, lib_dir, bin_dir):
         t = tempfile.mkdtemp()
-        Popen('curl -sf "%s" | tar -xzf - --strip-components=1' %
+        Popen('curl -O "%s"' %
               virtualenv_url, shell=True, cwd=t).wait()
 
         try:
             os.makedirs(lib_dir)
         except OSError:
             pass
-        try:  # virtualenv 16.1.0, 17+
-            check_output([sys.executable, './src/virtualenv.py', lib_dir], cwd=t)
-        except CalledProcessError:  # older virtualenv
-            Popen([sys.executable, './virtualenv.py', lib_dir], cwd=t).wait()
+        Popen([sys.executable, './virtualenv.pyz', lib_dir], cwd=t).wait()
         Popen([os.path.join(lib_dir, 'bin', 'pip'),
            'install', '--upgrade', 'Lektor']).wait()
         os.symlink(os.path.join(lib_dir, 'bin', 'lektor'),
@@ -155,14 +152,7 @@
 
         if prompt: get_confirmation()
 
-        for url in json.loads(urlopen(VENV_URL).read().decode('utf-8'))['urls']:
-            if url['python_version'] == 'source':
-                virtualenv = url['url']
-                break
-        else:
-            fail('Could not find virtualenv')
-
-        install(virtualenv, lib_dir, bin_dir)
+        install(VENV_URL, lib_dir, bin_dir)
 
         print('')
         print('All done!')
```
Here is simple urlretrieve version also but it does not show download progress (for that it will be more complicated to solve python2/3 comaptibility issues):

```patch
--- install.sh	2020-03-15 23:50:37.555242800 +0100
+++ /mnt/e/programs/lektor/install.sh	2020-03-15 23:47:40.352555700 +0100
@@ -26,9 +26,9 @@
     import shutil
     from subprocess import CalledProcessError, check_output, Popen
     try:
-        from urllib.request import urlopen
+        from urllib.request import urlopen, urlretrieve
     except ImportError:
-        from urllib import urlopen
+        from urllib import urlopen, urlretrieve
 
     PY2 = sys.version_info[0] == 2
     if PY2:
@@ -36,7 +36,7 @@
 
     sys.stdin = open('/dev/tty', 'r')
 
-    VENV_URL = "https://pypi.python.org/pypi/virtualenv/json"
+    VENV_URL = "https://bootstrap.pypa.io/virtualenv.pyz"
     KNOWN_BINS = ['/usr/local/bin', '/opt/local/bin',
                   os.path.join(os.environ['HOME'], '.bin'),
                   os.path.join(os.environ['HOME'], '.local', 'bin')]
@@ -113,18 +113,26 @@
         sys.exit(1)
 
     def install(virtualenv_url, lib_dir, bin_dir):
-        t = tempfile.mkdtemp()
-        Popen('curl -sf "%s" | tar -xzf - --strip-components=1' %
-              virtualenv_url, shell=True, cwd=t).wait()
+	print('')
+	print("Fetching virtualenv ...")
+	urlfile = urlretrieve(VENV_URL)
+	print('')
+	print("virtualenv fetched")
+	t, vefile =os.path.split(urlfile[0])
 
         try:
             os.makedirs(lib_dir)
         except OSError:
             pass
-        try:  # virtualenv 16.1.0, 17+
-            check_output([sys.executable, './src/virtualenv.py', lib_dir], cwd=t)
-        except CalledProcessError:  # older virtualenv
-            Popen([sys.executable, './virtualenv.py', lib_dir], cwd=t).wait()
+	print('')
+	print("Creating Lektor virtualenv ...")
+	print('')
+        Popen([sys.executable, vefile, lib_dir], cwd=t).wait()
+	print('')
+	print("virtualenv created")
+	print('')
+	print("installing Lektor ...")
+	print('')
         Popen([os.path.join(lib_dir, 'bin', 'pip'),
            'install', '--upgrade', 'Lektor']).wait()
         os.symlink(os.path.join(lib_dir, 'bin', 'lektor'),
@@ -155,14 +163,7 @@
 
         if prompt: get_confirmation()
 
-        for url in json.loads(urlopen(VENV_URL).read().decode('utf-8'))['urls']:
-            if url['python_version'] == 'source':
-                virtualenv = url['url']
-                break
-        else:
-            fail('Could not find virtualenv')
-
-        install(virtualenv, lib_dir, bin_dir)
+        install(VENV_URL, lib_dir, bin_dir)
 
         print('')
         print('All done!')
```

I just tested this with python2 so I am not sure is it working with python3

**Comment by xlotlu** [comment]
> My modification is a workaround that is useful if you want to install Lektor right now, but it's not a good long term solution. The zipapp approach suggested by @davidism is a much better basis for a PR.

Actually, I think pinning the version is the right thing to do, and of course getting a procedure in place to handle upgrades. This was also discussed under https://github.com/lektor/lektor/pull/734/ in the context of pinning pylint. @lektor/developers what do you think?

(That is pinning the version *and* fixing for virtualenv 20.*)

**Comment by mthuurne** [comment]
> Here is simple urlretrieve version also but it does not show download progress (for that it will be more complicated to solve python2/3 comaptibility issues):

The `virtualenv.pyz` is a lot larger than I realized at first (since it contains for example two versions of `pip`), so indeed a progress indicator may be useful.

I wrote a [pure Python download function with progress indicator](https://github.com/openMSX/openMSX/blob/master/build/download.py#L35) a while back, feel free to use that (openMSX as a whole is under GPL2 but as the author of that particular routine I'm fine with dual-licensing it under BSD). The current version is for Python 3, but if you go back a few months in Git history you can also find the Python 2 version.

**Comment by mthuurne** [comment]
> > My modification is a workaround that is useful if you want to install Lektor right now, but it's not a good long term solution. The zipapp approach suggested by @davidism is a much better basis for a PR.
> 
> Actually, I think pinning the version is the right thing to do, and of course getting a procedure in place to handle upgrades. This was also discussed under #734 in the context of pinning pylint. @lektor/developers what do you think?
> 
> (That is pinning the version _and_ fixing for virtualenv 20.*)

I'm a Lektor user instead of developer, but I'll give my opinion anyway.

Pinning a version would avoid breakage when the interface changes, such as it did in virtualenv 20, but it also means that fixes done in virtualenv won't automatically be incorporated and that could also break Lektor's installation when for example an OS or Python changes in an incompatible way. In my opinion, what is the best approach depends on how stable the interface is.

Originally the installer script did not use an official interface, so it's really not surprising that it would break at some point. The bootstrap zipapp is an official and documented way of installing virtualenv, so that should be a lot less prone to breaking between virtualenv releases.

**Comment by xlotlu** [comment]
> I'm a Lektor user instead of developer, but I'll give my opinion anyway. Pinning a version would avoid breakage when the interface changes, such as it did in virtualenv 20

This is not the first time this happened. Virtualenv updates broke installer scripts for many-a-project before.

> but it also means that fixes done in virtualenv won't automatically be incorporated and that could also break Lektor's installation when for example an OS or Python changes in an incompatible way.

Hence the need for a procedure to follow updates and apply them. That'd be the difference between us pushing a tested commit vs. some 3rd party change blowing up in our faces. This needs to be done anyway for pylint, which every now and then breaks CI for very silly reasons.

> Originally the installer script did not use an official interface, so it's really not surprising that it would break at some point. The bootstrap zipapp is an official and documented way of installing virtualenv, so that should be a lot less prone to breaking between virtualenv releases.

True..

**Comment by runfalk** [comment]
It doesn't seem like we can pin `virtualenv.pyz` if I understand things correctly (https://virtualenv.pypa.io/en/latest/installation.html#via-zipapp). It seems you can tell it which python version you want the latest release for, but not pin the version itself. I think it's OK to switch to the zipapp and get the one for the current version and if that 404s try the generic one.

Later we can set up a scheduled CI job that tries to install using this method to check for regressions.

**Comment by xlotlu** [comment]
> It doesn't seem like we can pin `virtualenv.pyz`

IIRC virtualenv only ever blew up because they changed the location of the executable. That won't be a problem with a zipapp.

> I think it's OK to switch to the zipapp and get the one for the current version and if that 404s try the generic one.

That's two branches of code, then there would need to be that pinning logic and procedure... not worth it since the zipapp is the official bootstrap method and that's the official URL. So yeah, I changed my opinion, sorry for the noise. I think we should go forward with the zipapp way and forget about legacy.

> Later we can set up a scheduled CI job that tries to install using this method to check for regressions.

That would be nice.

**Comment by goanpeca** [comment]
Anyone up for making a PR?

**Comment by xlotlu** [comment]
> Anyone up for making a PR?

I'll do it.

**Comment by xlotlu** [comment]
Guys, on windows the installer uses the built-in `venv` module when possible: [install.ps1#L114](https://github.com/lektor/lektor-website/blob/master/assets/install.ps1#L114).

I approve of this (that may well be because I did that change (I think)). What's your opinion? The only downside I see is on debian / ubuntu, which don't ship with `ensurepip` bundled (which `venv` uses). If they don't have python3-pip installed it's gonna prompt them to install it and exit.

**Comment by runfalk** [comment]
That assumes a system with Python 3 right? AFAIK macOS still only ships with Python 2.7, and I think we should consider that a supported platform since Lektor 3.2 will still support it. I'm fine with deprecating it later and switching to venv though.

**Comment by mthuurne** [comment]
If I understand the [macOS 10.15 release notes](https://developer.apple.com/documentation/macos_release_notes/macos_catalina_10_15_release_notes) correctly, they're switching from shipping with Python 2.7 to shipping with no Python at all. Assuming that happens in macOS 10.16, a Python 2.7 based installer will only work for about half a year.

**Comment by xlotlu** [comment]
> That assumes a system with Python 3 right?
> I think we should consider that a supported platform

Yes, it's available since 3.3. If `import venv` fails that would default to the old fetch-and-run thing, of course.

> a Python 2.7 based installer will only work for about half a year

Well, that's moot until we officially stop supporting 2.7. Anyway, the code is already written, and might also apply in who-knows-what-cornercase.

I'm more interested in feedback on the debian / ubuntu situation. A correction to my previous statement: on these it will fail if `python3-venv` is not installed, not `python3-pip`, and that's a rather likely scenario. This is the output one would get:

```
The virtual environment was not created successfully because ensurepip is not
available.  On Debian/Ubuntu systems, you need to install the python3-venv
package using the following command.

    apt-get install python3-venv

You may need to use sudo with that command.  After installing the python3-venv
package, recreate your virtual environment.

Failing command: ['/tmp/venv/bin/python3', '-Im', 'ensurepip', '--upgrade', '--default-pip']
```

The question is, do we want to let them get prompted to install the dependency (we could improve on the message above), or should we stay silent and go the download route? Personally, I have mixed feelings about this: the user experience is rather ugly, and debian+ubuntu probably make for most of the linux installs. On the other hand, that download is *really* large (and occasionally quite slow, I have discovered).

**Comment by mthuurne** [comment]
The `python3-venv` package in Debian buster is [nearly empty](https://packages.debian.org/buster/amd64/python3-venv/filelist); it seems it exists to keep old package dependency declarations working and to add the `pyvenv` command line tool.

**Comment by mthuurne** [comment]
> > a Python 2.7 based installer will only work for about half a year
> 
> Well, that's moot until we officially stop supporting 2.7. Anyway, the code is already written, and might also apply in who-knows-what-cornercase.

My point wasn't about whether Lektor supports 2.7, but that if the Lektor installer depends on Python 2.7 being pre-installed on macOS, that is likely going to break in with the next macOS release.

**Comment by xlotlu** [comment]
> The `python3-venv` package in Debian buster is [nearly empty](https://packages.debian.org/buster/amd64/python3-venv/filelist); it seems it exists to keep old package dependency declarations working and to add the `pyvenv` command line tool.

Nope, it provides `ensurepip` [via dependency](https://packages.debian.org/sid/amd64/python3.8-venv/filelist). And ships with a [modified stdlib](https://sources.debian.org/patches/python3.8/3.8.2-1/ensurepip-disabled.diff/
) to account for this.

> My point wasn't about whether Lektor supports 2.7, but that if the Lektor installer depends on Python 2.7 being pre-installed on macOS, that is likely going to break in with the next macOS release.

It doesn't depend on py2.7 being installed, it, well, depends on python being installed. ... d'oh... :)

**Comment by mthuurne** [comment]
> > The `python3-venv` package in Debian buster is [nearly empty](https://packages.debian.org/buster/amd64/python3-venv/filelist); it seems it exists to keep old package dependency declarations working and to add the `pyvenv` command line tool.
> 
> Nope, it provides `ensurepip` [via dependency](https://packages.debian.org/sid/amd64/python3.8-venv/filelist). And ships with a [modified stdlib](https://sources.debian.org/patches/python3.8/3.8.2-1/ensurepip-disabled.diff/) to account for this.

So they changed it after the buster release, good to know.

> > My point wasn't about whether Lektor supports 2.7, but that if the Lektor installer depends on Python 2.7 being pre-installed on macOS, that is likely going to break in with the next macOS release.
> 
> It doesn't depend on py2.7 being installed, it, well, depends on python being installed. ... d'oh... :)

Well, it has the upside that the Lektor installer doesn't need to stay 2.7 compatible just for the sake of macOS. The downside is that macOS is going to need a different installer strategy in the near future.

I'm starting to wonder if it would be more efficient to create easy to use installers for `pipx` on every platform instead of for individual applications.

**Comment by xlotlu** [comment]
> So they changed it after the buster release, good to know.

No, it's like that since ever: https://packages.debian.org/jessie/amd64/python3.4-venv/filelist

> The downside is that macOS is going to need a different installer strategy in the near future.

Not really, the installer says "you need python to run this" for all platforms. We could provide platform-specific instructions for installing, but that's a future improvement.

>  more efficient to create easy to use installers for pipx on every platform

That's a good plan, but maybe in addition to this, not as replacement.

**Comment by mthuurne** [comment]
> > So they changed it after the buster release, good to know.
> 
> No, it's like that since ever: https://packages.debian.org/jessie/amd64/python3.4-venv/filelist

Ah, `python3-venv` in buster depends on `python3.7-venv` which is indeed where the `ensurepip` module is packaged.

> > more efficient to create easy to use installers for pipx on every platform
> 
> That's a good plan, but maybe in addition to this, not as replacement.

I agree that in the short term, getting the Lektor installer fixed would be best. But a lot of Python applications need an installer, so in the long term they can save effort by adopting a shared installer and `pipx` seems to be the prime candidate for that.

**Comment by davidism** [comment]
I'd encourage dropping the custom installers and Mac package in favor of pipx, at least for now. Lektor is a site generator, the focus right now should be in getting that updated and released. Let a project focused on installing Python applications solve that problem.

Also, since you're discussing Python 2, I'd encourage dropping that and Python 3.5. Remaining compatible brings in a bunch of little complexities and mental overhead. PyPI stats show you have about 70% py3, and I have a feeling most people using Lektor with 2 have 3 available and the installer defaulted to 2.

**Comment by runfalk** [comment]
We will drop Python 2, but we'll make one last release for it. I don't think we should drop the installer before that.

@xlotlu I think it's fine to display that error message on Debian/Ubuntu. People running those are usually savvy enough to follow on screen instructions.

**Comment by xlotlu** [comment]
If any of you guys wants to take a stab at #741, feedback is welcome.
