### ISSUE TITLE
ModuleNotFoundError: No module named 'werkzeug.contrib'

### ISSUE THREAD

**Issue by animeshkrishnabulusu** [lektor/lektor#721]
Yesterday on my windows machine, I have removed Python 2.7.16 from my machine and installed Python 3.8.1 and reinstalled Lektor 3.1.3.

Then I try to run lektor clean, I got this error 

    ModuleNotFoundError: No module named 'werkzeug.contrib'
	
I have following plugins

	lektor-atom = 0.2
	lektor-minify = 1.2

I have reinstalled Lektor with the powershell command:

	iex ((new-object net.webclient).DownloadString('https://getlektor.com/install.ps1'))

Link to the full output of clean command -> https://gist.github.com/animeshb/16e1cbc5ba4e06279af153a2f53409f5

I have also tried to 

1. install Werkzeug==1.0.0 with pip. Still the same error.
1. use lektor-atom 0.3. No luck.

**Comment by davidism** [comment]
`werkzeug.contrib` had been deprecated for some time and is now removed. You can downgrade to Werkzeug 0.16.1 if you have plugins that use removed code, or you can try contributing to those projects to get them updated.

* lektor-atom tracking issue: https://github.com/nixjdm/lektor-atom/issues/23
* lektor-minify does not appear to use any deprecated code.

**Comment by animeshkrishnabulusu** [comment]
I installed Werkzeug 0.16.1 with pip and immediately run `lektor clean` and got the same error.

Does installing with the following command in the folder where the lektor website project not install it where lektor command can see it?

    pip install Werkzeug==0.16.1

**Comment by davidism** [comment]
I don't know enough about the Lektor custom installer to say. I use [pipx](https://pipxproject.github.io/pipx/) to manage global Python commands and their virtualenvs.

**Comment by animeshkrishnabulusu** [comment]
I will look into the issue to gain some understanding. Thanks for the link to the appropriate issue.

**Comment by ghost** [comment]
I have the same problem on my Windows 10 system and on the Travis-CI build (ubuntu 16.04).
- tried to use **python 3.7** but this had the same effect
- played around with the versions (my lektor project was about 2 years old) but no changes.
- created a new vector project 
> still the same issue

The problem with the downgrading to werkzeug==0.16.1 is not as easy as it sounds. The install is called from the scripts and a simple `pip install` or `requirements.txt` will not have the right effect.

> removing the plugins does not work

I will now investigate the issue with the lektor-homepage project iste

**Comment by yagebu** [comment]
This has been fixed in the dev branches of lektor and lektor-atom ages ago
