### ISSUE TITLE
Switching to GitHub actions

### ISSUE THREAD

**Issue by runfalk** [lektor/lektor#733]
Currently we use both Travis and Appveyor. I think we should consider moving to GitHub actions which is completely free for all open source projects. I also see this as an opportunity to optimize the CI process a bit. The current one has some problems (not all are related to Travis and Appveyor):

* JS is built for all Python versions even though we never use it for the tests
* Windows tests are slow because they can't run in parallel
* We have no macOS tests, which would probably be a requirement to start building dmg files again
* Linting is run for every single Python version which is completely unnecessary and takes some time

My suggestion is to split the build into many different stages where the first stage runs lints, the second builds JS and runs tests using different Node versions and the last step would run different Python version on different platforms.

Anyone who have negative experiences with GitHub actions or are concerned about moving to it?

**Comment by goanpeca** [comment]
@runfalk no negative experiences at all. In fact I am in the process of moving all the CI for the Spyder organization to Github Actions.

I have created custom actions and this one as well: https://github.com/marketplace/actions/setup-miniconda

I can work on this, this weekend :-)

Any other things you have in mind for this ?

**Comment by goanpeca** [comment]
>My suggestion is to split the build into many different stages where the first stage runs lints, the second builds JS and runs tests using different Node versions and the last step would run different Python version on different platforms.

Yes, pretty much what I had in mind!
