### ISSUE TITLE
allow us to [skip ci]

### ISSUE THREAD

**Issue by xlotlu** [lektor/lektor#742]
title says it all

**Comment by runfalk** [comment]
Is there a situation when this is needed? We don't block merges based on CI right?

**Comment by xlotlu** [comment]
> We don't block merges based on CI right?
We probably should I guess, but that's not the idea.

> Is there a situation when this is needed

We don't "need it", need it. It would be nice to have, for small / intermediary commits waiting for review, or something that's isolated and doesn't even have tests. Like during #741 where all commits will be squashed, rebased and forced pushed anyway. Running CI is a waste of resources. And an ominous section in the middle of the PR page. :)

**Comment by goanpeca** [comment]
See: https://github.community/t5/GitHub-Actions/GitHub-Actions-does-not-respect-skip-ci/td-p/42834

**Comment by runfalk** [comment]
I think I'm more in favor of better skipping conditions in the default CI loop than allowing `[skip ci]`. There is no need for JS tests i only Python was changed and vice versa.

The positive thing I see is less wasted resources and less vertical height on the PR-page. On the flip side we risk merging commits that doesn't comply with code style or linting or have broken tests without us knowing it

**Comment by goanpeca** [comment]
>I think I'm more in favor of better skipping conditions in the default CI loop than allowing [skip ci]. There is no need for JS tests i only Python was changed and vice versa.

Will add a simple check for this for both .py and .js files so we do not trigger tests that do not change those files.

If no JS, PY files are changed at all, then I can also add a skip to it 🤷‍♂

**Comment by yagebu** [comment]
Looking at b9ecb4013b07d6b5fe663167ad8a39949c7cb6fb, which didn't trigger CI, this seems to just work now :)
