### ISSUE TITLE
Broken CI: Mac py3.8 tests

### ISSUE THREAD

**Issue by yagebu** [lektor/lektor#759]
The Mac py3.8 tests GH action is broken:

https://github.com/lektor/lektor/runs/598104831
https://github.com/lektor/lektor/pull/758/checks?check_run_id=612685216

**Comment by runfalk** [comment]
I've opened an issue here: https://github.com/actions/setup-python/issues/83

I suspect it may not be on our end, and I don't know how we can work around it right now.

**Comment by yagebu** [comment]
It started working again, so I'll close this issue :)

**Comment by runfalk** [comment]
Interesting, a bit annoying that the build can break and fix itself automatically.
