### ISSUE TITLE
Rsync deployment not removing existing files from target

### ISSUE THREAD

**Issue by dkaparis** [lektor/lektor#761]
Rsync deployment seems to only upload generated files and not remove existing files on target.
This way, e.g. removed files from previous deployments may go stale and remain on target server.
I would expect the target directory to be cleaned and only newly generated files by the project to be present after deployment.

To this end, probably the --delete option should be passed to rsync command.

**Comment by xlotlu** [comment]
This is fixed in master, and it's documented here: https://github.com/lektor/lektor-website/commit/ae4d6bb0fcceaa4c895e6d0d7b1c21c2954e63d3
