### ISSUE TITLE
lektor server couldn't start

### ISSUE THREAD

**Issue by evilangel-ru** [lektor/lektor#765]
I installed lektor with workaround script from #763 But when I tried to run `lektor server` there is an error:

```
lektor server
 * Project path: /Volumes/My Book/Documents/Code/binba.se/lektor/lektor.lektorproject
 * Output path: /Users/dubov/Library/Caches/Lektor/builds/95ed12141f4c837acc693a154f1ca30b
Traceback (most recent call last):
  File "/usr/local/lib/lektor/lib/python2.7/site-packages/lektor/devserver.py", line 44, in build
    extra_flags=self.extra_flags)
  File "/usr/local/lib/lektor/lib/python2.7/site-packages/lektor/builder.py", line 980, in __init__
    con = self.connect_to_database()
  File "/usr/local/lib/lektor/lib/python2.7/site-packages/lektor/builder.py", line 1015, in connect_to_database
    cur.execute('pragma journal_mode=WAL')
  File "/usr/local/lib/lektor/lib/python2.7/site-packages/lektor/builder.py", line 1013, in <lambda>
    con.text_factory = lambda x: x.decode(system_encoding, 'ignore')
TypeError: decode() argument 1 must be string, not None
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)```

**Comment by runfalk** [comment]
This looks similar to https://github.com/lektor/lektor/issues/740. Could you attach your environment variables like I asked in that issue thread?

**Comment by evilangel-ru** [comment]
Yes, it similar. In my case it was connected with zsh. I added LANG=en_US.UTF-8 in my .zshrc and it helps. Sorry for disturbing

**Comment by runfalk** [comment]
I'll reopen this since I think we should have a better (or no) error message because of this.

**Comment by dairiki** [comment]
We have dropped the installation script in favor of installing via `pipx` (see #915 and lektor/lektor-website#325).
I'm closing this issue because I believe it is no longer pertinent.  If it's still a problem, feel free to reopen.
