### ISSUE TITLE
filetype==1.0.7 breaks get_image_info()

### ISSUE THREAD

**Issue by dairiki** [lektor/lektor#767]
In version 1.0.7, `filetype` renames `filetype.image` to `filetype.image_match` (h2non/filetype.py@e7babc0).  That breaks [this line][2] in `lektor.imagetools.get_image_info`.

Since this rename happened without so much as a minor version bump from `filetype`, I guess `filetype.image` is not considered part of the public API of the `filetype` package.  It looks like the intended public API is through `filetype.match`.

I haven't tested this, but I think replacing `filetype.image(...)` with `filetype.match(..., matchers=filetype.image_matchers)` might do the trick.

[2]: <https://github.com/lektor/lektor/blob/04509f83319472e883e5b04ab7c530263743e343/lektor/imagetools.py#L335>

**Comment by xlotlu** [comment]
@dairiki thanks. I simply renamed the function in the PR. Hopefully that will stay stable, maybe this will convince the filetype dev(s): https://github.com/h2non/filetype.py/issues/64.
