### ISSUE TITLE
Remove obsolete desktop app code

### ISSUE THREAD

**Issue by xlotlu** [lektor/lektor#774]
I propose we remove `/gui` entirely from the code base. We could `git filter-branch` it to a new repo, mostly for inspirational purposes, I doubt someone will reuse the code.

Right now it's dead weight, its only purpose to give the bot a reason to annoy us. #737 #738 #771.

**Comment by yagebu** [comment]
:+1: from me.

> We could git filter-branch it to a new repo

I think having it still in the history (and available with `git checkout 3.1.3` for example) should be enough (and hide it a bit better so that no one will get the impression that it's working)

**Comment by runfalk** [comment]
:+1: from me as well.

I agree that checking out an older version should be enough. I don't think there is that much left that we want to reuse anyway.
