### ISSUE TITLE
Implement schedule post

### ISSUE THREAD

**Issue by ikus060** [lektor/lektor#779]
I'm asking for a new feature on Lektor to manage scheduled post. 

Here the scenario. I have a website built with Lector. And I want to create my blog post in advance and define a good publication date. That date could be the 'pub_date'. When I compile luckily I want to see all the pages. When I compile for the final publication I want those future post to be excluded from the build. A nice way to make it work will be using the current date.

This way I can automate the bill process to happen everyday using a Cron job. And it will automatically publish my post.

**Comment by goanpeca** [comment]
Hi @ikus060, thanks for your suggestion. Although you have phrased in terms of a blog post (a very specific case) I do see value in having a publish date for any time of page.

@lektor/developers do you think this is useful and common enough to make part of lektor or is this something that should ve provided by an external plugin?

Thoughts?

**Comment by xlotlu** [comment]
I think this is a useful feature, but too opinionated to belong in core. Coming up with a field name that means "will only publish in the future" is bad enough, hardcoding conditional publishing logic is even worse.

But core should provide the components needed for such a plugin, and afaik currently we have neither of these:
 - different publishing environments - see #503
 - the ability to mask an artefact / content item, based on specific conditions.

**Comment by runfalk** [comment]
I think this is something you should do as part of your model/templates. I definitely appreciate your use-case and have needed something similar in the past. I agree with @xlotlu that it is too opinionated to be part of Lektor core. I think we could have a "recipe" for it though so people can add it themselves if they'd like.

If I was to implement something similar I would add a pub_date field to my posts, and then switch the page children query for the post list to hide the page if the pub_date hasn't happened yet. For local builds you could override it by adding a configuration setting or one of the suggested workarounds in #503. Would that be good enough for you?

**Comment by ikus060** [comment]
I was looking for something similar with a custom "children" query. But I'm not sure it's possible to make it work since we don't have a variable with the "current" date.

e.g: `this.children.filter(F.pub_date>now)`

**Comment by runfalk** [comment]
You can make a simple plugin for that which is only part of your site like in this issue: https://github.com/lektor/lektor/issues/717.

**Comment by goanpeca** [comment]
Maybe we should provide that function out of the box. It seems like a common enough need.

**Comment by runfalk** [comment]
I think it's common, but it also works in surprsing ways. People may be tempted to use it for stuff like "last updated", but that will not necessarily be true or accurate. Maybe it's OK to add but with a giant disclaimer?

**Comment by goanpeca** [comment]
I usually use moment for things like this, where the build is there but “hidden”. This avoids having to rebuild every day, but exposes the content in html.


https://github.com/moment/moment

**Comment by ikus060** [comment]
If we don't plan to implement this feature in Lektor can we guide me more about the proper way to implement this as a plugins in Lektor ? I'm very curious about the custom children query.

**Comment by dairiki** [comment]
@ikus060 It would be straight-forward to define a `now` or `today` template global via a plugin.
See https://www.getlektor.com/docs/plugins/dev/ and https://www.getlektor.com/docs/plugins/howto/ for the basics on how to create your own plugin.

As a starter, I think something like this (untested) would work:

```python
import datetime

from lektor.pluginsystem import Plugin

class ExampleTodayPlugin(Plugin):
    name = 'example-today'

    def on_setup_env(self, **extra):
        self.env.jinja_env.globals['today'] = datetime.date.today()
```

after which you could do just what you suggested [above](https://github.com/lektor/lektor/issues/779#issuecomment-623428198), e.g. to iterate
 the children whose ``pub_date`` is not in the future: 
```
this.children.filter(F.pub_date <= today)
```

**Comment by ikus060** [comment]
Thanks alot if give me the info I needed to make this work in my project !

For reference:
https://gitlab.com/ikus-soft/pdsl-www-lektor/-/blob/master/models/blog.ini
https://gitlab.com/ikus-soft/pdsl-www-lektor/-/tree/master/packages/schedule

Closing this issue.

**Comment by goanpeca** [comment]
@ikus060 maybe create a plugin so more people can use it :-) !

And glad you got it working!
