### ISSUE TITLE
Add new flow block: Is blocked by ad blocking list EasyList FR

### ISSUE THREAD

**Issue by blipp** [lektor/lektor#785]
### Steps to reproduce:

* Use a web browser with an ad blocking extension and the EasyList FR activated
* Have a fresh Lektor project, either with the latest release, or the development version
* Have a model using a flow type (or just use the example project)
* Go to the web interface and edit a page that has a flow type in it

### What happens:

* The browser does not show the “Add Block:” element at the bottom of the flow.

### What should happen:

* The browser should display the “Add Block:” element at the bottom of the flow.

### More information:

When using a flow type, the edit web interface is supposed to display the “Add Block:” element at the bottom, see this screenshot taken from https://www.getlektor.com/docs/content/flow/:

![](https://www.getlektor.com/docs/content/flow/flow-admin.png)

It is implemented using a div HTML element with the class `.add-block`.

This class `.add-block` is part of the EasyList FR advertisement blocklist, which can easily be added with various ad blocking browser extensions. For instance, I use it with uBlock origin in Firefox.

Proof that this class is indeed on the blocklist is this direct link to the repository: https://hg.adblockplus.org/listefr/file/tip/liste_fr.txt#l14904 (repository linked from https://adblockplus.org/subscriptions (search for “FR”)).

### Workaround:

Disable the ad blocker on the website/localhost.

### Suggestion:

I suggest the CSS class to be changed, for example to `.new-flow-block` or similar. An alternative could be to add an explanation to the manual and ask people to disable their ad blocker for their own website/localhost. However, users could think that this is a fishy thing to ask (and then not do it); also, the error is hard to detect in the first place if someone is new to Lektor, so it might be driving newcomers away from the project. See also the next section (related issues).

### Related issues:

This could also be the solution for issue #597, opened nearly two years ago.

**Comment by nixjdm** [comment]
Thank you for the report! That should be an easy change.

**Comment by streaps** [comment]
Have you reported this problem to EasyList FR? It's obviously a problem with filtering and should be fixed at the source, not in Lektor. ".add-block" is not a very specific selector.

**Comment by blipp** [comment]
I did not report it to EasyList FR and I personally do not intend to do so:
- I believe it is likely enough that an **ad**vertisement will use some CSS class like **ad**d-block at some point.
- My feeling is that getting something removed from an adblocker list is fighting against wind mills (takes a lot of time).
- In the meantime I also stopped to use Lektor, so I have no “stake” in this anymore.
