### ISSUE TITLE
Windows installation issues

### ISSUE THREAD

**Issue by viperscape** [lektor/lektor#79]
Installing from PS script fails:

```
Windows PowerShell
Copyright (C) 2015 Microsoft Corporation. All rights reserved.

PS C:\Users\Chris> iex ((new-object net.webclient).DownloadString('https://getlektor.com/install.ps1'))
  File "<string>", line 31
    print 'Error: %s' % message
                    ^
SyntaxError: Missing parentheses in call to 'print'
PS C:\Users\Chris>
```

Thanks

**Comment by tylerlong** [comment]
It seems that you are running Python 3.x.  Python 2.7 is required instead.

**Comment by viperscape** [comment]
Ah yes, I just realized this! I swapped the env var out for 2.7. Does lektor require python 2.7 during runtime? I would prefer to use 3.4 for other projects.

**Comment by viperscape** [comment]
It seems to be fine with 3.4 in the env after installation. I also noticed it installed a python executable under scripts in lektor-cli. Closing this, thanks!

**Comment by mitsuhiko** [comment]
@viperscape Lektor only supports Python 2.7.
