### ISSUE TITLE
Can't use thumbnail() with height only, and width set to None

### ISSUE THREAD

**Issue by relikd** [lektor/lektor#794]
According to [the documentation](https://www.getlektor.com/docs/api/db/record/thumbnail/) the `thumbnail` function should support setting height ony. However, the build process complains that width is a required positional.

```
".../templates/blocks/image.html", line 4, in top-level template code
    <img src="{{ image.thumbnail(height=this.height)|url }}">
TypeError: thumbnail() missing 1 required positional argument: 'width'
```

Setting width to `None` does not work either:

```
File ".../site-packages/lektor/db.py", line 785, in thumbnail
    width = int(width)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```
which is weird in itself, `db.py line 785` points to a different line in master branch.

I'm using the latest 3.1.3 version installed just a few days ago.

**Comment by relikd** [comment]
Ah! v3.1.3 uses this instead:
```
def thumbnail(self, width, height=None, crop=False, quality=None):
        """Utility to create thumbnails."""
        width = int(width)
        if height is not None:
            height = int(height)
        return make_thumbnail(_require_ctx(self),
            self.attachment_filename, self.url_path,
            width=width, height=height, crop=crop, quality=quality)
```

I guess its already fixed but not released yet. 
When can we approx expect the new version to be available?

**Comment by nixjdm** [comment]
Yes, the thumbnail API was changed quite a lot in the master branch and this issue shouldn't exist any longer. The next release is pending a few remaining items on our checklist, but I don't have an ETA for it. Just as soon as we can. In the meantime you may want to install from source with `pip install -e .`

**Comment by runfalk** [comment]
Remember that you need to generate the admin javascript files when installing from source if you plan to use the admin interface. If you don't the admin will not be accessible.

Provided you have the necessary dependencies you can generate them using `make build-js`.

**Comment by relikd** [comment]
@runfalk thanks for the info. 
To the topic, I assume the documentation is generated from current master? 
Does it make sence to show an API to the general public that isn't available yet?
I can find arguments for both sides and its something that should be considered.

**Comment by runfalk** [comment]
We are currently doing work to have a "stable" and "nightly" branch (or similar) of the docs. The first PR that ties docs directly to the code is here: https://github.com/lektor/lektor/pull/787.

This is mainly a problem since there hasn't been a release in so long and I expect it to be less of a problem going forward.
