### ISSUE TITLE
Paginate list of records other than children

### ISSUE THREAD

**Issue by betaveros** [lektor/lektor#810]
If I want to have a page that lists all records in some complicated query, I can always write a custom model and template that directly makes that query, but this list can't be paginated. I can also paginate the records from a complicated query with "child replacement", by taking a model and redefining its children to be the result of that query, as documented in https://www.getlektor.com/docs/guides/categories/ . However, this replaces all the model's old children, which it seems are no longer generated.

Example use case: I have a website that's primarily a blog (a list of posts), but that also has some other subpages (e.g. an about page, category/tag pages). I want the root of my website to paginate the list of posts, but also for those other pages to be generated and linkable. Using child replacement on the root to replace the children with the list of blog posts, and then paginating that, doesn't work because now the other pages are gone. Is this currently possible in Lektor?

If it doesn't, one way I could imagine it working is to add a `replaced_with` field to the pagination section that replaces only the query used for `pagination.entries`. This seems somewhat inelegant as introducing two ways to do the same thing though. It's also possible that child replacement preventing the old children from existing in the generated website isn't intended/desirable behavior, but I haven't really thought through the data model well enough to be sure about that.

**Comment by runfalk** [comment]
The way I'd do it is to have a sub directory like `posts/` where all blog posts are generated. If you want to show blog stuff I'd manually query say the first five posts and display their summaries there. At the bottom there would be a link to the paginated `posts/`.

I honestly don't know of another way to do it. If there is no other way I agree it's a short coming with the Lektor model.

**Comment by betaveros** [comment]
After playing around a bit more with `replaced_with` I wonder if it's the wrong abstraction, and should perhaps only apply to `children` when accessed in a template and pagination. Or maybe we should not allow `children` to be changed at all, and add a property to `Record` called (for example) `displayed_children`, which defaults to `children` but can be replaced, and which is used by pagination. I think this would solve my issue and many other weird behaviors, listed below, neatly.

Some weird things that can happen with child replacement as it currently works:

- The problem in the original comment: If I try to replace the children of a node with a filtered version of its children, the filtered-out children cease to exist in the generated website.
- If I try to replace the children of a node with the children of one of its descendants, say replace `/` with the children of `/blog/`, the skipped descendants also cease to exist. Furthermore, the dev server does not serve the children of the descendant node from the place they're generated, which is the URL path the children believe themselves to be at. So for example if I have a post at `/blog/post/`, there will be a file generated at `/blog/post/index.html` and the post will believe that its URL path is `/blog/post/` wherever you e.g. pass it through the `|url` filter, but the dev server will 404 at that URL path. Conversely, it will serve the post in response to the URL path `/post/`, even though there's no file there.
- Even without replacing a node with its own descendants, if I have a blog post at `/blog/post/` and some node `/mirror/` (which might be a category in normal usage) whose contents are replaced with the children of `/blog/`, then the dev server will happily serve up `post`'s page from `/mirror/post/` (in addition to its normal URL), even though that page also doesn't exist in the generated website.
- In addition, if a page appears in its normal place in the hierarchy and is also replaced into a node elsewhere, Lektor will build the page multiple times. This doesn't affect the output, but can make Lektor builds very slow (a page in multiple categories will be built once per category in addition to its normal build) or even enter an infinite loop.
- In general, child replacement does not affect most other pieces of parent/child/descendant-related logic, like determining if a node is a child of another or what its list of ancestors is.

Are there any use cases for child replacement that require it to affect anything other than getting accessed as `{{ foo.children }}` in templates and pagination?

**Comment by betaveros** [comment]
So... I discovered in the code that `pagination` has a configuration option `items` that, as far as I can tell, literally does what the title of this issue says, implemented in 2015 in https://github.com/lektor/lektor/commit/f4448f54bd51c170c85b8660991b6fb7a047adcb and https://github.com/lektor/lektor/commit/31b3d9ce988411da8974b7109ab9c25015366938. And I guess it's documented in https://www.getlektor.com/docs/models/children/, albeit in a way that doesn't immediately suggest its applicability for this use case; it's just not in the guides I looked at ¯\\_(ツ)\_/¯

**Comment by runfalk** [comment]
Nice. Seems like there is definitely room for some improvement of the docs then. An example for how to use `items` would be nice I guess. I certainly wasn't aware of it.

It'd be nice if you could append the relevant parts of your template and model in case someone finds this post. It could also be used to improve the docs.

**Comment by betaveros** [comment]
I think it's used basically exactly like `replaced_with`, you specify a query of the list you want. So my blog's front page's data model has something like:
```
[pagination]
enabled = yes
per_page = 10
items = site.query('/post')
```
Analogously, to paginate the category pages in the category guide I think you could just as well replace
```
[children]
replaced_with = site.query('/projects').filter(F.categories.contains(this))
```
with
```
[pagination]
items = site.query('/projects').filter(F.categories.contains(this))
```
