### ISSUE TITLE
Flow widget collapse button triggers Data Unsaved Warning when moving away from edit page

### ISSUE THREAD

**Issue by arabidopsis** [lektor/lektor#828]
When a flow collapse/expand button is clicked it marks the data as 'changed' so a triggers 'Prompt'.

Since no data has changed (only the ui layout) this is confusing. See the gif below.

I have a PR I can give you to fix this if you like.

Here is a simple project you can try yourself

[Test1.zip](https://github.com/lektor/lektor/files/5505715/Test1.zip)

Visual:

![flow](https://user-images.githubusercontent.com/9948595/98454462-a95ea180-219f-11eb-862e-d4665d1350c9.gif)

**Comment by runfalk** [comment]
Hey @arabidopsis! We'd very much appreciate a PR for this. It's indeed confusing that collapsing marks the page as edited.

**Comment by arabidopsis** [comment]
No problem... you might not like it though. I'm a bit stretched for time but I will make a PR *soon*. Also I
am a react novice... but there seems to be little out there about writing tests for React.
