### ISSUE TITLE
How to sort image attachments?

### ISSUE THREAD

**Issue by relikd** [lektor/lektor#835]
Hi there, how do I sort image attachments by their name? It did work before, but isn't anymore in version 3.2.0

The query `this.attachments.images.order_by('record_label').all()` will return `['image2.jpg', 'image.jpg', 'image3.jpg']` instead.

It seems order by is ignored completely as adding a minus infront of record label does not reverse order.

**Comment by relikd** [comment]
And adding the attachment order to the model also does not change the order.

**EDIT:** Here is a workaround: `this.attachments.images | sort(attribute='record_label')`

**Comment by arabidopsis** [comment]
For attachments the '_id' is the same as the filename so:

`this.attachments.images.order_by('-_id').all()`

should work. 

Looks like it's because only sorting on fields specified in the [fields.*] sections of the model files is supported.
Although it would be easy to changes this.

**Comment by relikd** [comment]
Interesting, that works indeed, thanks! I am not sure but I would assume it did work before (pre 3.2), because why would I otherwise have put the sorting in place. I remember that I wanted to sort them by filename and that my "solution" above did fix the sorting. And I further assume that I did test it thoroughly and it worked. But I could be wrong.

Anyway, thanks for the reply. I think it wouldn't hurt to enable sorting on all attributes. I mean, it is working for the sort filter, so why not enable it on the order_by method too?

**Comment by transplier** [comment]
This ended up working for me, but I believe there is a small typo in relikd's post? I had to do
```this.attachments.images.order_by('_id').all()```
(note the removed dash).

**Comment by relikd** [comment]
@progman32 ah yes, the dash reverts the sort order. Note: this works fine with a number sequence but keep in mind that if you have more than 10 images, "img11.png" will be sorted before "img2.png". If that is the case, you should always prepend the numbers with zero "img02.png" ;) ... PS. the post you refer to was not by me but it doesnt matter :D
