### ISSUE TITLE
Checkbox select broken in v.3.2.0

### ISSUE THREAD

**Issue by relikd** [lektor/lektor#862]
This worked before, but now it doesn't. Selecting a checkbox in the GUI will simply do nothing. The checkbox state won't even change.

```
[fields.nav_items]
label = Submenu
type = checkboxes
source = record.children
item_label = {{ this.title or this.record_label }}
item_key = {{ this.path }}
```

Also, it would be nice if a patch release version would be released in the near future as some of the bug (already closed ones and this one) are critical for use in production. This bug for instance, and this one https://github.com/lektor/lektor/issues/793#issuecomment-750168882 makes it impossible to update the configuration through GUI.

**Comment by yagebu** [comment]
This looks like a duplicate of #812, which is fixed in master

**Comment by relikd** [comment]
seems so, closing this for now.

**Comment by relikd** [comment]
Whats the roadmap for the next release?

**Comment by yagebu** [comment]
There isn't much of a roadmap. I guess a bugfix release can happen as soon as one of the maintainers with PyPI access finds the time to do it.
