### ISSUE TITLE
Open Admin interface from alternative

### ISSUE THREAD

**Issue by dwt** [lektor/lektor#867]
When opening the admin interface of a page via the ✏️ button in the upper left, it doesn't work.

For example, if `/projects/` is the default path of the page and `/en/projects/` the localised, then opening the admin interface from the localised page yields `/admin/root:projects%2Ben/edit` instead of the correct `/admin/root:projects+en/edit`

**Comment by dwt** [comment]
Grepping a bit around in the source, it seems that the bug might instead be that this url is not resolved correctly by the admin interface to the alternative as this might be done intentionally to prevent url decoding of + to ' ' (space).

**Comment by yagebu** [comment]
This sounds like a duplicate of #815, which is fixed in master, could you check that?

**Comment by dwt** [comment]
Indeed - fixed on master.
