### ISSUE TITLE
Is there a reason Lektor is so strict about plugin distribution names?

### ISSUE THREAD

**Issue by dairiki** [lektor/lektor#875]
This pertains to the relationship between plugin name and package name which is enforced by [lektor.pluginsystem.load_plugins()](https://github.com/lektor/lektor/blob/ce4d96be0af2703059109b2f1b7c491e53280351/lektor/pluginsystem.py#L115).

## Motivating Story

I have  a package called [excerpt-html](https://github.com/dairiki/excerpt-html), which, essentially contains one python function (not surprisingly named `excerpt_html`) whose purpose is to compute excerpts (or "summaries") of HTML text fragments.
I thought it would be nice to include a simple Lektor plugin in the package. The plugin would register a single jinja filter (also called `excerpt_html`) which would allow excerpts to be computed within jinja templates.

So I write a lektor plugin, and add something like this to `setup.py`:
```python
entry_points={
    'lektor.plugins': [
        'excerpt-html = excerpt_html.lektor:ExcerptHtmlPlugin',
    ]
}
```

When I go to use this, this error message obtains:
```
lektor/pluginsystem.py:123: in initialize_plugins
E RuntimeError: Mismatching entry point name.  Found "excerpt-html" but expected "-html" for package "excerpt-html".
```

## Points and Questions

First off, note that the error message is rubbish.  The problem is not the name of the entry point, but rather (for the most part) the distribution name of my package.  There seems to be no way to pass muster unless the distribution name starts with `lektor-`. (The message claims that Lektor expects the plugin to be named `-html`, but it’s clear that it won’t be happy with that name either.)

Second, is there really a good reason to require a specific relationship between distribution name and plugin name?  Why shouldn't I be able to register a plugin named `excerpt-html` in my `excerpt-html` distribution?

It seems silly to have to create a whole new distribution (`lektor-excerpt-html`) just to package the (essentially three-lines of) Lektor plugin code.  Do I have any better options?

**Comment by dwt** [comment]
I have to say that it is very convenient to search for all lektor plugins on pypi by just searching for 'lektor-'. There are other ways to group them on pypi, for example by using the trove classifiers, but these are far more complex, so I would really like to keep the 'lektor-' prefix for all usable plugins.

**Comment by runfalk** [comment]
Yes, I agree with @dwt here. It's nice to be able to search for lektor and have everything appear. It's also a way to prevent the plugin system from installing things that were not intended for Lektor usage.

In your case, wouldn't you need to depend on Lektor to provide the plugin? I don't think it makes sense to have Lektor as a dependency for something that is not primarily intended to be a Lektor plugin. There is also nothing stopping you from keeping the lektor plugin in the `excerpt-html` repository, but still serve it as a separate package.

**Comment by dairiki** [comment]
To be clear, I’m not claiming that naming plugins `lektor-*` is a bad idea.  I'm just questioning whether there’s really a good reason that it be *required*.  There are always situations where it makes sense to bend the rules.  Some things are better imposed as conventions rather than hard-and-fast rules. 

As to specific points.

## Finding plugins on PyPI

Searching for plugins by Trove classifier [appears to work well](https://pypi.org/search/?q=&o=-zscore&c=Environment+%3A%3A+Plugins&c=Framework+%3A%3A+Lektor).  The classifiers are precise and well-defined and seem to be in fairly wide usage (in that most current Lektor plugins are tagged with them.)  Really, calling searching by classifier "far more complex" seems to be a bit hyperbolic.

Searching for `lektor` (or `lektor-`, which appears to produce equivalent results) seems to match any distribution with the word "lektor" anywhere in its title *or its long_description* (though it does appear to score title matches higher).  This means: searching PyPI for `lektor` will still be likely to find Lektor plugins, even if their names weren't `lektor-`-prefixed.  It also means that searching for `lektor` finds distributions that are not Lektor plugins at all.  E.g., currently, if one searches PyPI for [`lektor`,  ordered by "trending"](https://pypi.org/search/?q=lektor&o=-zscore), the first hit is [poyo](https://pypi.org/project/poyo/), a distribution which appears to have little, if anything to do with Lektor.

(Even if it were true that you can't use my new plugin because, for whatever reason, you can't find it on PyPI, is that really a reasonable reason for lektor to prevent me from using it?)

## It's also a way to prevent the plugin system from installing things that were not intended for Lektor usage

I don't think that argument holds water.

It currently seems quite possible to install any distribution via Lektor's private packaging system — either by running `lektor plugin add <pkgname>`, or by directly adding the package to the `[packages]` section of the `.lektorproject` file.  Whether or not this is a good idea, packages installed this way, for the most part, currently work just fine.  (I.e. one can install any arbitrary package via `lektor plugin add`, and then that package will be available to import in any python code running in that lektor environment.)  The only thing they can't do is register a Lektor plugin (from a non-conformant distribution name).

The check for `lektor-`-prefixed distribution name currently only prevents lektor plugins from loading unless they come from a "properly-named" distribution.  As such, it seems to be a pretty artificial and ineffective check.

(If one did want to enforce a rule which allowed only Lektor plugins to be installed via `lektor plugin add`, then the way to do it is to make sure that only plugins — by definition, those distributions which declare a `lektor.plugins` entry point — can be installed.  Specifically, note that requirements on distribution name do not really guarantee anything about distribution content: it is quite possible for a distribution named `lektor-is-the-devil` to have nothing at all to do with Lektor.)

## The need to depend on Lektor when providing a plugin

No, I don't think my distribution would have to require lektor, so long as care is taken to make sure the rest of the package works without lektor installed.

Many distributions provide "extra" functionality if certain non-required extra packages are available at run-time.  (Setuptool's [`extras_require`](https://setuptools.readthedocs.io/en/latest/userguide/dependency_management.html?highlight=extras_require#id7) is related to this idea.)  As long as the lektor plugin code is in its own module (which doesn't get loaded unless one attempts to actually use the lektor integration) things will be fine.  (It is fairly safe to assume that — since lektor plugins are, generally, only loaded by lektor — if one is trying to load the lektor plugin, lektor is in fact installed.)

I would probably add lektor to `tests_require` so that tests can include integration testing for the Lektor plugin.

As an aside, note that most (all?) lektor plugin distributions do not explicitly depend on lektor.  (I have a vague recollection that declaring lektor as a requirement causes (or used to cause?) problems — something to do with triggering a second install of (possibly a different version of) lektor into lektor's private package cache.)

## Two-distributions in one git repo

Sure it's possible, but there are issues with doing this.  How does one tag two orthogonal sets of releases?  (Again, sure it's possible, but hoops must be jumped.)  Unless one always releases both distributions in lock-step... in which case, why not just one distribution?

And it doesn't really get around the fact that producing the separate plugin distribution involves writing and maintaining an order of magnitude more packaging code than actual run-time code.  It seems silly in cases like mine where the only purpose of the Lektor plugin is to export a function provided by the base library to Jinja filter space. (Again, I'm only saying this is a good idea when the plugin code, by itself, is pretty trivial.)

Really, it's not the extra git repo that makes for the extra work and upkeep, it's the additional distribution.  And to reiterate from my original comment, a separate distribution for what is essentially three lines of code just seems like overkill and make-work.

**Comment by runfalk** [comment]
It's easy to enforce plugin names, but it's harder to enforce trove classifiers. I like the explicit prefix since it signals that this package is intended to be used with Lektor. Your particular library might be multi purpose, but removing the restriction means that anyone can publish something that only works with Lektor, yet is not prefixed. Of course anyone can create a package with the prefix, whether or not it is a plugin, but it's a way to alert the user that they are trying to do something that doesn't quite make sense.

Apparently we allow the user to install plugins that are not prefixed with `lektor-`, and that sounds like a bug to me. I don't think there is a clean way to check for plugin specifiers before installing it.

The prefix requirement is also part of how lektor create plugins (https://www.getlektor.com/docs/plugins/dev/).

If your plugin is only 3 lines I'd probably just create it as part of the site and keep it the `packages/` directory. To me, your particular case sounds very unique and I don't think it's a good idea to change Lektor to accommodate a single project. I'm happy to keep the issue open for further discussion though. Maybe other maintainers have a different opinion.

**Comment by dairiki** [comment]
> It's easy to enforce plugin names, but it's harder to enforce trove classifiers.

I guess my philosophy is that neither need be "enforced".  While both naming conventions and the use of Trove classifiers can/should be suggested as best practice, third-party distributions are just that: third-party.  Why impose arbitrary limits on code that is not part of the Lektor project itself?  Why second guess the motives of third-parties?  Worst case, if someone creates an atrocious distribution, is not open to suggestions on improving it, and it really cheeses you off, you can just ignore that the distribution exists and all will be okay.  (That atrocious distribution will be even easier to ignore if it doesn't have "lektor" in its name ;-) )

> Apparently we allow the user to install plugins that are not prefixed with `lektor-`, and that sounds like a bug to me.

Well, they can install plugins, but they can't use them unless the name of the distribution that contains them is lektor-prefixed.  But they can install and use any other (non-Lektor-plugin) distribution (named any arbitrary name) using Lektor's private package cache machinery.  (Again, I'm not sure why this is a problem.  It's weird, but if users want to do it, what's the harm?)

> The prefix requirement is also part of how lektor create plugins (https://www.getlektor.com/docs/plugins/dev/).

Lektor tools *should* follow Lektor suggested practices — there's nothing wrong with that.  But there are other ways to create plugins, too.

> If your plugin is only 3 lines I'd probably just create it as part of the site and keep it the `packages/` directory.\

Yes, that's what I do now. It works fine for me, personally.

I had recently seen a request for help from someone (maybe it was on the Lektor gitter feed) who was having trouble with invalid HTML fragments being generated by whatever tools he had used to generate a synopsis.  That's exactly what my package fixes, so I was going to suggest he try it until I looked and remembered that no Lektor plugin was provided in my distribution.  I lost motivation help at that point, since this fellow sounded like he'd need a fair amount of hand-holding to figure out how to create a plugin to install the Jinja filter.

I figured that if it were easy to add, my work would be more easily usable by others.


----

At the least, that error message (quoted in my first comment) really should be fixed.  It is incorrect and non-elucidating.  It seems that the naming-convention requirement is imposed solely in the name of user-friendliness — that error message is not helping the cause.

If you'd like I can generate a PR to fix the error message.  (Although, since I've yet to discover how removing the check altogether would break Lektor in any way, I'd much rather just do that.)

**Comment by dwt** [comment]
@dairiki I notice that this seems to feel personal for you - but might I still suggest that adding a git repo, that just contains a setup.py file that contains a dependency on your code and a declaration of an entry point should be way shorter than the number of lines you have written on this bug report? Also you only need to release an update of that package if the signature of the entry point changes, which should be really rare.

I would like to suggest that a simple naming convention like `lektor-*` is something valuable that should be kept as it communicates really well. Names are important.

That being said, the whole weird private cache thing of lektor is something that probably needs to be revisited (at some point?), as I suspect that it only existed to allow distributing lektor as an app on macOS - which is now gone away. So I'm really not sure if it is worth to keep it.

Also if it is not documented yet, adding trove classifiers to plugins should be encouraged, as should perhaps a check that only things that actually contain a `lektor.plugin` entryponit - but that will take time and pull requests.

**Comment by dairiki** [comment]
Note to future self: 

The current implementation of the [Plugin.version][1] property depends on this distribution naming convention. Not that that couldn't be easily fixed — probably using [importlib.metadata][2] — were that so desired.

[1]: <https://github.com/lektor/lektor/blob/25ba7c7df2646078ae6667781e51444ee305bf8e/lektor/pluginsystem.py#L51>
[2]: <https://docs.python.org/3/library/importlib.metadata.html>

**Comment by dairiki** [comment]
Here's another *user story* that gets torpedoed by this unnecessarily strict package naming convention.

Suppose one would like to get away from using Lektor to manage plugin installation and use something like `Poetry`, `pipenv`, or `hatch` to manage the dependencies of a Lektor project.  Something along the lines of what’s in lektor/lektor-website#327.

So we have a `poetry` (say) project named something like `joes-blog`.  It's mostly not a python project — the "source" is `.lr` files, jinja templates, etc. — but building it requires some python dependencies to be installed in a local virtualenv: `lektor`, of course, and perhaps some `lektor-*` plugins installed from PyPI.  `Poetry`, et. al. make it easy to manage virtual environments.  I.e. to work on the site, one would need only clone the `joes-blog` git repo, then execute `poetry run lektor server`.

Now suppose we would like to include a local, project-local plugin (or two, even) in this project.  We put the code for the plugin(s) in the project’s `src/` subdirectory, add one or more `lektor.plugins` entry points to our `pyproject.toml` and fire up Lektor.

It would all work fine, except that Lektor arbitrarily refuses to load our plugins because they come from a package named `joes-blog`.  Lektor wants each plugin in its own distribution (named, e.g., `lektor-joes-plugin` and `lektor-joes-other-plugin`).

(Note that we never intend to publish these local plugins or the `joes-blog` project to PyPI — it's the source for a website, not a library or a utility.  Still, Lektor thinks it should tell us what the distribution name should be.  It seems like a lot of needless friction.)

We could rename our project to `lektor-joes-blog`, but that's stupid.  The project is not a Lektor plugin, it just happens to provide one for it's own use.  And we could still only facility a single local plugin this way.
The only real option, currently, is to include whole distribution sources (each with their own `pyproject.toml` or `setup.py`) in our project source.  That seems less than optimal.  Why require each plugin to be packaged into its own distribution, when those distributions will never be used or distributed outside the `joes-blog` project?

**Comment by dairiki** [comment]
@runfalk wrote, some time ago
> It's easy to enforce plugin names, but it's harder to enforce trove classifiers.

I don't think that's particularly true, especially now that we're using `importlib.metadata` rather than `pkg_resources` to access the distribution metadata.  We still, essentially, have to find the distribution metadata for the plugin to check the distribution name.  Once we have the distribution metadata, accessing the classifiers is not fundamentally any more difficult than accessing the distribution name.  The test, assuming `dist` is an instance of `importlib.metadata.Distribution` is:

```py
has_lektor_classifier = "Framework :: Lektor" in dist.metadata.get_all("classifier")
```

If we really care that we should be able to find all Lektor plugins on PyPI, what about just requiring plugins to come from a distribution tagged with the [`Framework :: Lektor`][framework-lektor] trove classifier? 
(I still feel that's being awfully pushy, but at least it is a less onerous requirement.)
PyPI appears to support searching by classifier [just fine][framework-lektor].



[framework-lektor]: https://pypi.org/search/?c=Framework+%3A%3A+Lektor
