### ISSUE TITLE
Consider dropping python3.5 support as it is end of life since some time

### ISSUE THREAD

**Issue by dwt** [lektor/lektor#878]
3.6 is the current oldest version that still receives patches. AFAIK

**Comment by runfalk** [comment]
Python 3.5 is actually dropped as per the latest release notes: https://www.getlektor.com/blog/2020/8/lektor-32-released/

**Comment by dairiki** [comment]
It appears that 3.5 is still listed in the CI test matrix.

https://github.com/lektor/lektor/blob/194b023c3020b5cc4b7f03c4b52ba9134b0da165/.github/workflows/ci.yml#L219

**Comment by runfalk** [comment]
True, that's an artifact of that 3.2 is still supporting Python 3.5. I assume we'll remove it in the near future.
