### ISSUE TITLE
Images are not exported in alternatives' folders

### ISSUE THREAD

**Issue by vindarel** [lektor/lektor#88]
Hi again !

Let's say I have a `content.lr` and a `content+en.lr`. I use an image in both, like you do with the logo and slide images in lektor-website.

During development, with `lektor server`, everything's fine, but when I build the project, it creates a base folder, an `en/` folder, but that one without any image.

The [current doc](https://www.getlektor.com/docs/templates/imageops/) on images didn't help, so I guess that's a bug  !

Regards

ps: I tried with lektor2.0dev

**Comment by mitsuhiko** [comment]
The images do not appear in alts but are referenced by the binary. In which situation does this cause problems. Is this in combination with markdown?

**Comment by vindarel** [comment]
This causes a problem because the index page of a translation won't show any image ! Viewing the base url is nice, but if we want to read its translations (url `/en/index.html`) we won't find any image. At the moment I must copy manually every one of them after the build.

The images affected are the ones you use in `lektor-website/content/contents.lr`, that live alongside this file (logo.png, etc). They are used either in some embedded html of markdown, either with a keyword for the slide feature:

   title of slide
    ---
    image: foo.png

ps: what do you mean "referenced by the binary" ?

**Comment by mitsuhiko** [comment]
> This causes a problem because the index page of a translation won't show any image

Can you clarify why? The `|url` filter should resolve to the correct file:

``` jinja
{% set img = this.attachments.get(this.image) %}
<img src="{{ img|url }}">
```

> ps: what do you mean "referenced by the binary" ?

That was auto correct I think. It was supposed to say referenced by the primary eg: primary alternative. We only store images once and not once for each alternative (same with all attachments).

**Comment by esclapes** [comment]
I am seeing this same issue, image source with `\url` filter points to

```
src="../../nl/webcare/image.gif"
```

while the file only exists on the `en` alternative. Using the lektor server, it works as expected, but not with my apache setup.
