### ISSUE TITLE
CI Tests are quite slow

### ISSUE THREAD

**Issue by dairiki** [lektor/lektor#892]
The CI tests take quite a while (often over 10 minutes) to run.  The workflow config also seems perhaps unnecessarily complicated.

Here are some questions and suggestions which might point the way to speeding up the total test time and to cleaning.  (It's quite possible that there a good reasons things are the way they are now, in which case... sorry to waste your time.)

## What purpose do the smoke-tests serve?

The test workflow runs a number of "smoke tests". Further tests depend on and are only run after the successful completion of these smoke tests.
The decreases the number of tests run in parallel, and so, increases overall test time.
It also results in a large, repetitive workflow [configuration file](https://github.com/lektor/lektor/blob/master/.github/workflows/ci.yml).  Many of the dependent tests are, at least on rough inspection, apparently identical to the smoke tests they follow.

As a developer, there are two things I care about: "Did all the tests pass?", and, if not, "Why not?".  And I'd like the answer as quickly as possible.
Running all tests in parallel (as much as github will allow) gets to an "all pass" faster.  It also can get to "first failure" faster, too.   These are both good things.
Since these tests are run for us for free by github, what is the downside to running all the (currently dependent) tests, even after we know they're likely to fail? The lack of parallelism slows the total test time.

## What is the purpose of running multiple versions of the frontend (node/webpack) tests?

The frontend tests (`webpack`, `npm test`, etc.) are currently run in four different combinations of OS and node version.

Since `webpack` is run as part of the package release process, end users do not do this themselves.  They just use the packaged `gen/app.js`.  What is the value in testing (for *every* push/PR to the repo) that `webpack` runs under multiple environments?

## How much value is there in running the Mac & Win tests under multiple python versions?

The Mac and Win tests are slow.  Currently, each is run twice under two different python versions.

Given that we test all supported python versions under Linux, is there much value in testing multiple python versions on Mac & Windows?  What sort of errors are we looking to catch by doing so?

## Suggestion: Unify with tox tests

In other projects, I've found value in putting as much of the test configuration as possible in `tox.ini`, with the workflow config just doing what's necessary to set up the test environment enough to be able to run `tox` to run the actual tests.

([Tox-gh-actions](https://pypi.org/project/tox-gh-actions/) can help with this.)

This minimizes duplication of configuration.  But the big advantage is it makes it easier for developers to run (as much as possible) the same tests as will be run in CI.

## Minor nit: Why are we passing `-s` to `pytest`?

`Pytest -s` results in all output to stdout/stderr being output by pytest (and so saved in the CI test logs).  By default, pytest captures output to stdout/stderr and displays only that produced by failing tests.  Some of the tests spit out a fair amount of cruft — I'm not sure any of it is of interest unless the test fails.

----

(If there is support for any changes suggested above, I'm willing to work on it.)

**Comment by runfalk** [comment]
> The test workflow runs a number of "smoke tests". Further tests depend on and are only run after the successful completion of these smoke tests.

I was in favor of just running everything in parallel when we migrated to GitHub Actions. I think the idea is to fail early if some basic checks aren't met. The smoke tests should catch most errors and the rest are there as safe guards. So if the smoke tests pass you can be reasonably sure that the rest will too. You could also make the argument that it's more energy efficient to have smoke tests though that's a bit of stretch for our CI usage.

I'm fine with cutting the smoke tests out of the equation and let GitHub run as many in parallel as it sees fit.

> The frontend tests (webpack, npm test, etc.) are currently run in four different combinations of OS and node version.

I'm fine with restricting it to one version per OS, but I think it makes sense to run it on all three systems to ensure that the dev environment doesn't break.

> In other projects, I've found value in putting as much of the test configuration as possible in tox.ini, with the workflow config just doing what's necessary to set up the test environment enough to be able to run tox to run the actual tests.

I don't have any opinion for or against this.

The duplication issue could also be solved using conditional steps like I did in another project (https://github.com/andrewchambers/bupstash/blob/master/.github/workflows/ci.yml#L29).

> Why are we passing -s to pytest?

I agree that this one can be dropped.

**Comment by dairiki** [comment]
Another question to research:

Much of the slowness of the Mac and Windows tests seems to be in the "Install System Dependencies" step which installs imagemagick and ffmpeg.   These packages seem to always be downloaded fresh (though I'm not sure how much of the total slowness is due to network/download time.)

I am not familiar enough with the Mac or Windows environment to say off the top of my head, but, might there be a way to use [actions/cache](https://github.com/actions/cache) to speed up these downloads (in a manner similar to how we currently use actions/cache to preserve npm and pip download caches between runs.)

----

Edited to add, after some quick googling:

It [appears](https://github.com/chocolatey/choco/issues/2015) that Chocolatey (used to install imagemagick and ffmpeg on Win) does not really have a download cache.

Though I haven't yet found authoritative docs on it, `brew`, used on MacOS for similar purposes, [does][1] [appear][2] to have a download-cache.  It might be worth playing with.

[1]: <https://github.com/Homebrew/brew/issues/3784>
[2]: <https://stackoverflow.com/questions/23273637/how-to-find-where-homebrew-temporarily-saves-dependencies-being-downloaded>

**Comment by dairiki** [comment]
> I'm fine with restricting it to one version per OS, but I think it makes sense to run it on all three systems to ensure that the dev environment doesn't break.

From what I can tell all the npm packages used are pure javascript — no native modules.
Also, I don't think there are any javascript tests that test any sort of OS integration — e.g. I don't think any of the tests run external non-node executables (e.g. imagemagick.)

Given that, what's the chance that node and the front-end code are going to behave differently on different OSes?

That said, the frontend tests are not the really slow ones, so it's not that painful to run more than one.

> The duplication issue could also be solved using conditional steps like I did in another project

Yes.  That seems like a great way to handle different setup on different OSes for what are essentially the same tests.

But that's mostly an orthogonal issue to whether to move as much test configuration as is reasonable to tox.

To reiterate, an advantage to keeping as much of the test config in `tox` as possible is that the individual developer can run (as much as possible) exactly the same tests in his own dev environment as are run by the CI test workflow.

E.g. `tox -e frontend` runs the webpack and other js tests, `tox -e lint` runs the lint tests, `tox -e py39` et. al. run the python tests.  The workflow config then does just enough setup to run the appropriate tox envs for each element in the workflow matrix (and then invokes tox.)  This allows the developer (assuming he has node and all the tested version of python installed) to just run `tox` (or `tox -p auto`) to run all the tests configured the same as the CI tests.

**Comment by yagebu** [comment]
I'd also be happy with a removal of the smoke tests and making the tests more robustly based on tox.

> From what I can tell all the npm packages used are pure javascript — no native modules.
Also, I don't think there are any javascript tests that test any sort of OS integration — e.g. I don't think any of the tests run external non-node executables (e.g. imagemagick.)
> Given that, what's the chance that node and the front-end code are going to behave differently on different OSes?

This has happened in the past (some breakage of Webpack on Windows with Node 10 I think), so we should keep one Node build per OS at least.

**Comment by dairiki** [comment]
I've started playing with this in my [refactor.ci-testing](https://github.com/dairiki/lektor/tree/refactor.ci-testing) branch.

I'm pretty happy with the python testing refactor in that branch.  I'm not completely satisfied yet with the node testing the way I have it now.

One issue is the way pre-commit is used for lint testing with the "local" checks for the JS.  That means that the configuration for the JS linting is spread between .pre-commit.yaml, package{-lock}.json (both for plugin specification and version pinning), .eslintrc.js.  I think (but I'm not sure) that I'd be happier if we could get all the configuration needed to run pre-commit into .pre-commit.yaml.

Also, perhaps the right way to configure the JS tests is to configure a single `test` target in package.json which would run the complete set of tests.  (So that `npm cit` would be all that's involved in running the JS tests.)

> This has happened in the past (some breakage of Webpack on Windows with Node 10 I think), so we should keep one Node build per OS at least.

I've discovered that Windows with Node 14 currently fails to run our webpack build.  This may be an intermittent problem — I swear I saw it pass once or twice, but have been unable to reproduce that lately.  (Is this a problem specific to the github runner?  If it's a broader problem than that, it would be good to get to the bottom of what's going on...)

**Comment by dairiki** [comment]
See #748 for more ideas on optimizing CI testing. (In particular, using the on...paths filter to avoid pointless test runs.)

**Comment by yagebu** [comment]
I had kind of forgotten about this issue, but with #931, most of this will be implemented (using tox for all python tests and removing the smoke tests).

Regarding the split of the frontend lint config to various files, I don't think that can be really avoided. Node projects just expect to have all these various files in place and a filled node_modules with all dependencies. The current setup also allows the standard prettier + eslint editor plugins to work.

**Comment by yagebu** [comment]
I'll close this issue, I think most of the points have been adressed:

- Smoke tests were removed
- Slow Win+Mac tests only run for one Python version
- Tests were unified with tox.
