### ISSUE TITLE
Fallback to original Translation of new Flow-Block if it isn't available in a translation

### ISSUE THREAD

**Issue by dwt** [lektor/lektor#893]
Flow-Blocks can be a nice help when translating pages to multiple languages. If one translation adds them, and you edit the page in another language, the untranslated flow blocks 'shine through', i.e. are shown and can easily be translated.

However, if you add new flow blocks after initial translation, they do not show up when editing translated pages, which makes it easier to miss them.

I would hope that we can change the admin interface to show the untranslated flow block to ease translation. Ideally it is marked and not saved until it is actually changed from the untranslated page.

Is there a specific reasoning for the current behaviour that I'm missing? (besides, easier to implement this way, of course)

**Comment by dairiki** [comment]
Here's how things currently work.

Flowblocks exist within a field (of `type = flow`) in the page data.  The data for all blocks within that field is serialized, using a custom format (the once with the `####`s), and stored as a single string value in the `contents.lr` file for the page.

For a particular translated page, the page data is stored in two files: the primary `contents.lr`, and the "alternative" `contents+xx.lr`.  These two files are overlayed — specifically, any field defined in the alternative supersedes the default value provided for the field by the primary.

So, once you edit a `flow` field in a translated page, the value for the field (which contains all the data for all the blocks in the field) becomes completely separate from the value of the field in the primary alternative.

This works just like any other page field.  E.g. suppose you have a markdown `body` field in your page.  Once you create a translated version of that field, the value of the field in the primary and alternate pages are completely separate — editing one will not change the other.

(This is also, essentially, the reason that implementing #863 is problematic.)

So, while it may be possible to fix things as you suggest it would involve quite a bit of change.  Logic would have to be added to be able to "merge" the contents of primary and translated `flow` fields.  The hooks for this do not exist in the current code.

Not having thought about it deeply, it's not clear to me that the process of merging two `flow` fields is well-defined, even. What if there are "merge conflicts"? Keep in mind, also, that blocks may contain other blocks (blocks can have fields of type `flow`.)

**Comment by dwt** [comment]
Oh wow, thanks for the detailed reply. That is indeed problematic, especially because none of the blocks has a clear defined `ID` that is recognisable across translations. Thats what you get for a human editable first format, I guess?
