### ISSUE TITLE
Add @dairiki to the maintainers

### ISSUE THREAD

**Issue by dwt** [lektor/lektor#899]
From working on and with lektor it seems to me that @dairiki should really be one of the maintainers of the project.

Some reasons:
1.  He knows quite a bit about it's internal workings
2. He is very active on the bug tracker
3. He can step down from his opinion when he gets good arguments against it

All of that suggest to me that he should really be a maintainer. :-)

So @maintainers what do you think? What is your process to add maintainers to the project? Is that documented somewhere?

**Comment by dwt** [comment]
@yagebu I'm not sure who to talk to on this issue - but it seems the number of maintainers for lektor is not super large (where is that actually documented) and it would seem very prudent to add more maintainers if possible.

So, what are your thoughts on this? Is there a process, if so, where can I find it?

**Comment by dairiki** [comment]
I am now a maintainer ([since September](https://github.com/lektor/lektor/issues/724#issuecomment-922384012)).
Closing.
