### ISSUE TITLE
Disable deprecated implicit thumbnail upscaling?

### ISSUE THREAD

**Issue by dairiki** [lektor/lektor#930]
Implicit thumbnail upscaling, as well as the `crop` argument to [`Image.thumbnail`](https://github.com/lektor/lektor/blob/f135d73a11ac557bff4f1068958e71b6b526ee63/lektor/db.py#L818) have been [deprecated](https://github.com/lektor/lektor/blob/f135d73a11ac557bff4f1068958e71b6b526ee63/lektor/imagetools.py#L598) since release 3.2.0.

This issue is here to make sure we don't forget to disable those features when the time is right.

(This issue should probably be attached to the [4.0 Milestone](https://github.com/lektor/lektor/milestone/5), but I don't think that I have sufficient privileges to do so.)

Refs: #551, #885

**Comment by yagebu** [comment]
Good point, I added this to the milestone 4.0 (and moved most of the current 4.0 to the "unplanned" milestone)
