### ISSUE TITLE
fix flaky windows test

### ISSUE THREAD

**Issue by yagebu** [lektor/lektor#941]
The CI tests that try to install the (non-Python) dependencies imagemagick and ffmpeg fail pretty regularly when trying to install those two packages with chocolatey. This seems to happen most often due to the imagemagick URL 404ing on us as far as I can tell. These steps are currently allowed to fail (which means that the parts of Lektor relying on those tools are not consistently tested on Windows), since those failures are not highlighting any problems in Lektor itself.

However, it would be nice if ~~Windows didn't exist~~ we could get consistent tests on Windows as well. winget as an alternative package manager was suggested in #933, that might be worth a shot (it doesn't have ffmpeg but then the ffmpeg install doesn't seem as problematic with chocolatey).

**Comment by dairiki** [comment]
Spitballing: Maybe we could just install the windows binary image directly from the [ImageMagick download site](https://imagemagick.org/script/download.php#windows)?  (There are a lot of different binary versions there — I'm not at all sure which would be most appropriate.)
