### ISSUE TITLE
BUG: attaching images are stored with a broken URL

### ISSUE THREAD

**Issue by andreamoro** [lektor/lektor#950]
Still trying to play around with Lektor and I have tried to attach an image into a post to see how this is handled.
Aside from the fact I don't see any changes in the local contents.lr file, when working with the web interface, the URL is clearly wrong as it appears nested twice under the containing parent folder, thus making the file not reachable by the webserver.

To make it clear, the local path is ..../website/content/blog/test but in the web interface the image is shown under http://127.0.0.1:5000/en/blog/test/en/blog/test/screenshot-from-2021-10-31-09-05-11.png/

See below image of the local folder

![image](https://user-images.githubusercontent.com/5256583/144921151-c52d2385-be6e-49e5-8cc7-07c7f62da55b.png)

I'm not entirely sure this is due to the alternatives settings. If I delete them from the settings file, regrettably I will lose the testing files as apparently these are deleted immediately after. 
Any idea of what the problem can be?

**Comment by tomgross** [comment]
Here is a minimal example based on the  boilerplate blog:  https://github.com/tomgross/test-for-lektor-issue
See http://localhost:5000/blog/first-post/ and http://localhost:5000/de/blog/first-post/

**Comment by dairiki** [comment]
Just a note: an (untested) workaround, in the interim is to link to the attachment by full absolute path.  E.g. in your `markdown` field, instead of

```md
![my screenshot](screenshot-from-2021-10-31-09-05-11.png)
```

do

```md
![my screenshot](/blog/test/screenshot-from-2021-10-31-09-05-11.png)
```

I realize that this is less than ideal, but I _think_ it should work, at least.

**Comment by andreamoro** [comment]
Hi Both,

Not sure I capture the nuances in the contents+de.lr @tomgross. But I guess that's the key objective I want to investigate/improve.

I believe improvements on the alternative part should be done so to:
- have alternatives having their own url property with which internal URLs can be generated
-- whether absolute or relative, this should not make any difference
- url property to be used only during the build used for the publication
-- here correct me whether my understanding is wrong, but it seems like lektor server is using the build also internally
- find a way to move the static under the alternative folders when this is in place

I appreciate this is not the best place to discuss this feature here, so my question is: do we have a place? 
It would be great joining forces rather than creating individual forks with people inventing something that might never find place in the final code. 
Do you think we can regroup somewhere? I trust you have more experience than I do with this SSG and you may know things I barely scratched during my early days.

**Comment by dairiki** [comment]
See also #313, #470, and #88 for additional discussion and history of this (or perhaps a similar) problem.
