### ISSUE TITLE
WebUI deprecated method warning at line 77 of /admin/webui.py

### ISSUE THREAD

**Issue by andreamoro** [lektor/lektor#956]
The flask.helpers.safe_join will be deprecated from Flask 2.1. A use 'werkzeug.utils.safe_join' instead message is returned.

There are also additional deprecation messages that keep appearing on my end. I will try to fix them in the 3.2-maintenance branch unless contrary indications from anybody?

**Comment by dairiki** [comment]
I've just backported #923 to the `3.2-maintenance` branch (in 41c13bf.)  This should take care of these warnings (once the next release is made.)
