### ISSUE TITLE
Admin GUI breaks if page contains an unknown flowblock type

### ISSUE THREAD

**Issue by dairiki** [lektor/lektor#968]
To reproduce:
1. Fire up the server on the demo project in the tests subdirectory
```sh
cd tests/demo-project
lektor server --browse
```
2. Click the pencil to edit the top "Welcome" page
3. Try to add a _text_ flowblock
     (Nothing happens except there are two tracebacks in the javascript console.)

The cause seems to have something to do with the fact that the _Welcome_ page's [`contents.lr`](https://raw.githubusercontent.com/lektor/lektor/a31d8e57a5b2f4b090072527269c26a65202c736/tests/demo-project/content/contents.lr) contains two flowblocks, one of type `text`, and one of type `quote`.  There is no definition of the _quote_ flowblock in [`tests/demo-project/flowblocks`](https://github.com/lektor/lektor/tree/a31d8e57a5b2f4b090072527269c26a65202c736/tests/demo-project/flowblocks) — this appears to be what causes issues.  If one manually creates an appropriate definition of a _quote_ flowblock in `tests/demo-project/flowblocks/quote.ini`, then all works well.

**Comment by yagebu** [comment]
This is (inadvertently) fixed by #977 :)
