### ISSUE TITLE
Lektor Admin console edit the wrong document when alternatives are used

### ISSUE THREAD

**Issue by ikus060** [lektor/lektor#975]
Using the latest version of Lektor v3.3.0, when using the Admin console to edit a page. The link return by the little pen in the top left corner is not the right URL.

e.g.: When browsing the page `http://localhost:5000/en/support/` the edit link is define as `http://localhost:5000/admin/edit?path=%2Fen%2Fsupport%2F`.

What links is wrong and doesn't allow proper editing of the page. The appropriate link should be `http://localhost:5000/admin/root:support/edit`

This is a regression when comparing to lektor v3.2.2.

Here my project file:
```
[project]
name = IKUS Software inc
name[fr] = Logiciel IKUS inc
url=https://www.ikus-soft.com/
url_style=absolute
excluded_assets=*.less

[alternatives.en]
name = English
name[fr] = English
locale = en_US
url_prefix = /en/

[alternatives.fr]
primary = yes
name = Francais
name[fr] = Francais
url_prefix = /fr/
locale = fr

[packages]
lektor-make
lektor-git-src-publisher
lektor-disqus-comments = 0.2
lektor-pythonmarkdown = 1.2
```

**Comment by dairiki** [comment]
Thank you for the report.

I can reproduce, but I don't think it's a regression.  I think this bug has always existed.

This edit URL is [generated client-side by javascript][1].  It's set to `/admin/edit?path=`_<document.location.pathname>_.  It's always been so.

Fixing will be a least a little tricky.  Right now there is no great way to convert from arbitrary URL path to Lektor db path (which is what is required), except in the lucky (and, thankfully, common) case where the two paths are the same.  They are not the same when alts are in use (for the non-primary alts) and with pages (or their parents) set a custom slug.

A couple of ideas:
- Use the build database to map from artifact name (related to URL path) back to primary source Lektor path.  I think there can be more than one primary source, however.  And the build database might be stale.
- For the alt case, iterate through the alts, checking the path against the prefix and suffix for the alt, and demangle the path appropriately if both match.
- Maybe embed the Lektor source path in the HTML output in a way that's accessible by the Javascript?

[1]: https://github.com/lektor/lektor/blob/19486da795ba5dff7a8abf39302e3ec2c6429dd0/lektor/admin/modules/serve.py#L62

**Comment by dairiki** [comment]
> A couple of ideas:
> 
> * Use the build database to map from artifact name (related to URL path) back to primary source Lektor path.  I think there can be more than one primary source, however.  And the build database might be stale.

After more careful inspection, this is not possible without augmenting the db schema.  There is nothing the (sqlite3) db that maps artifact to source path.

> * For the alt case, iterate through the alts, checking the path against the prefix and suffix for the alt, and demangle the path appropriately if both match.

This might work for handling alts.  I don't think it will work for custom slugs.

> * Maybe embed the Lektor source path in the HTML output in a way that's accessible by the Javascript?

Hokey.  Care will need to be taken not to mangle non-HTML (e.g. XML or plain text) "pages".

**Comment by ikus060** [comment]
> I can reproduce, but I don't think it's a regression. I think this bug has always existed.

It definitively worked with 3.1.2. I stick to that version to avoid this bug.

> Hokey. Care will need to be taken not to mangle non-HTML (e.g. XML or plain text) "pages".

The same feature used to inject the little edit button in top left corner could be used to inject metadata like the original source name.

**Comment by ikus060** [comment]
Had a deeper look at it worked on 3.1.2.
The link for page `/fr/support` is `http://localhost:5000/admin/edit?path=%2Ffr%2Fsupport%2F` which get redirected to `http://localhost:5000/admin/root:support%2Bfr/edit` which allow to edit the page properly. Look like a series of bug making it worked.

**Comment by dairiki** [comment]
Okay, well, never mind all of my above comments. :-P
(There is, of course, a way to resolve URL path to db path.  It is `Pad.resolve_url_path`, and it appears to be working correctly, as evidenced by the redirect.)

This appears to be a regression in the client-side (javascript) code.  At some point, the GUI app stopped correctly decoding that `/root:support%2Bfr/` in the `document.location` to `/root:support+fr/`.

After some bisecting, it appears the regression happened in 5672b976319b9ea2875a9c586466422deeeeab99, a large commit which upgraded react-router from v3 to v5 (see #739).

I do not know enough about React to efficiently work on this.  @yagebu, would you take a look when you have the chance?

**Comment by dairiki** [comment]
This bug currently exists in the `3.2-maintenance` branch as well as `master`. It affects releases 3.2.0–3.2.3 as well as 3.3.0.
The last Lektor release without this bug appears to be 3.1.3.
