### ISSUE TITLE
Lektor server doubles subfolder in url without obvious reason

### ISSUE THREAD

**Issue by maste9** [lektor/lektor#997]
I have a strange problem regarding the lektor server:

While my navigation works perfectly with every page and subpage, links to subpages in the content section don't. 

E.g. if I set a relative path like 

    [My Link to Subpage](/peter/personalinfo)
it is correctly solved in the browser view. If I hover the mouse over the link the browser shows the correct url 127.0.0.1:5000/peter/personalinfo.

But if I click it I get

    Not Found

    The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

and the url in the address field shows 

    127.0.0.1:5000/peter/peter/personalinfo

I.e. I click the correct url but the browser calls the wrong url and of course can't find anything there.
I don't understand how this doubling can happen. I naively would expect that if I clicked a link the browser would exactly look at that address. But it seems like the server is redirecting to the malformed url. And yes, it does so with any link to a subpage.

the navigation looks like this:

    Home
    News
    Peter
    -- Personalinfo
    -- Contact
    -- Portfolio
    Bob
    -- Personalinfo
    -- Contact
    -- Portfolio

That only occurs with the lektor server. If I `lektor build` and/or deploy it the whole project works fine.

Any idea why this happens and how to change it? 

It happens under Ubuntu 20.04, MacOS Monterey and with both lektor 3.2 and 3.31.

**Comment by paternal** [comment]
Hello. I have the same issue; I wondered if it was a Lektor issue or a Firefox issue.

My workaround is adding a slash ``/`` at the end of the URL, that is ``[My Link to Subpage](/peter/personalinfo/)`` instead of ``[My Link to Subpage](/peter/personalinfo)``

**Comment by dairiki** [comment]
This is, I think, a bug having to do with the use of `werkzeug.utils.append_slash_redirect` to redirect to slash-append URLs when appropriate.  The issue is that `append_slash_redirect`, at least as we are using it, does not work correctly if PATH_INFO has internal slashes.

As you can see in pallets/werkzeug#1538, there appears to be some disagreement over whether this is or is not a bug in `append_slash_redirect`. In any case, it looks like — bug or not — will not be getting fixed on the werkzeug side any time soon.

I've just fixed the issue as (a small) part of a general refactor of Lektor's admin server (PR #987), but that's not in master yet.  The fix for the add-slash redirect is in da49febcd37bb26db63c74e05e18ab8b7d2605a4.

The workaround, as @paternal says, is to add a trailing slash to the URL, thus avoiding the redirect altogether.

If this is causing a lot of grief, let me know... I can push a quick fix to master.

**Comment by nixjdm** [comment]
| If this is causing a lot of grief, let me know... I can push a quick fix to master.

For me, I wouldn't say a lot of grief, but for sure a mild annoyance. I noticed this at about the same time. I'll be happy to see this fixed, one way or the other.

**Comment by dairiki** [comment]
I have now made an attempt at an upstream fix: pallets/werkzeug#2338.

**Comment by maste9** [comment]
> If this is causing a lot of grief, let me know... I can push a quick fix to master.

There's no hurry to me. I can work around it for the moment. I just thought that this might give new users the impression that the application is somehow broken and so won't stick to a very appreciable tool. It would have spared me some time when I was learning how to use lektor properly and haven't been sure if it's a bug or I am doing it wrong.

And of course it would increase my flow a little if it was fixed 😏 But imho there's no need for a quickfix as long as your upstream fix is accepted.

**Comment by relikd** [comment]
Perfect timing to get here! @dairiki your PR was merged 8 days ago, congrats. Now we need to wait until the changes are reflected in lektor werkzeug dependency. :)

**Comment by dairiki** [comment]
There's also a fix for this in our PR #987, which, I think, is about ready to be merged.
That fix disuses werkzeug's `append_slash_redirect` in favor of our own (fairly trivial) implementation (see 7c8466d98754a3975e20b3c84410f7287c32f9e3).  If we keep that in then we don't need to pin to latest werkzeug.

**Comment by dairiki** [comment]
This has been fixed in master (via #987), so I'm closing this issue.

It may be a little while before master sees a new release (as it will be a version bump to 3.4.0.)  If anyone really needs this fixed in a released version sooner, let me know, and I'll backport something to 3.3.x.
